# Converting Words to Vectors

After text preprocessing, we will now try to give meaning to each word for the computer to understand. This where we apply different techniques to convert each word to vectors. Some of the techniques used are:
* One Hot Encoding (OHE)
* Bag Of Words (BOW)
* Term Frequency-Inverse Document Frequency (TF-IDF)
* Word2Vec
* AvgWord2Vec

Visit your note for the application of these techniques and how they work. Identify their advantage and disadvantage.

## BAG OF WORDS

In [1]:
import pandas as pd
messages=pd.read_csv("SMSSpamCollection.txt",sep='\t',names=['label','message'])

## '\t' is a tab separated variable

In [2]:
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
## Data cleaning and preprocessing
import re ## import regular-expression
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [4]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

ps=PorterStemmer()

In [5]:
corpus=[]
for i in range(0,len(messages)):
    ## remove special characters
    review=re.sub('[^a-zA-z]', ' ', messages['message'][i]) ## This says- apart from small and capital a-z any other thing you find replace it with blankspace. Perform this is in the data provided
    review=review.lower()
    review_words=review.split()
    stemmed_review_words=[ps.stem(word) for word in review_words if not word in stopwords.words('english')]
    stemmed_review_sentence=' '.join(stemmed_review_words)
    corpus.append(stemmed_review_sentence)

In [6]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather promis wont take help grant fulfil promis wonder bless time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt messag click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k watch',
 'eh u rememb spell name ye v naughti make v wet',
 'fine way u feel way gota b',
 'england v macedonia dont miss goal team news txt ur nation team eg england tri wale scotland txt poboxox w wq',
 'serious spell name',
 'go tri month ha ha joke',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch alreadi',
 'ffffffffff alright way meet sooner',
 'forc eat slice realli hungri tho suck mark get worri know sick turn pizza lol',
 'lol alway convinc',
 'catch bu fri egg make tea eat mom left dinner feel love',
 'back amp pack car let know room',
 'ahhh work vagu rememb feel like lol',
 'wait still clear sure sarcast x want live us',
 'yeah got v apologet n fallen actin like spoilt child got caught till go badli cheer',
 'k tell anyth',
 'fear faint housework quick cuppa',
 'thank subscript rington uk mobil charg month pleas confirm repli ye repli charg',
 'yup ok go home look time msg xuhui go learn nd may lesson',
 'oop let know roommat done',
 'see letter b car',
 'anyth lor u decid',
 'hello saturday go text see decid anyth tomo tri invit anyth',
 'pl go ahead watt want sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummi',
 'rodger burn msg tri call repli sm free nokia mobil free camcord pleas call deliveri tomorrow',
 'see',
 'great hope like man well endow lt gt inch',
 'call messag miss call',
 'get hep b immunis nigeria',
 'fair enough anyth go',
 'yeah hope tyler could mayb ask around bit',
 'u know stubborn even want go hospit kept tell mark weak sucker hospit weak sucker',
 'think first time saw class',
 'gram usual run like lt gt half eighth smarter though get almost whole second gram lt gt',
 'k fyi x ride earli tomorrow morn crash place tonight',
 'wow never realiz embarass accomod thought like sinc best could alway seem happi cave sorri give sorri offer sorri room embarass',
 'sm ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end repli end sptv',
 'know mallika sherawat yesterday find lt url gt',
 'congrat year special cinema pass call c suprman v matrix starwar etc free bx ip pm dont miss',
 'sorri call later meet',
 'tell reach',
 'ye gauti sehwag odi seri',
 'gonna pick burger way home even move pain kill',
 'ha ha ha good joke girl situat seeker',
 'part check iq',
 'sorri roommat took forev ok come',
 'ok lar doubl check wif da hair dresser alreadi said wun cut v short said cut look nice',
 'valu custom pleas advis follow recent review mob award bonu prize call',
 'today song dedic day song u dedic send ur valuabl frnd first rpli',
 'urgent ur award complimentari trip eurodisinc trav aco entri claim txt di morefrmmob shracomorsglsuplt ls aj',
 'hear new divorc barbi come ken stuff',
 'plane give month end',
 'wah lucki man save money hee',
 'finish class',
 'hi babe im home wanna someth xx',
 'k k perform',
 'u call',
 'wait machan call free',
 'that cool gentleman treat digniti respect',
 'like peopl much shi pa',
 'oper lt gt',
 'still look job much ta earn',
 'sorri call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later network urgnt sm',
 'real u get yo need ticket one jacket done alreadi use multi',
 'ye start send request make pain came back back bed doubl coin factori gotta cash nitro',
 'realli still tonight babe',
 'ela kano il download come wen ur free',
 'yeah stand close tho catch someth',
 'sorri pain ok meet anoth night spent late afternoon casualti mean done stuff moro includ time sheet sorri',
 'smile pleasur smile pain smile troubl pour like rain smile sum hurt u smile becoz someon still love see u smile',
 'pleas call custom servic repres pm guarante cash prize',
 'havent plan buy later check alreadi lido got show e afternoon u finish work alreadi',
 'free rington wait collect simpli text password mix verifi get usher britney fml po box mk h ppw',
 'watch telugu movi wat abt u',
 'see finish load loan pay',
 'hi wk ok hol ye bit run forgot hairdress appoint four need get home n shower beforehand caus prob u',
 'see cup coffe anim',
 'pleas text anymor noth els say',
 'okay name ur price long legal wen pick u ave x am xx',
 'still look car buy gone drive test yet',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'wow right mean guess gave boston men chang search locat nyc someth chang cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thank lot wish birthday thank make birthday truli memor',
 'aight hit get cash',
 'would ip address test consid comput minecraft server',
 'know grumpi old peopl mom like better lie alway one play joke',
 'dont worri guess busi',
 'plural noun research',
 'go dinner msg',
 'ok wif co like tri new thing scare u dun like mah co u said loud',
 'gent tri contact last weekend draw show prize guarante call claim code k valid hr ppm',
 'wa ur openin sentenc formal anyway fine juz tt eatin much n puttin weight haha anythin special happen',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'winner u special select receiv holiday flight inc speak live oper claim p min',
 'goodo ye must speak friday egg potato ratio tortilla need',
 'hmm uncl inform pay school directli pl buy food',
 'privat account statement show unredeem bonu point claim call identifi code expir',
 'urgent mobil award bonu caller prize final tri contact u call landlin box wr c ppm',
 'new address appl pair malarki',
 'today voda number end select receiv award match pleas call quot claim code standard rate app',
 'go sao mu today done',
 'predict wat time finish buy',
 'good stuff',
 'know yetund sent money yet sent text bother send dont involv anyth impos anyth first place apologis',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'k k much cost',
 'home',
 'dear call tmorrow pl accomod',
 'first answer question',
 'sunshin quiz wkli q win top soni dvd player u know countri algarv txt ansr sp tyron',
 'want get laid tonight want real dog locat sent direct ur mob join uk largest dog network bt txting gravel nt ec p msg p',
 'haf msn yiju hotmail com',
 'call meet',
 'check room befor activ',
 'rcv msg chat svc free hardcor servic text go u get noth u must age verifi yr network tri',
 'got c lazi type forgot lect saw pouch like v nice',
 'k text way',
 'sir wait mail',
 'swt thought nver get tire littl thing lovabl person coz somtim littl thing occupi biggest part heart gud ni',
 'know pl open back',
 'ye see ya dot',
 'what staff name take class us',
 'freemsg repli text randi sexi femal live local luv hear u netcollex ltd p per msg repli stop end',
 'ummma call check life begin qatar pl pray hard',
 'k delet contact',
 'sindu got job birla soft',
 'wine flow never',
 'yup thk cine better co need go plaza mah',
 'ok ur typic repli',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'everywher dirt floor window even shirt sometim open mouth come flow dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time done becom one',
 'aaooooright work',
 'leav hous',
 'hello love get interview today happi good boy think miss',
 'custom servic annonc new year deliveri wait pleas call arrang deliveri',
 'winner u special select receiv cash holiday flight inc speak live oper claim',
 'keep safe need miss alreadi envi everyon see real life',
 'new car hous parent new job hand',
 'love excit day spend make happi',
 'pl stop bootydeli f invit friend repli ye see www sm ac u bootydeli stop send stop frnd',
 'bangbab ur order way u receiv servic msg download ur content u goto wap bangb tv ur mobil internet servic menu',
 'place ur point e cultur modul alreadi',
 'urgent tri contact last weekend draw show prize guarante call claim code valid hr',
 'hi frnd best way avoid missunderstd wit belov one',
 'great escap fanci bridg need lager see tomo',
 'ye complet form clark also utter wast',
 'sir need axi bank account bank address',
 'hmmm thk sure got time hop ard ya go free abt muz call u discuss liao',
 'time come later',
 'bloodi hell cant believ forgot surnam mr ill give u clue spanish begin',
 'well gonna finish bath good fine night',
 'let know got money carlo make call',
 'u still go mall',
 'turn friend stay whole show back til lt gt feel free go ahead smoke lt gt worth',
 'text doesnt repli let know log',
 'hi spoke maneesha v like know satisfi experi repli toll free ye',
 'lift hope offer money need especi end month approach hurt studi anyway gr weekend',
 'lol u trust',
 'ok gentleman treat digniti respect',
 'guy close',
 'go noth great bye',
 'hello handsom find job lazi work toward get back net mummi boytoy miss',
 'haha awesom minut',
 'pleas call custom servic repres freephon pm guarante cash prize',
 'got xma radio time get',
 'ju reach home go bath first si use net tell u finish k',
 'uniqu enough find th august www areyouuniqu co uk',
 'sorri join leagu peopl dont keep touch mean great deal friend time even great person cost great week',
 'hi final complet cours',
 'stop howev suggest stay someon abl give or everi stool',
 'hope settl new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u got person stori',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate even hope see tomorrow bit bloodi babyjontet txt back u xxx',
 'found enc lt gt',
 'sent lt gt buck',
 'hello darlin ive finish colleg txt u finish u love kate xxx',
 'account refil success inr lt decim gt keralacircl prepaid account balanc rs lt decim gt transact id kr lt gt',
 'goodmorn sleep ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'aight yo dat straight dogg',
 'pleas give us connect today lt decim gt refund bill',
 'shoot big load get readi',
 'bruv hope great break reward semest',
 'home alway chat',
 'k k good studi well',
 'yup noe leh',
 'sound great home',
 'final match head toward draw predict',
 'tire slept well past night',
 'easi ah sen got select mean good',
 'take exam march',
 'yeah think use gt atm regist sure anyway help let know sure readi',
 'ok prob take ur time',
 'os call ubandu run without instal hard disk use os copi import file system give repair shop',
 'sorri call later',
 'u say leh cours noth happen lar say v romant ju bit lor thk e nite sceneri nice leh',
 'new mobil must go txt nokia collect today www tc biz optout gbp mtmsg',
 'would realli appreci call need someon talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo follow ur star sign e g horo ari',
 'hey compani elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happi morn',
 'dear good morn',
 'get gandhipuram walk cross cut road right side lt gt street road turn first right',
 'dear go rubber place',
 'sorri batteri die yeah',
 'ye tv alway avail work place',
 'text meet someon sexi today u find date even flirt u join p repli name age eg sam msg recd thirtyeight penc',
 'print oh lt gt come upstair',
 'ill littl closer like bu stop street',
 'wil reach',
 'new theori argument win situat lose person dont argu ur friend kick amp say alway correct',
 'u secret admir look make contact u find r reveal think ur special call',
 'tomarrow final hear laptop case cant',
 'pleassssssseeeee tel v avent done sportsx',
 'okay shine meant sign sound better',
 'although told u dat baig face watch realli like e watch u gave co fr u thanx everyth dat u done today touch',
 'u rememb old commerci',
 'late said websit dont slipper',
 'ask call ok',
 'kalli wont bat nd inning',
 'didnt work oh ok goodnight fix readi time wake dearli miss good night sleep',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovabl bcum angri wid u dnt take serious coz angri childish n true way show deep affect care n luv kettoda manda nice day da',
 '',
 'up day also ship compani take wk way usp take week get lag may bribe nipost get stuff',
 'back lemm know readi',
 'necessarili expect done get back though headin',
 'mmm yummi babe nice jolt suzi',
 'lover need',
 'tri contact repli offer video handset anytim network min unlimit text camcord repli call',
 'park next mini come today think',
 'yup',
 'anyway go shop co si done yet dun disturb u liao',
 'luton ring ur around h',
 'hey realli horni want chat see nake text hot text charg pm unsubscrib text stop',
 'dint come us',
 'wana plan trip sometm',
 'sure yet still tri get hold',
 'ur rington servic chang free credit go club mobil com choos content stop txt club stop p wk club po box mk wt',
 'evo download flash jealou',
 'rington club get uk singl chart mobil week choos top qualiti rington messag free charg',
 'come mu sort narcot situat',
 'night end anoth day morn come special way may smile like sunni ray leav worri blue blue bay',
 'hmv bonu special pound genuin hmv voucher answer easi question play send hmv info www percent real com',
 'usf guess might well take car',
 'object bf come',
 'thanx',
 'tell rob mack gf theater',
 'awesom see bit',
 'sent type food like',
 'done hand celebr full swing yet',
 'got call tool',
 'wen u miss someon person definit special u person special miss keep touch gdeve',
 'ok ask money far',
 'oki',
 'yeah think usual guy still pass last night get ahold anybodi let know throw',
 'k might come tonight class let earli',
 'ok',
 'hi babi im cruisin girl friend r u give call hour home that alright fone fone love jenni xxx',
 'life mean lot love life love peopl life world call friend call world ge',
 'dear shall mail tonit busi street shall updat tonit thing look ok varunnathu edukkukaye raksha ollu good one real sens',
 'hey told name gautham ah',
 'haf u found feel stupid da v cam work',
 'oop got bit',
 'much buzi',
 'accident delet messag resend pleas',
 'mobil custom may claim free camera phone upgrad pay go sim card loyalti call offer end thfeb c appli',
 'unless situat go gurl would appropri',
 'hurt teas make cri end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'cant pick phone right pl send messag',
 'need coffe run tomo believ time week alreadi',
 'awesom rememb last time got somebodi high first time diesel v',
 'shit realli shock scari cant imagin second def night u think somewher could crash night save taxi',
 'oh way food fridg want go meal tonight',
 'womdarful actor',
 'sm ac blind date u rodd aberdeen unit kingdom check http img sm ac w icmb cktz r blind date send hide',
 'yup remb think book',
 'jo ask u wana meet',
 'lol ye friendship hang thread caus u buy stuff',
 'themob check newest select content game tone gossip babe sport keep mobil fit funki text wap',
 'garag key bookshelf',
 'today accept day u accept brother sister lover dear best clo lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rpli mean enemi',
 'think ur smart win week weekli quiz text play cs winnersclub po box uz gbp week',
 'say give call friend got money definit buy end week',
 'hi way u day normal way real ur uniqu hope know u rest mylif hope u find wot lost',
 'made day great day',
 'k k advanc happi pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao',
 'realli dude friend afraid',
 'decemb mobil mth entitl updat latest colour camera mobil free call mobil updat co free',
 'coffe cake guess',
 'merri christma babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bit l co buse hav gon past co full im still waitin pete x',
 'would great guild could meet bristol road somewher get touch weekend plan take flight good week',
 'problem',
 'call messag miss call',
 'hi da today class',
 'say good sign well know track record read women',
 'cool text park',
 'read text sent meant joke read light',
 'k k apo k good movi',
 'mayb could get book tomo return immedi someth',
 'call germani penc per minut call fix line via access number prepay direct access',
 'chanc might evapor soon violat privaci steal phone number employ paperwork cool pleas contact report supervisor',
 'valentin day special win quiz take partner trip lifetim send go p msg rcvd custcar',
 'ta daaaaa home babe still',
 'cool come havent wine dine',
 'sleep surf',
 'sorri call later',
 'u call right call hand phone',
 'ok great thanx lot',
 'take post come must text happi read one wiv hello carolin end favourit bless',
 'u hide stranger',
 'interest like',
 'sister clear two round birla soft yesterday',
 'gudnit tc practic go',
 'di yiju ju saw ur mail case huim havent sent u num di num',
 'one small prestig problem',
 'fanci shag interest sextextuk com txt xxuk suzi txt cost per msg tnc websit x',
 'check realli miss see jeremiah great month',
 'nah help never iphon',
 'car hour half go apeshit',
 'today sorri day ever angri ever misbehav hurt plz plz slap urself bcoz ur fault basic good',
 'yo guy ever figur much need alcohol jay tri figur much safe spend weed',
 'lt gt ish minut minut ago wtf',
 'thank call forgot say happi onam sirji fine rememb met insur person meet qatar insha allah rakhesh ex tata aig join tissco tayseer',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'ur cash balanc current pound maxim ur cash send cash p msg cc hg suit land row w j hl',
 'actor work work even sleep late sinc unemploy moment alway sleep late unemploy everi day saturday',
 'hello got st andrew boy long way cold keep post',
 'ha ha cool cool chikku chikku db',
 'oh ok prob',
 'check audrey statu right',
 'busi tri finish new year look forward final meet',
 'good afternoon sunshin dawn day refresh happi aliv breath air smile think love alway',
 'well know z take care worri',
 'update_now xma offer latest motorola sonyericsson nokia free bluetooth doubl min txt orang call mobileupd call optout f q',
 'discount code rp stop messag repli stop www regalportfolio co uk custom servic',
 'wat uniform get',
 'cool text readi',
 'hello boytoy geeee miss alreadi woke wish bed cuddl love',
 'spoil bed well',
 'go bath msg next lt gt min',
 'cant keep talk peopl sure pay agre price pl tell want realli buy much will pay',
 'thank rington order refer charg gbp per week unsubscrib anytim call custom servic',
 'say happen',
 'could seen recognis face',
 'well lot thing happen lindsay new year sigh bar ptbo blue heron someth go',
 'keep payasam rinu bring',
 'taught ranjith sir call sm like becau he verifi project prabu told today pa dont mistak',

In [7]:
## Create the bag of words (BOW) model
## We will use sklearn's CountVectorizer for this
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
countvectorizer=CountVectorizer(max_features=2500)
## max_features=2500 is saying that out of all the words in the BOW take the top 2500 words
## for binary BOW set binary=True

In [9]:
X=countvectorizer.fit_transform(corpus).toarray()

In [10]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [11]:
X.shape

(5572, 2500)

### N Grams

We use this to create combination of words for improved sentence to vector transformation. Examples are unigram, bigrams, trigram etc

We will work an exampleon how to use N-grams

In [12]:
## Create bag of words model
from sklearn.feature_extraction.text import CountVectorizer
## for binary BOW
cv=CountVectorizer(max_features=100,binary=True)

In [13]:
X=cv.fit_transform(corpus).toarray()

In [14]:
import numpy as np
np.set_printoptions(
    edgeitems=30,
    linewidth=100000,
    formatter=dict(float=lambda x: "%.3g" % x))

X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ..., 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ..., 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..., 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [15]:
cv.vocabulary_ ## These re the top 100 vocabularies with their column index

{'go': 22,
 'great': 25,
 'got': 24,
 'wat': 90,
 'ok': 56,
 'free': 18,
 'win': 94,
 'text': 77,
 'txt': 85,
 'say': 67,
 'alreadi': 0,
 'think': 80,
 'hey': 28,
 'week': 92,
 'back': 3,
 'like': 38,
 'still': 73,
 'send': 69,
 'even': 15,
 'friend': 19,
 'prize': 62,
 'claim': 7,
 'call': 4,
 'mobil': 47,
 'co': 8,
 'home': 30,
 'want': 89,
 'today': 82,
 'cash': 6,
 'day': 12,
 'repli': 64,
 'www': 96,
 'right': 65,
 'thank': 78,
 'take': 75,
 'time': 81,
 'use': 87,
 'messag': 44,
 'oh': 55,
 'ye': 97,
 'make': 42,
 'way': 91,
 'feel': 16,
 'dont': 14,
 'miss': 46,
 'ur': 86,
 'tri': 84,
 'da': 11,
 'lor': 39,
 'meet': 43,
 'realli': 63,
 'get': 20,
 'know': 33,
 'love': 40,
 'let': 37,
 'work': 95,
 'wait': 88,
 'yeah': 98,
 'tell': 76,
 'pleas': 61,
 'msg': 49,
 'see': 68,
 'pl': 60,
 'need': 51,
 'tomorrow': 83,
 'hope': 31,
 'well': 93,
 'lt': 41,
 'gt': 26,
 'ask': 1,
 'morn': 48,
 'happi': 27,
 'sorri': 72,
 'give': 21,
 'new': 52,
 'find': 17,
 'year': 99,
 'later': 35,
 'pick': 59,
 'good': 23,
 'come': 9,
 'said': 66,
 'hi': 29,
 'babe': 2,
 'im': 32,
 'much': 50,
 'stop': 74,
 'one': 57,
 'night': 53,
 'servic': 70,
 'dear': 13,
 'thing': 79,
 'contact': 10,
 'last': 34,
 'min': 45,
 'number': 54,
 'leav': 36,
 'sleep': 71,
 'care': 5,
 'phone': 58}

In [16]:
len(cv.vocabulary_)

100

In [17]:
## Now let us implement n-gram
## Create the Bag Of Words model with ngram
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=100,binary=True,ngram_range=(1,1)) 
## with ngram_range as (1,1) the values will be tha same as the previous. This is unigram
X=cv.fit_transform(corpus).toarray()

In [18]:
cv.vocabulary_

{'go': 22,
 'great': 25,
 'got': 24,
 'wat': 90,
 'ok': 56,
 'free': 18,
 'win': 94,
 'text': 77,
 'txt': 85,
 'say': 67,
 'alreadi': 0,
 'think': 80,
 'hey': 28,
 'week': 92,
 'back': 3,
 'like': 38,
 'still': 73,
 'send': 69,
 'even': 15,
 'friend': 19,
 'prize': 62,
 'claim': 7,
 'call': 4,
 'mobil': 47,
 'co': 8,
 'home': 30,
 'want': 89,
 'today': 82,
 'cash': 6,
 'day': 12,
 'repli': 64,
 'www': 96,
 'right': 65,
 'thank': 78,
 'take': 75,
 'time': 81,
 'use': 87,
 'messag': 44,
 'oh': 55,
 'ye': 97,
 'make': 42,
 'way': 91,
 'feel': 16,
 'dont': 14,
 'miss': 46,
 'ur': 86,
 'tri': 84,
 'da': 11,
 'lor': 39,
 'meet': 43,
 'realli': 63,
 'get': 20,
 'know': 33,
 'love': 40,
 'let': 37,
 'work': 95,
 'wait': 88,
 'yeah': 98,
 'tell': 76,
 'pleas': 61,
 'msg': 49,
 'see': 68,
 'pl': 60,
 'need': 51,
 'tomorrow': 83,
 'hope': 31,
 'well': 93,
 'lt': 41,
 'gt': 26,
 'ask': 1,
 'morn': 48,
 'happi': 27,
 'sorri': 72,
 'give': 21,
 'new': 52,
 'find': 17,
 'year': 99,
 'later': 35,
 'pick': 59,
 'good': 23,
 'come': 9,
 'said': 66,
 'hi': 29,
 'babe': 2,
 'im': 32,
 'much': 50,
 'stop': 74,
 'one': 57,
 'night': 53,
 'servic': 70,
 'dear': 13,
 'thing': 79,
 'contact': 10,
 'last': 34,
 'min': 45,
 'number': 54,
 'leav': 36,
 'sleep': 71,
 'care': 5,
 'phone': 58}

In [19]:
## Create the Bag Of Words model with ngram
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=200,binary=True,ngram_range=(1,2)) 
## max features increased to 200 for more illustration
## with ngram_range as (1,2). Here we combine unigram and bigram
X=cv.fit_transform(corpus).toarray()

In [20]:
cv.vocabulary_

{'go': 51,
 'great': 55,
 'got': 54,
 'wat': 183,
 'ok': 117,
 'free': 47,
 'win': 189,
 'st': 153,
 'may': 94,
 'text': 161,
 'txt': 174,
 'dun': 37,
 'say': 138,
 'alreadi': 0,
 'think': 164,
 'live': 83,
 'around': 5,
 'hey': 65,
 'week': 186,
 'word': 191,
 'back': 9,
 'like': 81,
 'still': 155,
 'send': 140,
 'even': 40,
 'per': 120,
 'friend': 48,
 'custom': 31,
 'prize': 132,
 'claim': 22,
 'call': 14,
 'hour': 70,
 'mobil': 101,
 'month': 103,
 'co': 23,
 'gonna': 52,
 'home': 68,
 'soon': 150,
 'want': 182,
 'talk': 159,
 'tonight': 172,
 'today': 168,
 'cash': 19,
 'cost': 29,
 'day': 33,
 'repli': 135,
 'urgent': 177,
 'www': 194,
 'right': 136,
 'thank': 162,
 'take': 158,
 'help': 64,
 'time': 167,
 'use': 179,
 'next': 110,
 'messag': 97,
 'com': 26,
 'oh': 116,
 'watch': 184,
 'name': 107,
 'ye': 196,
 'make': 91,
 'fine': 44,
 'way': 185,
 'feel': 42,
 'dont': 36,
 'miss': 100,
 'ur': 176,
 'tri': 173,
 'first': 46,
 'da': 32,
 'finish': 45,
 'lor': 86,
 'meet': 96,
 'realli': 134,
 'get': 49,
 'know': 74,
 'lol': 84,
 'alway': 2,
 'love': 88,
 'amp': 3,
 'car': 17,
 'let': 79,
 'work': 192,
 'wait': 180,
 'sure': 157,
 'us': 178,
 'yeah': 197,
 'tell': 160,
 'anyth': 4,
 'uk': 175,
 'pleas': 128,
 'look': 85,
 'msg': 105,
 'done': 35,
 'see': 139,
 'pl': 124,
 'need': 108,
 'sm': 146,
 'nokia': 113,
 'tomorrow': 170,
 'pleas call': 129,
 'hope': 69,
 'man': 92,
 'well': 187,
 'lt': 89,
 'gt': 56,
 'lt gt': 90,
 'could': 30,
 'ask': 6,
 'bit': 11,
 'morn': 104,
 'place': 125,
 'thought': 166,
 'best': 10,
 'happi': 62,
 'sorri': 151,
 'give': 50,
 'offer': 115,
 'new': 109,
 'play': 127,
 'end': 38,
 'find': 43,
 'year': 198,
 'special': 152,
 'pm': 130,
 'later': 77,
 'call later': 15,
 'reach': 133,
 'pick': 123,
 'good': 53,
 'check': 21,
 'come': 27,
 'said': 137,
 'nice': 111,
 'award': 7,
 'money': 102,
 'hi': 66,
 'babe': 8,
 'im': 71,
 'someth': 149,
 'peopl': 119,
 'much': 106,
 'job': 72,
 'stop': 156,
 'one': 118,
 'start': 154,
 'night': 112,
 'late': 76,
 'mean': 95,
 'smile': 147,
 'someon': 148,
 'servic': 142,
 'guarante': 57,
 'plan': 126,
 'buy': 13,
 'show': 144,
 'collect': 25,
 'box': 12,
 'yet': 199,
 'life': 80,
 'lot': 87,
 'dear': 34,
 'wish': 190,
 'would': 193,
 'thing': 163,
 'contact': 28,
 'last': 75,
 'ppm': 131,
 'haha': 60,
 'happen': 61,
 'went': 188,
 'holiday': 67,
 'min': 98,
 'number': 114,
 'sent': 141,
 'chat': 20,
 'person': 121,
 'heart': 63,
 'gud': 58,
 'ya': 195,
 'thk': 165,
 'leav': 78,
 'keep': 73,
 'also': 1,
 'cant': 16,
 'guy': 59,
 'minut': 99,
 'co uk': 24,
 'everi': 41,
 'sleep': 145,
 'shop': 143,
 'told': 169,
 'care': 18,
 'phone': 122,
 'tone': 171,
 'line': 82,
 'enjoy': 39,
 'mani': 93,
 'wan': 181}

If you go through the dictionary you will find some double word combination. Please refer to note for detailed explanation

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=200,binary=True,ngram_range=(2,2)) 
## max features increased to 200 for more illustration
## with ngram_range as (2,2). Here we combine using bigram only (ignoring unigram)
X=cv.fit_transform(corpus).toarray()

In [22]:
cv.vocabulary_

{'free entri': 55,
 'rate appli': 134,
 'claim call': 28,
 'call claim': 8,
 'claim code': 29,
 'free call': 54,
 'call mobil': 16,
 'chanc win': 27,
 'txt word': 177,
 'let know': 94,
 'feel like': 52,
 'repli ye': 140,
 'go home': 64,
 'call repli': 20,
 'mobil free': 107,
 'pleas call': 126,
 'lt gt': 102,
 'miss call': 105,
 'want go': 191,
 'first time': 53,
 'like lt': 95,
 'sm ac': 152,
 'sorri call': 153,
 'call later': 14,
 'award bonu': 5,
 'prize call': 131,
 'ur award': 180,
 'call free': 10,
 'that cool': 167,
 'call custom': 9,
 'custom servic': 40,
 'servic repres': 149,
 'guarante cash': 75,
 'cash prize': 26,
 'po box': 127,
 'tri contact': 172,
 'draw show': 45,
 'show prize': 150,
 'prize guarante': 133,
 'guarante call': 74,
 'valid hr': 187,
 'select receiv': 146,
 'speak live': 154,
 'live oper': 98,
 'privat account': 130,
 'account statement': 0,
 'statement show': 157,
 'call identifi': 11,
 'identifi code': 88,
 'code expir': 33,
 'urgent mobil': 185,
 'bonu caller': 6,
 'caller prize': 21,
 'call landlin': 13,
 'receiv award': 136,
 'wat time': 193,
 'give call': 61,
 'ur mob': 183,
 'go get': 63,
 'gud ni': 77,
 'repli stop': 139,
 'new year': 115,
 'send stop': 148,
 'ur mobil': 184,
 'urgent tri': 186,
 'get back': 58,
 'reach home': 135,
 'co uk': 32,
 'gud mrng': 76,
 'nice day': 117,
 'lt decim': 101,
 'decim gt': 42,
 'txt nokia': 175,
 'good morn': 69,
 'ur friend': 181,
 'secret admir': 145,
 'look make': 99,
 'reveal think': 141,
 'think ur': 168,
 'special call': 155,
 'good night': 70,
 'draw txt': 46,
 'txt music': 174,
 'www ldew': 199,
 'ldew com': 93,
 'anytim network': 2,
 'network min': 112,
 'camcord repli': 22,
 'repli call': 138,
 'text stop': 165,
 'last night': 91,
 'camera phone': 23,
 'cant pick': 24,
 'pick phone': 124,
 'phone right': 123,
 'right pl': 142,
 'pl send': 125,
 'send messag': 147,
 'great day': 71,
 'love ya': 100,
 'hg suit': 82,
 'suit land': 159,
 'land row': 90,
 'row hl': 143,
 'good afternoon': 67,
 'take care': 161,
 'doubl min': 44,
 'min txt': 104,
 'call mobileupd': 17,
 'mobileupd call': 109,
 'call optout': 18,
 'gt min': 73,
 'half price': 79,
 'line rental': 97,
 'txt stop': 176,
 'date servic': 41,
 'entri weekli': 49,
 'pobox wq': 128,
 'last week': 92,
 'mobil number': 108,
 'call land': 12,
 'land line': 89,
 'line claim': 96,
 'claim valid': 31,
 'watch tv': 194,
 'call min': 15,
 'wc xx': 195,
 'gt lt': 72,
 'hope good': 86,
 'good day': 68,
 'free text': 57,
 'text back': 164,
 'holiday cash': 85,
 'prize claim': 132,
 'tone repli': 170,
 'http www': 87,
 'nd attempt': 111,
 'attempt contact': 3,
 'claim ur': 30,
 'text ye': 166,
 'show un': 151,
 'un redeem': 179,
 'redeem point': 137,
 'point call': 129,
 'goe day': 66,
 'across sea': 1,
 'happi birthday': 80,
 'new video': 114,
 'video phone': 188,
 'one day': 121,
 'ok lor': 120,
 'want come': 190,
 'make sure': 103,
 'ts cs': 173,
 'stop text': 158,
 'everi week': 50,
 'come home': 36,
 'new nokia': 113,
 'next week': 116,
 'happi new': 81,
 'everi wk': 51,
 'wk txt': 197,
 'nation rate': 110,
 'free st': 56,
 'st week': 156,
 'nokia tone': 119,
 'tone ur': 171,
 'week txt': 196,
 'nokia get': 118,
 'tell ur': 163,
 'ur mate': 182,
 'www getz': 198,
 'getz co': 59,
 'uk pobox': 178,
 'gift voucher': 60,
 'cash await': 25,
 'await collect': 4,
 'sae cs': 144,
 'wan go': 189,
 'cs www': 39,
 'dont know': 43,
 'contact today': 38,
 'today draw': 169,
 'come back': 35,
 'mob everi': 106,
 'gud nyt': 78,
 'take part': 162,
 'call per': 19,
 'per min': 122,
 'sweet dream': 160,
 'bt nation': 7,
 'go back': 62,
 'go sleep': 65,
 'dun wan': 47,
 'come tomorrow': 37,
 'easi call': 48,
 'holiday await': 84,
 'collect call': 34,
 'hi darlin': 83,
 'want new': 192}

You can do the same for trigram (3,3). Note:(1,3) will run unigram, bigram and trigram. When training you can run hyperparameters to test different combinations to get the best accuracy.

## TEXT FREQUENCY-INVERSE DOCUMENT FREQUENCY (TF-IDF)

Check note for explanation.

We will carry out the same process we carried out before.

In [23]:
import pandas as pd
messages=pd.read_csv('SMSSpamCollection.txt',sep='\t',names=['label','message'])
messages

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [24]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [27]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
wnl=WordNetLemmatizer()

In [28]:
corpus=[]
for i in range(0,len(messages)):
    ## remove special characters
    review=re.sub('[^a-zA-z]', ' ', messages['message'][i]) ## This says- apart from small and capital a-z any other thing you find replace it with blankspace. Perform this is in the data provided
    review=review.lower()
    review_words=review.split()
    stemmed_review_words=[wnl.lemmatize(word) for word in review_words if not word in stopwords.words('english')]
    stemmed_review_sentence=' '.join(stemmed_review_words)
    corpus.append(stemmed_review_sentence)

In [29]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'searching right word thank breather promise wont take help granted fulfil promise wonderful blessing time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt message click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k watching',
 'eh u remember spell name yes v naughty make v wet',
 'fine way u feel way gota b',
 'england v macedonia dont miss goal team news txt ur national team eg england try wale scotland txt poboxox w wq',
 'seriously spell name',
 'going try month ha ha joking',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch already',
 'ffffffffff alright way meet sooner',
 'forced eat slice really hungry tho suck mark getting worried know sick turn pizza lol',
 'lol always convincing',
 'catch bus frying egg make tea eating mom left dinner feel love',
 'back amp packing car let know room',
 'ahhh work vaguely remember feel like lol',
 'wait still clear sure sarcastic x want live u',
 'yeah got v apologetic n fallen actin like spoilt child got caught till go badly cheer',
 'k tell anything',
 'fear fainting housework quick cuppa',
 'thanks subscription ringtone uk mobile charged month please confirm replying yes reply charged',
 'yup ok go home look timing msg xuhui going learn nd may lesson',
 'oops let know roommate done',
 'see letter b car',
 'anything lor u decide',
 'hello saturday go texting see decided anything tomo trying invite anything',
 'pls go ahead watt wanted sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummy',
 'rodger burn msg tried call reply sm free nokia mobile free camcorder please call delivery tomorrow',
 'seeing',
 'great hope like man well endowed lt gt inch',
 'call message missed call',
 'get hep b immunisation nigeria',
 'fair enough anything going',
 'yeah hopefully tyler could maybe ask around bit',
 'u know stubborn even want go hospital kept telling mark weak sucker hospital weak sucker',
 'thinked first time saw class',
 'gram usually run like lt gt half eighth smarter though get almost whole second gram lt gt',
 'k fyi x ride early tomorrow morning crashing place tonight',
 'wow never realized embarassed accomodations thought liked since best could always seemed happy cave sorry give sorry offered sorry room embarassing',
 'sm ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end reply end sptv',
 'know mallika sherawat yesterday find lt url gt',
 'congrats year special cinema pas call c suprman v matrix starwars etc free bx ip pm dont miss',
 'sorry call later meeting',
 'tell reached',
 'yes gauti sehwag odi series',
 'gonna pick burger way home even move pain killing',
 'ha ha ha good joke girl situation seeker',
 'part checking iq',
 'sorry roommate took forever ok come',
 'ok lar double check wif da hair dresser already said wun cut v short said cut look nice',
 'valued customer pleased advise following recent review mob awarded bonus prize call',
 'today song dedicated day song u dedicate send ur valuable frnds first rply',
 'urgent ur awarded complimentary trip eurodisinc trav aco entry claim txt dis morefrmmob shracomorsglsuplt l aj',
 'hear new divorce barbie come ken stuff',
 'plane give month end',
 'wah lucky man save money hee',
 'finished class',
 'hi babe im home wanna something xx',
 'k k performed',
 'u call',
 'waiting machan call free',
 'thats cool gentleman treat dignity respect',
 'like people much shy pa',
 'operate lt gt',
 'still looking job much ta earn',
 'sorry call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later network urgnt sm',
 'real u getting yo need ticket one jacket done already used multis',
 'yes started send request make pain came back back bed double coin factory gotta cash nitros',
 'really still tonight babe',
 'ela kano il download come wen ur free',
 'yeah stand close tho catch something',
 'sorry pain ok meet another night spent late afternoon casualty mean done stuff moro includes time sheet sorry',
 'smile pleasure smile pain smile trouble pours like rain smile sum hurt u smile becoz someone still love see u smiling',
 'please call customer service representative pm guaranteed cash prize',
 'havent planning buy later check already lido got show e afternoon u finish work already',
 'free ringtone waiting collected simply text password mix verify get usher britney fml po box mk h ppw',
 'watching telugu movie wat abt u',
 'see finish load loan pay',
 'hi wk ok hols yes bit run forgot hairdresser appointment four need get home n shower beforehand cause prob u',
 'see cup coffee animation',
 'please text anymore nothing else say',
 'okay name ur price long legal wen pick u ave x am xx',
 'still looking car buy gone driving test yet',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'wow right mean guess gave boston men changed search location nyc something changed cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thanks lot wish birthday thanks making birthday truly memorable',
 'aight hit get cash',
 'would ip address test considering computer minecraft server',
 'know grumpy old people mom like better lying always one play joke',
 'dont worry guess busy',
 'plural noun research',
 'going dinner msg',
 'ok wif co like try new thing scared u dun like mah co u said loud',
 'gent trying contact last weekend draw show prize guaranteed call claim code k valid hr ppm',
 'wa ur openin sentence formal anyway fine juz tt eatin much n puttin weight haha anythin special happened',
 'entered cabin pa said happy b day bos felt special askd lunch lunch invited apartment went',
 'winner u specially selected receive holiday flight inc speak live operator claim p min',
 'goodo yes must speak friday egg potato ratio tortilla needed',
 'hmm uncle informed paying school directly pls buy food',
 'private account statement show unredeemed bonus point claim call identifier code expires',
 'urgent mobile awarded bonus caller prize final try contact u call landline box wr c ppm',
 'new address apple pair malarky',
 'today voda number ending selected receive award match please call quoting claim code standard rate app',
 'going sao mu today done',
 'predict wat time finish buying',
 'good stuff',
 'know yetunde sent money yet sent text bother sending dont involve anything imposed anything first place apologise',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'k k much cost',
 'home',
 'dear call tmorrow pls accomodate',
 'first answer question',
 'sunshine quiz wkly q win top sony dvd player u know country algarve txt ansr sp tyrone',
 'want get laid tonight want real dogging location sent direct ur mob join uk largest dogging network bt txting gravel nt ec p msg p',
 'haf msn yijue hotmail com',
 'call meet',
 'check room befor activity',
 'rcv msg chat svc free hardcore service text go u get nothing u must age verify yr network try',
 'got c lazy type forgot lect saw pouch like v nice',
 'k text way',
 'sir waiting mail',
 'swt thought nver get tired little thing lovable person coz somtimes little thing occupy biggest part heart gud ni',
 'know pls open back',
 'yes see ya dot',
 'whats staff name taking class u',
 'freemsg replied text randy sexy female live local luv hear u netcollex ltd p per msg reply stop end',
 'ummma call check life begin qatar pls pray hard',
 'k deleted contact',
 'sindu got job birla soft',
 'wine flowing nevering',
 'yup thk cine better co need go plaza mah',
 'ok ur typical reply',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'everywhere dirt floor window even shirt sometimes open mouth come flowing dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time done become one',
 'aaooooright work',
 'leaving house',
 'hello love get interview today happy good boy think missing',
 'customer service annoncement new year delivery waiting please call arrange delivery',
 'winner u specially selected receive cash holiday flight inc speak live operator claim',
 'keep safe need miss already envy everyone see real life',
 'new car house parent new job hand',
 'love excited day spend make happy',
 'pls stop bootydelious f inviting friend reply yes see www sm ac u bootydelious stop send stop frnd',
 'bangbabes ur order way u receive service msg download ur content u goto wap bangb tv ur mobile internet service menu',
 'place ur point e culture module already',
 'urgent trying contact last weekend draw show prize guaranteed call claim code valid hr',
 'hi frnd best way avoid missunderstding wit beloved one',
 'great escape fancy bridge need lager see tomo',
 'yes completely form clark also utter waste',
 'sir need axis bank account bank address',
 'hmmm thk sure got time hop ard ya go free abt muz call u discus liao',
 'time coming later',
 'bloody hell cant believe forgot surname mr ill give u clue spanish begin',
 'well gonna finish bath good fine night',
 'let know got money carlos make call',
 'u still going mall',
 'turn friend staying whole show back til lt gt feel free go ahead smoke lt gt worth',
 'text doesnt reply let know log',
 'hi spoke maneesha v like know satisfied experience reply toll free yes',
 'lifted hope offer money need especially end month approach hurt studying anyways gr weekend',
 'lol u trust',
 'ok gentleman treat dignity respect',
 'guy close',
 'going nothing great bye',
 'hello handsome finding job lazy working towards getting back net mummy boytoy miss',
 'haha awesome minute',
 'please call customer service representative freephone pm guaranteed cash prize',
 'got xmas radio time get',
 'jus reached home go bathe first si using net tell u finish k',
 'unique enough find th august www areyouunique co uk',
 'sorry joined league people dont keep touch mean great deal friend time even great personal cost great week',
 'hi finally completed course',
 'stop however suggest stay someone able give or every stool',
 'hope settled new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u got person story',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate evening hope see tomorrow bit bloody babyjontet txt back u xxx',
 'found enc lt gt',
 'sent lt gt buck',
 'hello darlin ive finished college txt u finish u love kate xxx',
 'account refilled successfully inr lt decimal gt keralacircle prepaid account balance r lt decimal gt transaction id kr lt gt',
 'goodmorning sleeping ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'entered cabin pa said happy b day bos felt special askd lunch lunch invited apartment went',
 'aight yo dat straight dogg',
 'please give u connection today lt decimal gt refund bill',
 'shoot big load get ready',
 'bruv hope great break rewarding semester',
 'home always chat',
 'k k good study well',
 'yup noe leh',
 'sound great home',
 'finally match heading towards draw prediction',
 'tired slept well past night',
 'easy ah sen got selected mean good',
 'take exam march',
 'yeah think use gt atm register sure anyway help let know sure ready',
 'ok prob take ur time',
 'o called ubandu run without installing hard disk use o copy important file system give repair shop',
 'sorry call later',
 'u say leh course nothing happen lar say v romantic jus bit lor thk e nite scenery nice leh',
 'new mobile must go txt nokia collect today www tc biz optout gbp mtmsg',
 'would really appreciate call need someone talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo followed ur star sign e g horo aries',
 'hey company elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happy morning',
 'dear good morning',
 'get gandhipuram walk cross cut road right side lt gt street road turn first right',
 'dear going rubber place',
 'sorry battery died yeah',
 'yes tv always available work place',
 'text meet someone sexy today u find date even flirt u join p reply name age eg sam msg recd thirtyeight penny',
 'printed oh lt gt come upstairs',
 'ill little closer like bus stop street',
 'wil reach',
 'new theory argument win situation loses person dont argue ur friend kick amp say always correct',
 'u secret admirer looking make contact u find r reveal think ur special call',
 'tomarrow final hearing laptop case cant',
 'pleassssssseeeeee tel v avent done sportsx',
 'okay shining meant signing sound better',
 'although told u dat baig face watch really like e watch u gave co fr u thanx everything dat u done today touched',
 'u remember old commercial',
 'late said website dont slipper',
 'asked call ok',
 'kallis wont bat nd inning',
 'didnt work oh ok goodnight fix ready time wake dearly missed good night sleep',
 'congratulation ur awarded cd voucher gift guaranteed free entry wkly draw txt music tncs www ldew com win ppmx age',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovable bcums angry wid u dnt take seriously coz angry childish n true way showing deep affection care n luv kettoda manda nice day da',
 '',
 'ups day also shipping company take wks way usps take week get lag may bribe nipost get stuff',
 'back lemme know ready',
 'necessarily expect done get back though headin',
 'mmm yummy babe nice jolt suzy',
 'lover need',
 'tried contact reply offer video handset anytime network min unlimited text camcorder reply call',
 'parked next mini coming today think',
 'yup',
 'anyway going shopping co si done yet dun disturb u liao',
 'luton ring ur around h',
 'hey really horny want chat see naked text hot text charged pm unsubscribe text stop',
 'dint come u',
 'wana plan trip sometme',
 'sure yet still trying get hold',
 'ur ringtone service changed free credit go club mobile com choose content stop txt club stop p wk club po box mk wt',
 'evo download flash jealous',
 'ringtone club get uk single chart mobile week choose top quality ringtone message free charge',
 'come mu sorting narcotic situation',
 'night ended another day morning come special way may smile like sunny ray leaf worry blue blue bay',
 'hmv bonus special pound genuine hmv voucher answer easy question play send hmv info www percent real com',
 'usf guess might well take car',
 'objection bf coming',
 'thanx',
 'tell rob mack gf theater',
 'awesome see bit',
 'sent type food like',
 'done handed celebration full swing yet',
 'got called tool',
 'wen u miss someone person definitely special u person special miss keep touch gdeve',
 'ok asked money far',
 'okie',
 'yeah think usual guy still passed last night get ahold anybody let know throw',
 'k might come tonight class let early',
 'ok',
 'hi baby im cruisin girl friend r u give call hour home thats alright fone fone love jenny xxx',
 'life mean lot love life love people life world call friend call world ge',
 'dear shall mail tonite busy street shall update tonite thing looking ok varunnathu edukkukayee raksha ollu good one real sense',
 'hey told name gautham ah',
 'haf u found feel stupid da v cam working',
 'oops got bit',
 'much buzy',
 'accidentally deleted message resend please',
 'mobile customer may claim free camera phone upgrade pay go sim card loyalty call offer end thfeb c apply',
 'unless situation go gurl would appropriate',
 'hurt tease make cry end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'cant pick phone right pls send message',
 'need coffee run tomo believe time week already',
 'awesome remember last time got somebody high first time diesel v',
 'shit really shocking scary cant imagine second def night u think somewhere could crash night save taxi',
 'oh way food fridge want go meal tonight',
 'womdarfull actor',
 'sm ac blind date u rodds aberdeen united kingdom check http img sm ac w icmb cktz r blind date send hide',
 'yup remb think book',
 'jos ask u wana meet',
 'lol yes friendship hanging thread cause u buy stuff',
 'themob check newest selection content game tone gossip babe sport keep mobile fit funky text wap',
 'garage key bookshelf',
 'today accept day u accept brother sister lover dear best clos lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rply mean enemy',
 'think ur smart win week weekly quiz text play c winnersclub po box uz gbp week',
 'say give call friend got money definitely buying end week',
 'hi way u day normal way real ur unique hope know u rest mylife hope u find wot lost',
 'made day great day',
 'k k advance happy pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao',
 'really dude friend afraid',
 'december mobile mths entitled update latest colour camera mobile free call mobile update co free',
 'coffee cake guess',
 'merry christmas babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bit l co bus hav gon past co full im still waitin pete x',
 'would great guild could meet bristol road somewhere get touch weekend plan take flight good week',
 'problem',
 'call message missed call',
 'hi da today class',
 'say good sign well know track record reading woman',
 'cool text parked',
 'reading text sent meant joke read light',
 'k k apo k good movie',
 'maybe could get book tomo return immediately something',
 'call germany penny per minute call fixed line via access number prepayment direct access',
 'chance might evaporated soon violated privacy stealing phone number employer paperwork cool please contact report supervisor',
 'valentine day special win quiz take partner trip lifetime send go p msg rcvd custcare',
 'ta daaaaa home babe still',
 'cool come havent wined dined',
 'sleeping surfing',
 'sorry call later',
 'u calling right call hand phone',
 'ok great thanx lot',
 'take post come must text happy reading one wiv hello caroline end favourite bless',
 'u hiding stranger',
 'interested like',
 'sister cleared two round birla soft yesterday',
 'gudnite tc practice going',
 'dis yijue jus saw ur mail case huiming havent sent u num dis num',
 'one small prestige problem',
 'fancy shag interested sextextuk com txt xxuk suzy txts cost per msg tncs website x',
 'checking really miss seeing jeremiah great month',
 'nah help never iphone',
 'car hour half going apeshit',
 'today sorry day ever angry ever misbehaved hurt plz plz slap urself bcoz ur fault basically good',
 'yo guy ever figure much need alcohol jay trying figure much safely spend weed',
 'lt gt ish minute minute ago wtf',
 'thank calling forgot say happy onam sirji fine remembered met insurance person meet qatar insha allah rakhesh ex tata aig joined tissco tayseer',
 'congratulation ur awarded cd voucher gift guaranteed free entry wkly draw txt music tncs www ldew com win ppmx age',
 'ur cash balance currently pound maximize ur cash send cash p msg cc hg suite land row w j hl',

In [30]:
## Create TF-IDF and NGrams
from sklearn.feature_extraction.text import TfidfVectorizer

In [31]:
tfidf=TfidfVectorizer(max_features=100)
X=tfidf.fit_transform(corpus).toarray()

In [33]:
import numpy as np
np.set_printoptions(
    edgeitems=30,
    linewidth=100000,
    formatter=dict(float=lambda x: "%.3g" % x)
)

In [34]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.434, 0, 0, 0.461, 0.544, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.456, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.473, 0, 0, 0, 0, 0, 0, 0, 0.492, 0, 0, 0, 0, 0, 0, 0, 0.571, 0, 0, 0, 0, 0, 0],
       [0.465, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.486, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.574, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0.389, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.412, ..., 0.365, 0, 0, 0.384, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.403, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0.283, 0, 0, 0.85, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0.189, 0, 0, 0, 0.275, 0, 0, 0, 0, 0, 0, 0, 0.481, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.58, 0, 0, 0, 0, 0, 0.56, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0.39, 0, 0, 0, 0, 0, 0.6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0.323, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.334, 0, 0, 0, 0, 0, 0, 0, 0.387, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.422, 0, 0, 0, 0, 0, 0, 0, 0, 0.357, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.385, 0, 0, 0, 0, 0, 0.411, 0, 0, 0, 0, 0.429, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0.57, 0, 0, 0, 0, 0, 0.517, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.624, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.529, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.717],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.388, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.744, 0, 0.322, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0.429, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.329, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.325, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.695, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0.556, 0, 0, 0, 0.481, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.766, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.602, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.675, 0, 0, 0, 0, ..., 0, 0, 0, 0.738, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0.577, 0, 0, 0, 0.499, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.466, 0, 0, 0, 0.449, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0.55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.622, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.359],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.507, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.643, 0.574, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.597, 0, 0, 0, 0, 0, 0.802, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0.558, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.444, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.514, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.415, 0, 0, 0, 0, 0, 0, 0, 0, 0.695, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.44, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.711],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.597, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.382, 0],
       [0, 0, 0, 0, 0, 0, 0.445, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0.624, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.707, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0.498, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.749, 0, 0, 0, 0, 0, 0, 0, 0.663, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0.553, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.628, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0.287, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.364, 0, 0.321, 0, 0, 0, 0, 0, 0.431, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.378, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0.369, 0, 0, 0.555, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.469, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.706, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.548, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.631, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
X.shape

(5572, 100)

## Word2Vec Practical Implementation

Please refer to notes for the mathematical intuition. We will be using `gensim` for this practical example.

In [1]:
!pip install gensim

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: gensim in c:\programdata\anaconda3\lib\site-packages (4.3.3)
Requirement already satisfied: numpy<2.0,>=1.18.5 in c:\programdata\anaconda3\lib\site-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in c:\programdata\anaconda3\lib\site-packages (from gensim) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in c:\programdata\anaconda3\lib\site-packages (from gensim) (5.2.1)

In [2]:
import gensim

In [3]:
from gensim.models import Word2Vec, KeyedVectors

For the `pretrained implementation`, we will use **`word2vec-google-news-300`**. It can be dowloaded from `gensim`

In [11]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')
vec_king=wv['king']

## This code checks the folder 'word2vec-google-news-300' (within gensim folder)
## If the compressed data is not present the __init__.py will fire a download request
## Sometimes the download may be unsuccessful due to some reasons, like network
## You can download it directly via your browser through this link
## https://github.com/piskvorky/gensim-data/releases/tag/word2vec-google-news-300?utm_source=chatgpt.com
## ensure you download the word2vec with the init file
## once its downloaded successfully move it to gensim folder in a word2vec-google-news-300 folder
## If it fails to download in google chrome, use Edge or Firefox

In [12]:
## THis is vector for the word 'King' with 300 dimensions
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  2.01416016e-02, -1.63085938e-01,  1.35803223e-03,
       -1.44531250e-01, -5.68847656e-02,  4.29687500e-02, -2.46582031e-02,
        1.85546875e-01,  4.47265625e-01,  9.58251953e-03,  1.31835938e-01,
        9.86328125e-02, -1.85546875e-01, -1.00097656e-01, -1.33789062e-01,
       -1.25000000e-01,  2.83203125e-01,  1.23046875e-01,  5.32226562e-02,
       -1.77734375e-01,  8.59375000e-02, -2.18505859e-02,  2.05078125e-02,
       -1.39648438e-01,  2.51464844e-02,  1.38671875e-01, -1.05468750e-01,
        1.38671875e-01,  8.88671875e-02, -7.51953125e-02, -2.13623047e-02,
        1.72851562e-01,  4.63867188e-02, -2.65625000e-01,  8.91113281e-03,
        1.49414062e-01,  3.78417969e-02,  2.38281250e-01, -1.24511719e-01,
       -2.17773438e-01, -1.81640625e-01,  2.97851562e-02,  5.71289062e-02,
       -2.89306641e-02,  1.24511719e-02,  9.66796875e-02, -2.31445312e-01,
        5.81054688e-02,  6.68945312e-02,  7.08007812e-02, -3.08593750e-01,
       -2.14843750e-01,  1.45507812e-01, -4.27734375e-01, -9.39941406e-03,
        1.54296875e-01, -7.66601562e-02,  2.89062500e-01,  2.77343750e-01,
       -4.86373901e-04, -1.36718750e-01,  3.24218750e-01, -2.46093750e-01,
       -3.03649902e-03, -2.11914062e-01,  1.25000000e-01,  2.69531250e-01,
        2.04101562e-01,  8.25195312e-02, -2.01171875e-01, -1.60156250e-01,
       -3.78417969e-02, -1.20117188e-01,  1.15234375e-01, -4.10156250e-02,
       -3.95507812e-02, -8.98437500e-02,  6.34765625e-03,  2.03125000e-01,
        1.86523438e-01,  2.73437500e-01,  6.29882812e-02,  1.41601562e-01,
       -9.81445312e-02,  1.38671875e-01,  1.82617188e-01,  1.73828125e-01,
        1.73828125e-01, -2.37304688e-01,  1.78710938e-01,  6.34765625e-02,
        2.36328125e-01, -2.08984375e-01,  8.74023438e-02, -1.66015625e-01,
       -7.91015625e-02,  2.43164062e-01, -8.88671875e-02,  1.26953125e-01,
       -2.16796875e-01, -1.73828125e-01, -3.59375000e-01, -8.25195312e-02,
       -6.49414062e-02,  5.07812500e-02,  1.35742188e-01, -7.47070312e-02,
       -1.64062500e-01,  1.15356445e-02,  4.45312500e-01, -2.15820312e-01,
       -1.11328125e-01, -1.92382812e-01,  1.70898438e-01, -1.25000000e-01,
        2.65502930e-03,  1.92382812e-01, -1.74804688e-01,  1.39648438e-01,
        2.92968750e-01,  1.13281250e-01,  5.95703125e-02, -6.39648438e-02,
        9.96093750e-02, -2.72216797e-02,  1.96533203e-02,  4.27246094e-02,
       -2.46093750e-01,  6.39648438e-02, -2.25585938e-01, -1.68945312e-01,
        2.89916992e-03,  8.20312500e-02,  3.41796875e-01,  4.32128906e-02,
        1.32812500e-01,  1.42578125e-01,  7.61718750e-02,  5.98144531e-02,
       -1.19140625e-01,  2.74658203e-03, -6.29882812e-02, -2.72216797e-02,
       -4.82177734e-03, -8.20312500e-02, -2.49023438e-02, -4.00390625e-01,
       -1.06933594e-01,  4.24804688e-02,  7.76367188e-02, -1.16699219e-01,
        7.37304688e-02, -9.22851562e-02,  1.07910156e-01,  1.58203125e-01,
        4.24804688e-02,  1.26953125e-01,  3.61328125e-02,  2.67578125e-01,
       -1.01074219e-01, -3.02734375e-01, -5.76171875e-02,  5.05371094e-02,
        5.26428223e-04, -2.07031250e-01, -1.38671875e-01, -8.97216797e-03,
       -2.78320312e-02, -1.41601562e-01,  2.07031250e-01, -1.58203125e-01,
        1.27929688e-01,  1.49414062e-01, -2.24609375e-02, -8.44726562e-02,
        1.22558594e-01,  2.15820312e-01, -2.13867188e-01, -3.12500000e-01,
       -3.73046875e-01,  4.08935547e-03,  1.07421875e-01,  1.06933594e-01,
        7.32421875e-02,  8.97216797e-03, -3.88183594e-02, -1.29882812e-01,
        1.49414062e-01, -2.14843750e-01, -1.83868408e-03,  9.91210938e-02,
        1.57226562e-01, -1.14257812e-01, -2.05078125e-01,  9.91210938e-02,
        3.69140625e-01, -1.97265625e-01,  3.54003906e-02,  1.09375000e-01,
        1.31835938e-01,  1.66992188e-01,  2.35351562e-01,  1.04980469e-01,
       -4.96093750e-01, -1.64062500e-01, -1.56250000e-01, -5.22460938e-02,
        1.03027344e-01,  2.43164062e-01, -1.88476562e-01,  5.07812500e-02,
       -9.37500000e-02, -6.68945312e-02,  2.27050781e-02,  7.61718750e-02,
        2.89062500e-01,  3.10546875e-01, -5.37109375e-02,  2.28515625e-01,
        2.51464844e-02,  6.78710938e-02, -1.21093750e-01, -2.15820312e-01,
       -2.73437500e-01, -3.07617188e-02, -3.37890625e-01,  1.53320312e-01,
        2.33398438e-01, -2.08007812e-01,  3.73046875e-01,  8.20312500e-02,
        2.51953125e-01, -7.61718750e-02, -4.66308594e-02, -2.23388672e-02,
        2.99072266e-02, -5.93261719e-02, -4.66918945e-03, -2.44140625e-01,
       -2.09960938e-01, -2.87109375e-01, -4.54101562e-02, -1.77734375e-01,
       -2.79296875e-01, -8.59375000e-02,  9.13085938e-02,  2.51953125e-01],
      dtype=float32)

In [6]:
print("BASE_DIR:", api.BASE_DIR)

BASE_DIR: C:\Users\pc/gensim-data

In [7]:
import tempfile
print(tempfile.gettempdir())

C:\Users\pc\AppData\Local\Temp

In [9]:
import gensim.downloader as api
print(api.BASE_DIR)

C:\Users\pc/gensim-data

In [13]:
vec_king.shape

(300,)

In [14]:
wv['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -5.59082031e-02,  7.61718750e-02, -4.14062500e-01,
       -3.65234375e-01, -3.35937500e-01, -1.54296875e-01, -2.39257812e-01,
       -3.73046875e-01,  2.27355957e-03, -3.51562500e-01,  8.64257812e-02,
        1.26953125e-01,  2.21679688e-01, -9.86328125e-02,  1.08886719e-01,
        3.65234375e-01, -5.66406250e-02,  5.66406250e-02, -1.09375000e-01,
       -1.66992188e-01, -4.54101562e-02, -2.00195312e-01, -1.22558594e-01,
        1.31835938e-01, -1.31835938e-01,  1.03027344e-01, -3.41796875e-01,
       -1.57226562e-01,  2.04101562e-01,  4.39453125e-02,  2.44140625e-01,
       -3.19824219e-02,  3.20312500e-01, -4.41894531e-02,  1.08398438e-01,
       -4.98046875e-02, -9.52148438e-03,  2.46093750e-01, -5.59082031e-02,
        4.07714844e-02, -1.78222656e-02, -2.95410156e-02,  1.65039062e-01,
        5.03906250e-01, -2.81250000e-01,  9.81445312e-02,  1.80664062e-02,
       -1.83593750e-01,  2.53906250e-01,  2.25585938e-01,  1.63574219e-02,
        1.81640625e-01,  1.38671875e-01,  3.33984375e-01,  1.39648438e-01,
        1.45874023e-02, -2.89306641e-02, -8.39843750e-02,  1.50390625e-01,
        1.67968750e-01,  2.28515625e-01,  3.59375000e-01,  1.22558594e-01,
       -3.28125000e-01, -1.56250000e-01,  2.77343750e-01,  1.77001953e-02,
       -1.46484375e-01, -4.51660156e-03, -4.46777344e-02,  1.75781250e-01,
       -3.75000000e-01,  1.16699219e-01, -1.39648438e-01,  2.55859375e-01,
       -1.96289062e-01, -2.57568359e-02, -5.41992188e-02, -2.51464844e-02,
       -1.93359375e-01, -3.17382812e-02, -8.74023438e-02, -1.32812500e-01,
       -2.12402344e-02,  4.33593750e-01, -5.20019531e-02,  3.46679688e-02,
        8.00781250e-02,  3.41796875e-02,  1.99218750e-01, -2.39257812e-02,
       -2.37304688e-01,  1.93359375e-01,  7.32421875e-02, -2.87109375e-01,
        1.25000000e-01,  8.44726562e-02,  1.30859375e-01, -2.19726562e-01,
       -1.61132812e-01, -2.63671875e-01, -5.46875000e-01, -2.96875000e-01,
        3.44238281e-02, -2.87109375e-01, -1.93359375e-01, -1.61132812e-01,
       -3.84765625e-01, -2.14843750e-01, -6.22558594e-03, -1.27929688e-01,
       -1.00097656e-01, -6.21093750e-01,  3.78906250e-01, -4.58984375e-01,
        1.44531250e-01, -9.13085938e-02, -3.08593750e-01,  2.23632812e-01,
        7.86132812e-02, -2.16796875e-01,  8.78906250e-02, -1.66992188e-01,
        1.14746094e-02, -2.53906250e-01, -6.25000000e-02,  6.04248047e-03,
        1.56250000e-01,  4.37500000e-01, -2.23632812e-01, -2.32421875e-01,
        2.75390625e-01,  2.39257812e-01,  4.49218750e-02, -7.51953125e-02,
        5.74218750e-01, -2.61230469e-02, -1.21582031e-01,  2.44140625e-01,
       -3.37890625e-01,  8.59375000e-02, -7.71484375e-02,  4.85839844e-02,
        1.43554688e-01,  4.25781250e-01, -4.29687500e-02, -1.08398438e-01,
        1.19628906e-01, -1.91406250e-01, -2.12890625e-01, -2.87109375e-01,
       -1.14746094e-01, -2.04101562e-01, -2.06298828e-02, -2.53906250e-01,
        8.25195312e-02, -3.97949219e-02, -1.57226562e-01,  1.34765625e-01,
        2.08007812e-01, -1.78710938e-01, -2.00195312e-02, -8.34960938e-02,
       -1.20605469e-01,  4.29687500e-02, -1.94335938e-01, -1.32812500e-01,
       -2.17285156e-02, -2.35351562e-01, -3.63281250e-01,  1.51367188e-01,
        9.32617188e-02,  1.63085938e-01,  1.02050781e-01, -4.27734375e-01,
        2.83203125e-01,  2.74658203e-04, -3.20312500e-01,  1.68457031e-02,
        4.06250000e-01, -5.24902344e-02,  7.91015625e-02, -1.41601562e-01,
        5.27343750e-01, -1.26953125e-01,  4.74609375e-01, -6.64062500e-02,
        3.41796875e-01, -1.78710938e-01,  3.69140625e-01, -2.05078125e-01,
        5.82885742e-03, -1.84570312e-01, -8.88671875e-02, -1.81640625e-01,
       -4.80957031e-02,  4.39453125e-01,  2.12890625e-01, -3.07617188e-02,
        9.32617188e-02,  2.40234375e-01,  2.39257812e-01,  2.51953125e-01,
       -1.98974609e-02,  1.24511719e-01, -4.73632812e-02, -2.13623047e-02,
        3.12500000e-02,  3.05175781e-02,  2.79296875e-01,  9.08203125e-02,
       -2.02148438e-01, -2.19726562e-02, -2.63671875e-01,  8.78906250e-02,
       -1.07421875e-01, -2.49023438e-01, -1.22070312e-02,  1.73828125e-01,
       -9.91210938e-02,  7.27539062e-02,  2.59765625e-01, -4.60937500e-01,
        3.59375000e-01, -2.25585938e-01,  1.87988281e-02, -2.19726562e-01,
       -2.08984375e-01, -1.51367188e-01,  8.64257812e-02,  1.11694336e-02,
        6.93359375e-02, -2.99072266e-02,  1.43554688e-01,  1.89453125e-01,
       -1.32812500e-01,  4.72656250e-01, -1.40625000e-01, -2.52685547e-02,
        1.91406250e-01, -2.63671875e-01, -1.39648438e-01,  1.09375000e-01,
        1.97753906e-02,  2.49023438e-01, -1.42578125e-01,  4.15039062e-02],
      dtype=float32)

In [15]:
wv['Izu']

array([ 0.18847656,  0.24414062,  0.07519531, -0.18359375,  0.0090332 ,
        0.08056641, -0.15625   , -0.08789062, -0.25976562,  0.22949219,
        0.10009766,  0.15722656, -0.05688477, -0.08544922, -0.06787109,
       -0.05249023, -0.35546875,  0.20117188, -0.14160156, -0.03979492,
       -0.11279297, -0.03173828, -0.10058594,  0.109375  ,  0.02746582,
       -0.12109375, -0.12353516, -0.14648438,  0.13769531, -0.04980469,
        0.00242615, -0.10449219, -0.12158203,  0.01623535, -0.30273438,
       -0.32617188,  0.25195312, -0.09570312, -0.07275391, -0.16308594,
       -0.22949219,  0.05175781, -0.05273438,  0.24804688,  0.15234375,
        0.08447266,  0.18652344,  0.09423828, -0.03393555, -0.05615234,
       -0.12207031, -0.28710938,  0.24121094, -0.02001953,  0.00927734,
        0.29492188,  0.02966309, -0.02868652,  0.10888672, -0.5390625 ,
       -0.07714844,  0.36328125, -0.09619141, -0.23730469,  0.09570312,
       -0.31054688, -0.01519775,  0.07763672,  0.19824219, -0.06982422,
       -0.04394531, -0.16796875,  0.03222656, -0.07519531, -0.10253906,
        0.09228516, -0.20507812, -0.09228516,  0.06640625,  0.00640869,
        0.34570312, -0.3515625 ,  0.0546875 , -0.14453125,  0.00970459,
       -0.17871094, -0.06689453, -0.22460938,  0.08837891, -0.06494141,
        0.06689453, -0.06298828, -0.20703125,  0.29882812, -0.28515625,
        0.02783203,  0.20898438, -0.03063965, -0.01855469,  0.13183594,
       -0.01324463,  0.05639648,  0.15039062,  0.23242188,  0.39648438,
        0.31445312, -0.10791016, -0.06787109, -0.23730469,  0.01831055,
       -0.41210938,  0.10107422,  0.33203125,  0.14160156, -0.15527344,
       -0.03833008, -0.11376953, -0.3828125 , -0.17480469, -0.12792969,
       -0.24511719,  0.11474609, -0.16796875,  0.14355469,  0.06445312,
        0.14941406, -0.12597656, -0.19433594,  0.06298828,  0.30078125,
       -0.38867188,  0.01013184,  0.05273438,  0.1015625 , -0.11376953,
        0.04077148, -0.265625  ,  0.1015625 , -0.15820312,  0.19335938,
        0.02380371,  0.0859375 ,  0.19042969, -0.20019531,  0.18261719,
        0.24121094, -0.25585938,  0.15234375, -0.16699219,  0.11865234,
        0.11328125,  0.07910156, -0.12695312,  0.24707031,  0.01208496,
       -0.19628906,  0.05053711,  0.10644531,  0.08984375,  0.11572266,
        0.11425781,  0.11035156,  0.07763672,  0.33203125,  0.00878906,
        0.27734375,  0.16015625, -0.20898438, -0.12695312,  0.11865234,
        0.09521484,  0.07421875, -0.02160645,  0.14648438,  0.00653076,
       -0.15722656,  0.40039062,  0.01855469,  0.27539062, -0.1328125 ,
        0.04492188, -0.23144531,  0.17285156, -0.23339844, -0.21972656,
       -0.11328125, -0.05737305, -0.24609375, -0.3359375 , -0.13769531,
       -0.11132812, -0.27929688,  0.18359375,  0.15917969, -0.05419922,
       -0.10058594,  0.19921875,  0.07714844,  0.00830078,  0.01733398,
        0.13769531, -0.10205078, -0.0612793 , -0.04003906, -0.13964844,
       -0.07324219,  0.38671875, -0.16503906, -0.1484375 , -0.16601562,
       -0.31054688, -0.0559082 ,  0.04516602,  0.0625    , -0.28320312,
       -0.08496094,  0.34960938,  0.17578125,  0.20996094,  0.02978516,
        0.29296875, -0.12060547, -0.14550781, -0.08837891,  0.03857422,
        0.19628906, -0.03613281,  0.28515625,  0.10986328, -0.10449219,
        0.03955078,  0.01135254, -0.05664062,  0.14355469,  0.19042969,
        0.29882812, -0.09130859,  0.20800781, -0.16113281,  0.14648438,
       -0.14257812, -0.55078125, -0.10791016,  0.2109375 ,  0.04248047,
       -0.22460938, -0.12792969,  0.03540039,  0.05615234, -0.25      ,
        0.02490234,  0.22460938,  0.2734375 , -0.01208496,  0.0189209 ,
       -0.375     , -0.20019531, -0.25390625, -0.06079102,  0.03662109,
       -0.00198364,  0.00099945,  0.04443359, -0.29101562, -0.00372314,
        0.22949219, -0.20996094,  0.00469971, -0.00680542, -0.23339844,
       -0.14355469,  0.06689453, -0.13964844,  0.37890625,  0.3359375 ,
        0.234375  , -0.36523438,  0.21972656, -0.05957031,  0.05273438,
        0.06982422, -0.10791016,  0.04467773, -0.28515625,  0.04174805,
       -0.13964844, -0.04711914,  0.12304688, -0.40234375,  0.08056641,
       -0.24511719,  0.12451172,  0.17773438,  0.00616455,  0.02209473,
       -0.18359375, -0.19238281, -0.18652344,  0.15429688,  0.22363281],
      dtype=float32)

In [16]:
## We can check for most similar words to a word
wv.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819784164429),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.7541396617889404),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.698798656463623)]

The numbers sow the level of similarities. The closer it is to 1 the closer the similarities.

`It ranges from -1 to 1:`

* `1.0 → identical direction (very similar)`
* ` 0 → unrelated`
* ` -1 → opposite direction`

In [17]:
wv.most_similar('happy')

[('glad', 0.7408890724182129),
 ('pleased', 0.6632170677185059),
 ('ecstatic', 0.6626912355422974),
 ('overjoyed', 0.6599286794662476),
 ('thrilled', 0.6514049172401428),
 ('satisfied', 0.6437949538230896),
 ('proud', 0.636042058467865),
 ('delighted', 0.6272379159927368),
 ('disappointed', 0.6269949674606323),
 ('excited', 0.6247665882110596)]

In [18]:
## You can check the similarity between two words
wv.similarity("hockey","sports")

0.5354152

In [19]:
wv.similarity("bad","good") ## You can google why its not negative

0.7190051

In [20]:
wv.similarity('banana','democracy')

0.14052573

In [22]:
wv.similarity('airplane', 'happiness')

0.101052366

I have been tryinf to find words that will give a negative cosine similarity. We will use code to fish it out.

In [23]:
import numpy as np

word = "good"

# Compute similarities with every word in the vocabulary
sims = wv.cosine_similarities(wv[word], wv.vectors)

# Get the index of the smallest similarity
idx = np.argmin(sims)

print(wv.index_to_key[idx])
print(sims[idx])

J.Gordon_###-###
-0.3913142

In [24]:
## lets do some operation
vec=wv['king']-wv['man']+wv['woman']
vec

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  2.42309570e-01, -3.21777344e-01,  1.45416260e-02,
       -1.59179688e-01, -8.37402344e-02,  1.65039062e-01,  1.58691406e-03,
        3.09570312e-01,  3.16406250e-01,  7.38525391e-03,  2.41210938e-01,
        4.90722656e-02, -9.86328125e-02,  2.90527344e-02,  1.49414062e-01,
       -4.83398438e-02,  2.35595703e-01,  2.21191406e-01,  1.25488281e-01,
       -1.38671875e-01,  1.54296875e-01,  7.18994141e-02,  1.29882812e-01,
       -1.05712891e-01,  6.00585938e-02,  3.14697266e-01,  1.09619141e-01,
        8.49609375e-02,  7.71484375e-02, -2.17285156e-02,  6.11572266e-02,
       -1.89941406e-01,  2.07519531e-01, -1.63085938e-01,  1.13525391e-01,
        2.01171875e-01,  6.06689453e-02,  1.27929688e-01, -3.11279297e-01,
       -2.80151367e-01, -1.55883789e-01,  4.15039062e-02,  9.87854004e-02,
        1.69555664e-01, -3.49121094e-02,  2.08496094e-01, -9.89990234e-02,
        4.39453125e-03, -7.27539062e-02, -4.24804688e-02, -4.09179688e-01,
       -2.76367188e-01,  1.64062500e-01, -5.57617188e-01, -2.02199936e-01,
        2.12158203e-01, -9.81445312e-02,  2.30773926e-01,  2.75878906e-01,
        1.68092728e-01, -4.50439453e-02,  1.71615601e-01, -3.77075195e-01,
       -3.52478027e-03, -3.01513672e-01,  1.74224854e-01,  3.30078125e-01,
        2.00683594e-01,  1.17736816e-01, -1.37695312e-01, -1.07421875e-01,
        8.61816406e-02,  1.06445312e-01,  1.44531250e-01,  3.05175781e-03,
        1.80664062e-02,  3.73535156e-02,  7.32421875e-03,  1.32812500e-01,
        9.61914062e-02,  3.35998535e-01,  1.81152344e-01,  2.40905762e-01,
       -8.49609375e-02, -1.10107422e-01,  2.11914062e-01,  5.85937500e-03,
        1.62109375e-01, -4.15527344e-01,  1.39160156e-01,  1.01562500e-01,
        1.44531250e-01, -1.09375000e-01,  4.88281250e-02,  6.15234375e-02,
       -1.69921875e-01,  3.28369141e-02,  5.56640625e-02,  1.47460938e-01,
       -2.24609375e-02, -2.73925781e-01, -2.81982422e-01, -1.39160156e-01,
       -1.81884766e-01,  9.33532715e-02,  1.21093750e-01, -5.37109375e-03,
       -1.87500000e-01,  3.05175781e-04,  5.52734375e-01, -9.71679688e-02,
       -1.81640625e-01, -1.51855469e-01,  7.76367188e-02, -2.38281250e-01,
       -2.63977051e-02,  2.25555420e-01, -3.02734375e-01,  1.34765625e-01,
        3.23242188e-01,  1.25976562e-01,  3.51562500e-02, -2.04345703e-01,
        2.96142578e-01,  1.03149414e-01, -4.76074219e-03,  1.69189453e-01,
       -3.50585938e-01,  2.46887207e-02, -3.90502930e-01, -2.70507812e-01,
        1.85241699e-02,  1.04492188e-01,  2.84179688e-01,  1.35009766e-01,
       -5.95703125e-02,  1.88232422e-01,  8.88214111e-02,  3.24707031e-02,
       -8.98437500e-02,  5.45043945e-02,  5.65185547e-02,  1.56860352e-01,
       -9.70458984e-03, -7.08007812e-02,  5.71289062e-02, -3.08837891e-01,
       -1.91894531e-01,  4.83398438e-02,  5.22460938e-02, -1.59667969e-01,
       -4.49218750e-02, -7.37304688e-02,  5.51757812e-02,  2.12402344e-01,
        2.05322266e-01, -2.73437500e-02,  7.86132812e-02,  3.19091797e-01,
       -1.56982422e-01, -3.92822266e-01,  4.00390625e-02,  9.93652344e-02,
       -1.97372437e-02, -8.25195312e-02,  2.53906250e-02,  3.10668945e-02,
       -3.63769531e-02,  1.48925781e-02,  2.20703125e-01, -5.98144531e-02,
        6.15234375e-02, -7.14111328e-02, -4.00390625e-02, -1.03515625e-01,
        9.22851562e-02,  2.71789551e-01, -2.30224609e-01, -2.62695312e-01,
       -5.61523438e-01,  1.38549805e-02,  1.09863281e-01,  7.22656250e-02,
        4.58984375e-02, -3.31802368e-02, -8.03833008e-02, -6.10351562e-03,
        2.09960938e-01, -3.86840820e-01,  1.44645691e-01,  8.05664062e-02,
        2.96264648e-01, -1.17187500e-02, -2.34680176e-01,  1.32019043e-01,
        2.53906250e-01, -2.46826172e-01,  1.03759766e-01,  1.14013672e-01,
        1.71875000e-01, -5.61523438e-03,  2.05078125e-01,  6.34765625e-02,
       -4.51293945e-01, -2.26562500e-01, -1.03027344e-01, -1.31469727e-01,
        3.75976562e-02,  2.70996094e-01, -2.39257812e-01,  3.80859375e-02,
       -3.90625000e-02, -9.42382812e-02,  8.30078125e-03,  7.03125000e-02,
        2.75390625e-01,  3.31542969e-01, -1.07421875e-02,  3.72192383e-01,
       -1.24511719e-01,  1.94335938e-01, -1.35620117e-01, -3.09570312e-01,
       -2.36328125e-01, -1.26953125e-02, -2.76855469e-01,  1.57714844e-01,
        3.07617188e-01, -2.32910156e-01,  3.25439453e-01,  1.36718750e-02,
        1.99462891e-01, -2.61840820e-02, -8.08105469e-02, -7.50732422e-02,
       -4.11109924e-02,  1.95556641e-01, -5.64270020e-02, -2.79296875e-01,
       -2.75390625e-01, -4.04296875e-01, -1.75781250e-02, -5.85937500e-03,
       -7.71484375e-02,  1.33789062e-01,  2.36816406e-01,  2.01538086e-01],
      dtype=float32)

In [25]:
wv.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300518155097961),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676948547363),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613664388656616),
 ('sultan', 0.5376776456832886),
 ('Queen_Consort', 0.5344247221946716),
 ('queens', 0.5289887189865112)]

This is `Pretrained Word2Vec` because we are using ready made vectors trained by google experts. Later on we will learn how to build our own vectors from scratch. 

For now we will go to doing a full machine learning analysis with what we have learned so far

## SPAM HAM PROJECT

Here we will develop a model to predict if a message is a spam or not. We will apply `BOW`, `TF-IDF`, `Word2Vec` and `AvgWord2Vec` (for Vectorizing) and `Machine Learning Algorithms` for training

In [1]:
import pandas as pd
messages = pd.read_csv('SMSSpamCollection.txt',sep='\t',names=['label','message'])

In [2]:
messages

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [4]:
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
sbs=SnowballStemmer('english')

In [5]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[sbs.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [6]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkts st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather promis wont take help grant fulfil promis wonder bless time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt messag click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k watch',
 'eh u rememb spell name yes v naughti make v wet',
 'fine way u feel way gota b',
 'england v macedonia dont miss goal team news txt ur nation team eg england tri wale scotland txt poboxox w wq',
 'serious spell name',
 'go tri month ha ha joke',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch alreadi',
 'ffffffffff alright way meet sooner',
 'forc eat slice realli hungri tho suck mark get worri know sick turn pizza lol',
 'lol alway convinc',
 'catch bus fri egg make tea eat mom left dinner feel love',
 'back amp pack car let know room',
 'ahhh work vagu rememb feel like lol',
 'wait still clear sure sarcast x want live us',
 'yeah got v apologet n fallen actin like spoilt child got caught till go bad cheer',
 'k tell anyth',
 'fear faint housework quick cuppa',
 'thank subscript rington uk mobil charg month pleas confirm repli yes repli charg',
 'yup ok go home look time msg xuhui go learn nd may lesson',
 'oop let know roommat done',
 'see letter b car',
 'anyth lor u decid',
 'hello saturday go text see decid anyth tomo tri invit anyth',
 'pls go ahead watt want sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummi',
 'rodger burn msg tri call repli sms free nokia mobil free camcord pleas call deliveri tomorrow',
 'see',
 'great hope like man well endow lt gt inch',
 'call messag miss call',
 'get hep b immunis nigeria',
 'fair enough anyth go',
 'yeah hope tyler could mayb ask around bit',
 'u know stubborn even want go hospit kept tell mark weak sucker hospit weak sucker',
 'think first time saw class',
 'gram usual run like lt gt half eighth smarter though get almost whole second gram lt gt',
 'k fyi x ride earli tomorrow morn crash place tonight',
 'wow never realiz embarass accomod thought like sinc best could alway seem happi cave sorri give sorri offer sorri room embarass',
 'sms ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end repli end sptv',
 'know mallika sherawat yesterday find lt url gt',
 'congrat year special cinema pass call c suprman v matrix starwar etc free bx ip pm dont miss',
 'sorri call later meet',
 'tell reach',
 'yes gauti sehwag odi seri',
 'gonna pick burger way home even move pain kill',
 'ha ha ha good joke girl situat seeker',
 'part check iq',
 'sorri roommat took forev ok come',
 'ok lar doubl check wif da hair dresser alreadi said wun cut v short said cut look nice',
 'valu custom pleas advis follow recent review mob award bonus prize call',
 'today song dedic day song u dedic send ur valuabl frnds first rpli',
 'urgent ur award complimentari trip eurodisinc trav aco entri claim txt dis morefrmmob shracomorsglsuplt ls aj',
 'hear new divorc barbi come ken stuff',
 'plane give month end',
 'wah lucki man save money hee',
 'finish class',
 'hi babe im home wanna someth xx',
 'k k perform',
 'u call',
 'wait machan call free',
 'that cool gentleman treat digniti respect',
 'like peopl much shi pa',
 'oper lt gt',
 'still look job much ta earn',
 'sorri call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later network urgnt sms',
 'real u get yo need ticket one jacket done alreadi use multi',
 'yes start send request make pain came back back bed doubl coin factori gotta cash nitro',
 'realli still tonight babe',
 'ela kano il download come wen ur free',
 'yeah stand close tho catch someth',
 'sorri pain ok meet anoth night spent late afternoon casualti mean done stuff moro includ time sheet sorri',
 'smile pleasur smile pain smile troubl pour like rain smile sum hurt u smile becoz someon still love see u smile',
 'pleas call custom servic repres pm guarante cash prize',
 'havent plan buy later check alreadi lido got show e afternoon u finish work alreadi',
 'free rington wait collect simpli text password mix verifi get usher britney fml po box mk h ppw',
 'watch telugu movi wat abt u',
 'see finish load loan pay',
 'hi wk ok hol yes bit run forgot hairdress appoint four need get home n shower beforehand caus prob u',
 'see cup coffe anim',
 'pleas text anymor noth els say',
 'okay name ur price long legal wen pick u ave x am xx',
 'still look car buy gone drive test yet',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'wow right mean guess gave boston men chang search locat nyc someth chang cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thank lot wish birthday thank make birthday truli memor',
 'aight hit get cash',
 'would ip address test consid comput minecraft server',
 'know grumpi old peopl mom like better lie alway one play joke',
 'dont worri guess busi',
 'plural noun research',
 'go dinner msg',
 'ok wif cos like tri new thing scare u dun like mah cos u said loud',
 'gent tri contact last weekend draw show prize guarante call claim code k valid hrs ppm',
 'wa ur openin sentenc formal anyway fine juz tt eatin much n puttin weight haha anythin special happen',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'winner u special select receiv holiday flight inc speak live oper claim p min',
 'goodo yes must speak friday egg potato ratio tortilla need',
 'hmm uncl inform pay school direct pls buy food',
 'privat account statement show unredeem bonus point claim call identifi code expir',
 'urgent mobil award bonus caller prize final tri contact u call landlin box wr c ppm',
 'new address appl pair malarki',
 'today voda number end select receiv award match pleas call quot claim code standard rate app',
 'go sao mu today done',
 'predict wat time finish buy',
 'good stuff',
 'know yetund sent money yet sent text bother send dont involv anyth impos anyth first place apologis',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'k k much cost',
 'home',
 'dear call tmorrow pls accomod',
 'first answer question',
 'sunshin quiz wkli q win top soni dvd player u know countri algarv txt ansr sp tyron',
 'want get laid tonight want real dog locat sent direct ur mob join uk largest dog network bt txting gravel nt ec p msg p',
 'haf msn yiju hotmail com',
 'call meet',
 'check room befor activ',
 'rcv msgs chat svc free hardcor servic text go u get noth u must age verifi yr network tri',
 'got c lazi type forgot lect saw pouch like v nice',
 'k text way',
 'sir wait mail',
 'swt thought nver get tire littl thing lovabl person coz somtim littl thing occupi biggest part heart gud ni',
 'know pls open back',
 'yes see ya dot',
 'what staff name take class us',
 'freemsg repli text randi sexi femal live local luv hear u netcollex ltd p per msg repli stop end',
 'ummma call check life begin qatar pls pray hard',
 'k delet contact',
 'sindu got job birla soft',
 'wine flow never',
 'yup thk cine better cos need go plaza mah',
 'ok ur typic repli',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'everywher dirt floor window even shirt sometim open mouth come flow dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time done becom one',
 'aaooooright work',
 'leav hous',
 'hello love get interview today happi good boy think miss',
 'custom servic annonc new year deliveri wait pleas call arrang deliveri',
 'winner u special select receiv cash holiday flight inc speak live oper claim',
 'keep safe need miss alreadi envi everyon see real life',
 'new car hous parent new job hand',
 'love excit day spend make happi',
 'pls stop bootydeli f invit friend repli yes see www sms ac u bootydeli stop send stop frnd',
 'bangbab ur order way u receiv servic msg download ur content u goto wap bangb tv ur mobil internet servic menu',
 'place ur point e cultur modul alreadi',
 'urgent tri contact last weekend draw show prize guarante call claim code valid hrs',
 'hi frnd best way avoid missunderstd wit belov one',
 'great escap fanci bridg need lager see tomo',
 'yes complet form clark also utter wast',
 'sir need axi bank account bank address',
 'hmmm thk sure got time hop ard ya go free abt muz call u discuss liao',
 'time come later',
 'bloodi hell cant believ forgot surnam mr ill give u clue spanish begin',
 'well gonna finish bath good fine night',
 'let know got money carlo make call',
 'u still go mall',
 'turn friend stay whole show back til lt gt feel free go ahead smoke lt gt worth',
 'text doesnt repli let know log',
 'hi spoke maneesha v like know satisfi experi repli toll free yes',
 'lift hope offer money need especi end month approach hurt studi anyway gr weekend',
 'lol u trust',
 'ok gentleman treat digniti respect',
 'guy close',
 'go noth great bye',
 'hello handsom find job lazi work toward get back net mummi boytoy miss',
 'haha awesom minut',
 'pleas call custom servic repres freephon pm guarante cash prize',
 'got xmas radio time get',
 'jus reach home go bath first sis use net tell u finish k',
 'uniqu enough find th august www areyouuniqu co uk',
 'sorri join leagu peopl dont keep touch mean great deal friend time even great person cost great week',
 'hi final complet cours',
 'stop howev suggest stay someon abl give or everi stool',
 'hope settl new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u got person stori',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate even hope see tomorrow bit bloodi babyjontet txt back u xxx',
 'found enc lt gt',
 'sent lt gt buck',
 'hello darlin ive finish colleg txt u finish u love kate xxx',
 'account refil success inr lt decim gt keralacircl prepaid account balanc rs lt decim gt transact id kr lt gt',
 'goodmorn sleep ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'aight yo dat straight dogg',
 'pleas give us connect today lt decim gt refund bill',
 'shoot big load get readi',
 'bruv hope great break reward semest',
 'home alway chat',
 'k k good studi well',
 'yup noe leh',
 'sound great home',
 'final match head toward draw predict',
 'tire slept well past night',
 'easi ah sen got select mean good',
 'take exam march',
 'yeah think use gt atm regist sure anyway help let know sure readi',
 'ok prob take ur time',
 'os call ubandu run without instal hard disk use os copi import file system give repair shop',
 'sorri call later',
 'u say leh cours noth happen lar say v romant jus bit lor thk e nite sceneri nice leh',
 'new mobil must go txt nokia collect today www tc biz optout gbp mtmsg',
 'would realli appreci call need someon talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo follow ur star sign e g horo ari',
 'hey compani elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happi morn',
 'dear good morn',
 'get gandhipuram walk cross cut road right side lt gt street road turn first right',
 'dear go rubber place',
 'sorri batteri die yeah',
 'yes tv alway avail work place',
 'text meet someon sexi today u find date even flirt u join p repli name age eg sam msg recd thirtyeight penc',
 'print oh lt gt come upstair',
 'ill littl closer like bus stop street',
 'wil reach',
 'new theori argument win situat lose person dont argu ur friend kick amp say alway correct',
 'u secret admir look make contact u find r reveal think ur special call',
 'tomarrow final hear laptop case cant',
 'pleassssssseeeee tel v avent done sportsx',
 'okay shine meant sign sound better',
 'although told u dat baig face watch realli like e watch u gave cos fr u thanx everyth dat u done today touch',
 'u rememb old commerci',
 'late said websit dont slipper',
 'ask call ok',
 'kalli wont bat nd inning',
 'didnt work oh ok goodnight fix readi time wake dear miss good night sleep',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tncs www ldew com win ppmx age',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovabl bcum angri wid u dnt take serious coz angri childish n true way show deep affect care n luv kettoda manda nice day da',
 '',
 'up day also ship compani take wks way usp take week get lag may bribe nipost get stuff',
 'back lemm know readi',
 'necessarili expect done get back though headin',
 'mmm yummi babe nice jolt suzi',
 'lover need',
 'tri contact repli offer video handset anytim network min unlimit text camcord repli call',
 'park next mini come today think',
 'yup',
 'anyway go shop cos sis done yet dun disturb u liao',
 'luton ring ur around h',
 'hey realli horni want chat see nake text hot text charg pm unsubscrib text stop',
 'dint come us',
 'wana plan trip sometm',
 'sure yet still tri get hold',
 'ur rington servic chang free credit go club mobil com choos content stop txt club stop p wk club po box mk wt',
 'evo download flash jealous',
 'rington club get uk singl chart mobil week choos top qualiti rington messag free charg',
 'come mu sort narcot situat',
 'night end anoth day morn come special way may smile like sunni ray leav worri blue blue bay',
 'hmv bonus special pound genuin hmv voucher answer easi question play send hmv info www percent real com',
 'usf guess might well take car',
 'object bf come',
 'thanx',
 'tell rob mack gf theater',
 'awesom see bit',
 'sent type food like',
 'done hand celebr full swing yet',
 'got call tool',
 'wen u miss someon person definit special u person special miss keep touch gdeve',
 'ok ask money far',
 'oki',
 'yeah think usual guy still pass last night get ahold anybodi let know throw',
 'k might come tonight class let earli',
 'ok',
 'hi babi im cruisin girl friend r u give call hour home that alright fone fone love jenni xxx',
 'life mean lot love life love peopl life world call friend call world ge',
 'dear shall mail tonit busi street shall updat tonit thing look ok varunnathu edukkukaye raksha ollu good one real sens',
 'hey told name gautham ah',
 'haf u found feel stupid da v cam work',
 'oop got bit',
 'much buzi',
 'accident delet messag resend pleas',
 'mobil custom may claim free camera phone upgrad pay go sim card loyalti call offer end thfeb c appli',
 'unless situat go gurl would appropri',
 'hurt teas make cri end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'cant pick phone right pls send messag',
 'need coffe run tomo believ time week alreadi',
 'awesom rememb last time got somebodi high first time diesel v',
 'shit realli shock scari cant imagin second def night u think somewher could crash night save taxi',
 'oh way food fridg want go meal tonight',
 'womdarful actor',
 'sms ac blind date u rodd aberdeen unit kingdom check http img sms ac w icmb cktz r blind date send hide',
 'yup remb think book',
 'jos ask u wana meet',
 'lol yes friendship hang thread caus u buy stuff',
 'themob check newest select content game tone gossip babe sport keep mobil fit funki text wap',
 'garag key bookshelf',
 'today accept day u accept brother sister lover dear best clos lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rpli mean enemi',
 'think ur smart win week week quiz text play cs winnersclub po box uz gbp week',
 'say give call friend got money definit buy end week',
 'hi way u day normal way real ur uniqu hope know u rest mylif hope u find wot lost',
 'made day great day',
 'k k advanc happi pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao',
 'realli dude friend afraid',
 'decemb mobil mths entitl updat latest colour camera mobil free call mobil updat co free',
 'coffe cake guess',
 'merri christma babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bit l cos buse hav gon past cos full im still waitin pete x',
 'would great guild could meet bristol road somewher get touch weekend plan take flight good week',
 'problem',
 'call messag miss call',
 'hi da today class',
 'say good sign well know track record read women',
 'cool text park',
 'read text sent meant joke read light',
 'k k apo k good movi',
 'mayb could get book tomo return immedi someth',
 'call germani penc per minut call fix line via access number prepay direct access',
 'chanc might evapor soon violat privaci steal phone number employ paperwork cool pleas contact report supervisor',
 'valentin day special win quiz take partner trip lifetim send go p msg rcvd custcar',
 'ta daaaaa home babe still',
 'cool come havent wine dine',
 'sleep surf',
 'sorri call later',
 'u call right call hand phone',
 'ok great thanx lot',
 'take post come must text happi read one wiv hello carolin end favourit bless',
 'u hide stranger',
 'interest like',
 'sister clear two round birla soft yesterday',
 'gudnit tc practic go',
 'dis yiju jus saw ur mail case huim havent sent u num dis num',
 'one small prestig problem',
 'fanci shag interest sextextuk com txt xxuk suzi txts cost per msg tncs websit x',
 'check realli miss see jeremiah great month',
 'nah help never iphon',
 'car hour half go apeshit',
 'today sorri day ever angri ever misbehav hurt plz plz slap urself bcoz ur fault basic good',
 'yo guy ever figur much need alcohol jay tri figur much safe spend weed',
 'lt gt ish minut minut ago wtf',
 'thank call forgot say happi onam sirji fine rememb met insur person meet qatar insha allah rakhesh ex tata aig join tissco tayseer',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tncs www ldew com win ppmx age',
 'ur cash balanc current pound maxim ur cash send cash p msg cc hg suit land row w j hl',
 'actor work work even sleep late sinc unemploy moment alway sleep late unemploy everi day saturday',
 'hello got st andrew boy long way cold keep post',
 'ha ha cool cool chikku chikku db',
 'oh ok prob',
 'check audrey status right',
 'busi tri finish new year look forward final meet',
 'good afternoon sunshin dawn day refresh happi aliv breath air smile think love alway',
 'well know z take care worri',
 'update_now xmas offer latest motorola sonyericsson nokia free bluetooth doubl min txt orang call mobileupd call optout f q',
 'discount code rp stop messag repli stop www regalportfolio co uk custom servic',
 'wat uniform get',
 'cool text readi',
 'hello boytoy geeee miss alreadi woke wish bed cuddl love',
 'spoil bed well',
 'go bath msg next lt gt min',
 'cant keep talk peopl sure pay agre price pls tell want realli buy much will pay',
 'thank rington order refer charg gbp per week unsubscrib anytim call custom servic',
 'say happen',
 'could seen recognis face',
 'well lot thing happen lindsay new year sigh bar ptbo blue heron someth go',
 'keep payasam rinu bring',

### Vectorise (BOW)

In [10]:
## CREATE BAG OF WORDS MODEL
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [15]:
## Independent feature
X=cv.fit_transform(corpus).toarray()

In [12]:
import numpy as np
np.set_printoptions(
    edgeitems=30,
    linewidth=100000,
    formatter=dict(float=lambda x: "%.3g" % x))

X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [13]:
X.shape

(5572, 2500)

In [14]:
cv.vocabulary_

{'go': 803,
 'point': 1605,
 'crazi': 450,
 'avail': 115,
 'bugi': 222,
 'great': 853,
 'world': 2429,
 'la': 1099,
 'cine': 344,
 'got': 842,
 'wat': 2338,
 'ok': 1474,
 'lar': 1110,
 'joke': 1067,
 'wif': 2394,
 'ok lar': 1477,
 'free': 725,
 'entri': 617,
 'wkli': 2418,
 'comp': 392,
 'win': 2399,
 'cup': 468,
 'final': 687,
 'tkts': 2135,
 'st': 1969,
 'may': 1268,
 'text': 2082,
 'receiv': 1704,
 'question': 1663,
 'std': 1984,
 'txt': 2199,
 'rate': 1680,
 'appli': 79,
 'free entri': 730,
 'entri wkli': 619,
 'cup final': 469,
 'std txt': 1985,
 'txt rate': 2203,
 'rate appli': 1682,
 'dun': 575,
 'say': 1806,
 'earli': 583,
 'alreadi': 50,
 'nah': 1389,
 'think': 2104,
 'goe': 822,
 'usf': 2273,
 'live': 1174,
 'around': 91,
 'though': 2114,
 'freemsg': 742,
 'hey': 922,
 'darl': 485,
 'week': 2363,
 'word': 2425,
 'back': 132,
 'like': 1160,
 'fun': 759,
 'still': 1987,
 'tb': 2062,
 'xxx': 2464,
 'send': 1837,
 'rcv': 1688,
 'even': 627,
 'brother': 215,
 'speak': 1949,
 'treat': 2176,
 'per': 1548,
 'request': 1742,
 'mell': 1279,
 'oru': 1516,
 'set': 1859,
 'callertun': 274,
 'caller': 271,
 'press': 1632,
 'copi': 430,
 'friend': 747,
 'per request': 1552,
 'set callertun': 1860,
 'callertun caller': 275,
 'caller press': 272,
 'press copi': 1633,
 'copi friend': 431,
 'friend callertun': 748,
 'winner': 2404,
 'valu': 2281,
 'network': 1406,
 'custom': 474,
 'select': 1831,
 'prize': 1642,
 'reward': 1753,
 'claim': 347,
 'call': 240,
 'code': 365,
 'valid': 2278,
 'hour': 977,
 'claim call': 348,
 'call claim': 245,
 'claim code': 349,
 'valid hour': 2279,
 'mobil': 1328,
 'month': 1349,
 'entitl': 615,
 'updat': 2229,
 'latest': 1120,
 'colour': 378,
 'camera': 281,
 'co': 362,
 'entitl updat': 616,
 'updat latest': 2231,
 'latest colour': 1122,
 'free call': 728,
 'call mobil': 258,
 'mobil updat': 1338,
 'updat co': 2230,
 'co free': 363,
 'gonna': 827,
 'home': 957,
 'soon': 1937,
 'want': 2326,
 'talk': 2058,
 'stuff': 2017,
 'anymor': 67,
 'tonight': 2159,
 'cri': 455,
 'enough': 612,
 'today': 2142,
 'want talk': 2334,
 'chanc': 321,
 'cash': 301,
 'pound': 1617,
 'cost': 435,
 'day': 491,
 'repli': 1732,
 'hl': 939,
 'info': 1022,
 'chanc win': 323,
 'win cash': 2400,
 'repli hl': 1734,
 'hl info': 940,
 'urgent': 2262,
 'www': 2448,
 'net': 1404,
 'pobox': 1601,
 'ldnw': 1133,
 'week free': 2367,
 'txt word': 2205,
 'search': 1817,
 'right': 1755,
 'thank': 2094,
 'promis': 1652,
 'wont': 2424,
 'take': 2052,
 'help': 920,
 'wonder': 2423,
 'bless': 180,
 'time': 2126,
 'date': 489,
 'sunday': 2032,
 'use': 2271,
 'credit': 453,
 'click': 357,
 'wap': 2335,
 'link': 1169,
 'next': 1419,
 'messag': 1285,
 'http': 987,
 'com': 381,
 'oh': 1470,
 'watch': 2343,
 'eh': 595,
 'rememb': 1724,
 'spell': 1957,
 'name': 1391,
 'yes': 2482,
 'naughti': 1396,
 'make': 1235,
 'wet': 2383,
 'fine': 693,
 'way': 2349,
 'feel': 674,
 'england': 608,
 'dont': 553,
 'miss': 1315,
 'goal': 819,
 'team': 2066,
 'news': 1418,
 'ur': 2236,
 'nation': 1393,
 'eg': 593,
 'tri': 2177,
 'wq': 2440,
 'dont miss': 555,
 'serious': 1855,
 'ha': 887,
 'ha ha': 888,
 'pay': 1542,
 'first': 697,
 'da': 479,
 'stock': 1990,
 'comin': 390,
 'aft': 26,
 'finish': 695,
 'lunch': 1224,
 'str': 2010,
 'lor': 1197,
 'ard': 85,
 'smth': 1917,
 'alright': 51,
 'meet': 1275,
 'forc': 714,
 'eat': 589,
 'realli': 1700,
 'hungri': 992,
 'tho': 2113,
 'suck': 2025,
 'mark': 1254,
 'get': 779,
 'worri': 2431,
 'know': 1096,
 'sick': 1880,
 'turn': 2195,
 'pizza': 1573,
 'lol': 1187,
 'alway': 54,
 'convinc': 426,
 'catch': 308,
 'bus': 226,
 'fri': 745,
 'egg': 594,
 'tea': 2064,
 'mom': 1344,
 'left': 1141,
 'dinner': 536,
 'love': 1203,
 'amp': 57,
 'pack': 1525,
 'car': 294,
 'let': 1148,
 'room': 1769,
 'let know': 1149,
 'work': 2426,
 'feel like': 676,
 'wait': 2313,
 'clear': 356,
 'sure': 2041,
 'us': 2270,
 'yeah': 2475,
 'till': 2125,
 'bad': 133,
 'cheer': 335,
 'yeah got': 2476,
 'tell': 2072,
 'anyth': 69,
 'tell anyth': 2073,
 'quick': 1664,
 'subscript': 2023,
 'rington': 1758,
 'uk': 2213,
 'charg': 326,
 'pleas': 1580,
 'confirm': 403,
 'mobil charg': 1330,
 'repli yes': 1737,
 'yup': 2498,
 'look': 1193,
 'msg': 1372,
 'learn': 1135,
 'nd': 1397,
 'lesson': 1147,
 'ok go': 1476,
 'go home': 809,
 'oop': 1499,
 'roommat': 1770,
 'done': 552,
 'see': 1825,
 'letter': 1150,
 'decid': 506,
 'anyth lor': 71,
 'hello': 919,
 'saturday': 1800,
 'tomo': 2150,
 'invit': 1031,
 'pls': 1585,
 'ahead': 34,
 'weekend': 2371,
 'abiola': 1,
 'great weekend': 857,
 'forget': 716,
 'need': 1401,
 'crave': 449,
 'sweet': 2046,
 'want need': 2331,
 'burn': 225,
 'sms': 1915,
 'nokia': 1431,
 'camcord': 277,
 'deliveri': 518,
 'tomorrow': 2151,
 'call repli': 263,
 'free nokia': 736,
 'nokia mobil': 1435,
 'mobil free': 1334,
 'free camcord': 729,
 'pleas call': 1581,
 'call deliveri': 247,
 'deliveri tomorrow': 519,
 'hope': 963,
 'man': 1242,
 'well': 2375,
 'lt': 1215,
 'gt': 864,
 'inch': 1017,
 'lt gt': 1217,
 'gt inch': 867,
 'miss call': 1318,
 'nigeria': 1424,
 'tyler': 2210,
 'could': 440,
 'mayb': 1269,
 'ask': 99,
 'bit': 173,
 'hospit': 972,
 'kept': 1083,
 'weak': 2356,
 'want go': 2329,
 'saw': 1805,
 'class': 354,
 'first time': 698,
 'usual': 2274,
 'run': 1783,
 'half': 894,
 'almost': 48,
 'whole': 2391,
 'second': 1820,
 'like lt': 1163,
 'fyi': 762,
 'ride': 1754,
 'morn': 1354,
 'place': 1574,
 'wow': 2439,
 'never': 1410,
 'realiz': 1699,
 'embarass': 600,
 'thought': 2115,
 'sinc': 1889,
 'best': 159,
 'seem': 1829,
 'happi': 902,
 'sorri': 1938,
 'give': 795,
 'offer': 1464,
 'ac': 4,
 'new': 1411,
 'red': 1710,
 'play': 1577,
 'ice': 999,
 'correct': 432,
 'end': 603,
 'sms ac': 1916,
 'yesterday': 2488,
 'find': 689,
 'congrat': 404,
 'year': 2479,
 'special': 1952,
 'cinema': 345,
 'pass': 1538,
 'etc': 623,
 'bx': 231,
 'ip': 1035,
 'pm': 1595,
 'etc free': 624,
 'bx ip': 232,
 'ip pm': 1036,
 'later': 1117,
 'sorri call': 1939,
 'call later': 256,
 'later meet': 1118,
 'reach': 1692,
 'pick': 1565,
 'move': 1364,
 'pain': 1529,
 'kill': 1089,
 'way home': 2351,
 'good': 829,
 'girl': 793,
 'situat': 1900,
 'part': 1534,
 'check': 334,
 'took': 2161,
 'forev': 715,
 'come': 384,
 'ok come': 1475,
 'doubl': 558,
 'hair': 893,
 'said': 1791,
 'wun': 2447,
 'cut': 476,
 'short': 1874,
 'nice': 1422,
 'follow': 710,
 'recent': 1708,
 'review': 1752,
 'mob': 1326,
 'award': 121,
 'bonus': 186,
 'award bonus': 122,
 'prize call': 1643,
 'song': 1933,
 'frnds': 754,
 'rpli': 1776,
 'send ur': 1850,
 'complimentari': 396,
 'trip': 2182,
 'dis': 539,
 'ls': 1214,
 'ur award': 2237,
 'hear': 912,
 'plane': 1576,
 'lucki': 1222,
 'save': 1804,
 'money': 1348,
 'hee': 916,
 'hi': 927,
 'babe': 129,
 'im': 1007,
 'wanna': 2325,
 'someth': 1928,
 'xx': 2463,
 'hi babe': 928,
 'call free': 248,
 'that': 2099,
 'cool': 428,
 'respect': 1743,
 'that cool': 2100,
 'peopl': 1547,
 'much': 1379,
 'pa': 1523,
 'oper': 1501,
 'job': 1062,
 'ta': 2051,
 'ah': 32,
 'hi hi': 931,
 'stop': 1994,
 'urgnt': 2268,
 'real': 1697,
 'yo': 2492,
 'ticket': 2123,
 'one': 1493,
 'start': 1978,
 'came': 279,
 'bed': 151,
 'coin': 370,
 'gotta': 848,
 'kano': 1078,
 'il': 1005,
 'download': 560,
 'wen': 2378,
 'wen ur': 2379,
 'stand': 1974,
 'close': 359,
 'anoth': 63,
 'night': 1425,
 'spent': 1959,
 'late': 1116,
 'afternoon': 27,
 'mean': 1271,
 'moro': 1359,
 'includ': 1018,
 'smile': 1912,
 'pleasur': 1583,
 'troubl': 2183,
 'rain': 1673,
 'sum': 2029,
 'hurt': 995,
 'someon': 1926,
 'servic': 1856,
 'repres': 1739,
 'guarante': 875,
 'call custom': 246,
 'custom servic': 475,
 'servic repres': 1858,
 'repres pm': 1741,
 'pm guarante': 1597,
 'guarante cash': 877,
 'cash prize': 305,
 'havent': 910,
 'plan': 1575,
 'buy': 229,
 'show': 1875,
 'collect': 374,
 'simpli': 1888,
 'password': 1540,
 'verifi': 2283,
 'po': 1599,
 'box': 199,
 'mk': 1322,
 'free rington': 739,
 'po box': 1600,
 'box mk': 202,
 'movi': 1365,
 'abt': 3,
 'wat abt': 2339,
 'load': 1178,
 'loan': 1179,
 'wk': 2416,
 'hol': 946,
 'forgot': 717,
 'appoint': 80,
 'shower': 1878,
 'caus': 309,
 'prob': 1647,
 'need get': 1402,
 'get home': 782,
 'coffe': 369,
 'noth': 1448,
 'els': 597,
 'okay': 1487,
 'price': 1636,
 'long': 1190,
 'ave': 116,
 'gone': 826,
 'drive': 569,
 'test': 2081,
 'yet': 2489,
 'guess': 883,
 'gave': 769,
 'boston': 194,
 'men': 1282,
 'chang': 324,
 'locat': 1181,
 'cuz': 478,
 'page': 1527,
 'umma': 2215,
 'life': 1155,
 'lot': 1201,
 'dear': 502,
 'love lot': 1208,
 'wish': 2406,
 'birthday': 169,
 'truli': 2185,
 'aight': 36,
 'hit': 937,
 'would': 2437,
 'address': 17,
 'consid': 409,
 'comput': 397,
 'old': 1490,
 'better': 161,
 'lie': 1154,
 'busi': 228,
 'go dinner': 807,
 'cos': 433,
 'thing': 2103,
 'scare': 1809,
 'mah': 1230,
 'contact': 411,
 'last': 1111,
 'draw': 561,
 'hrs': 985,
 'ppm': 1622,
 'tri contact': 2178,
 'contact last': 416,
 'last weekend': 1115,
 'weekend draw': 2372,
 'draw show': 563,
 'show prize': 1876,
 'prize guarante': 1645,
 'guarante call': 876,
 'code valid': 368,
 'valid hrs': 2280,
 'hrs ppm': 986,
 'wa': 2312,
 'anyway': 74,
 'juz': 1076,
 'tt': 2191,
 'eatin': 590,
 'weight': 2373,
 'haha': 890,
 'happen': 901,
 'enter': 613,
 'cabin': 234,
 'boss': 192,
 'felt': 677,
 'askd': 100,
 'apart': 76,
 'went': 2380,
 'enter cabin': 614,
 'cabin pa': 235,
 'pa said': 1524,
 'said happi': 1792,
 'happi day': 904,
 'day boss': 492,
 'boss felt': 193,
 'felt special': 678,
 'special askd': 1953,
 'askd lunch': 101,
 'lunch lunch': 1226,
 'lunch invit': 1225,
 'invit apart': 1032,
 'apart went': 77,
 'holiday': 951,
 'flight': 706,
 'inc': 1016,
 'min': 1297,
 'winner special': 2405,
 'special select': 1955,
 'select receiv': 1832,
 'holiday flight': 954,
 'flight inc': 707,
 'speak live': 1950,
 'live oper': 1176,
 'oper claim': 1502,
 'must': 1386,
 'friday': 746,
 'hmm': 942,
 'uncl': 2219,
 'inform': 1023,
 'school': 1811,
 'direct': 538,
 'food': 712,
 'privat': 1640,
 'account': 8,
 'statement': 1980,
 'identifi': 1002,
 'expir': 648,
 'privat account': 1641,
 'account statement': 9,
 'statement show': 1981,
 'call identifi': 252,
 'identifi code': 1003,
 'code expir': 366,
 'landlin': 1106,
 'urgent mobil': 2265,
 'mobil award': 1329,
 'bonus caller': 187,
 'caller prize': 273,
 'contact call': 412,
 'call landlin': 255,
 'voda': 2303,
 'number': 1455,
 'match': 1257,
 'quot': 1668,
 'standard': 1975,
 'app': 78,
 'today voda': 2147,
 'voda number': 2304,
 'number end': 1457,
 'end select': 604,
 'receiv award': 1705,
 'match pleas': 1258,
 'call quot': 262,
 'quot claim': 1669,
 'code standard': 367,
 'standard rate': 1976,
 'rate app': 1681,
 'mu': 1378,
 'predict': 1628,
 'wat time': 2341,
 'time finish': 2128,
 'sent': 1852,
 'bother': 195,
 'del': 514,
 'bak': 135,
 'long time': 1191,
 'give call': 796,
 'dear call': 503,
 'answer': 65,
 'sunshin': 2034,
 'quiz': 1666,
 'top': 2162,
 'soni': 1934,
 'dvd': 581,
 'player': 1579,
 'countri': 442,
 'sp': 1947,
 'sunshin quiz': 2035,
 'quiz wkli': 1667,
 'soni dvd': 1935,
 'dvd player': 582,
 'laid': 1102,
 'dog': 549,
 'join': 1065,
 'bt': 217,
 'txting': 2207,
 'nt': 1450,
 'ec': 591,
 'want get': 2328,
 'sent direct': 1853,
 'ur mob': 2253,
 'join uk': 1066,
 'haf': 889,
 'yiju': 2490,
 'activ': 13,
 'msgs': 1375,
 'chat': 331,
 'age': 30,
 'yr': 2495,
 'go get': 808,
 'lazi': 1129,
 'type': 2211,
 'lect': 1139,
 'sir': 1894,
 'mail': 1232,
 'sir wait': 1895,
 'swt': 2049,
 'tire': 2132,
 'littl': 1173,
 'lovabl': 1202,
 'person': 1554,
 'coz': 446,
 'biggest': 165,
 'heart': 914,
 'gud': 878,
 'ni': 1421,
 'gud ni': 881,
 'open': 1500,
 'ya': 2468,
 'yes see': 2486,
 'what': 2384,
 'sexi': 1863,
 'local': 1180,
 'luv': 1227,
 'ltd': 1219,
 'per msg': 1551,
 'repli stop': 1736,
 'stop end': 1997,
 'begin': 155,
 'qatar': 1658,
 'pray': 1627,
 'hard': 906,
 'delet': 516,
 'got job': 844,
 'wine': 2403,
 'thk': 2111,
 'need go': 1403,
 'shirt': 1870,
 'sometim': 1931,
 'dream': 565,
 'without': 2414,
 'joy': 1070,
 'tv': 2196,
 'becom': 150,
 'leav': 1137,
 'hous': 978,
 'leav hous': 1138,
 'interview': 1029,
 'boy': 206,
 'arrang': 93,
 'new year': 1417,
 'receiv cash': 1706,
 'keep': 1081,
 'safe': 1790,
 'everyon': 634,
 'miss alreadi': 1316,
 'parent': 1531,
 'hand': 898,
 'new job': 1412,
 'excit': 642,
 'spend': 1958,
 'make happi': 1238,
 'frnd': 753,
 'invit friend': 1033,
 'friend repli': 749,
 'see www': 1828,
 'www sms': 2452,
 'stop send': 2001,
 'send stop': 1847,
 'stop frnd': 1999,
 'order': 1512,
 'content': 421,
 'goto': 847,
 'internet': 1028,
 'menu': 1283,
 'ur mobil': 2254,
 'urgent tri': 2267,
 'avoid': 117,
 'wit': 2411,
 'fanci': 659,
 'complet': 395,
 'also': 53,
 'wast': 2337,
 'bank': 138,
 'hmmm': 943,
 'hop': 962,
 'muz': 1387,
 'discuss': 542,
 'liao': 1151,
 'time come': 2127,
 'hell': 917,
 'cant': 289,
 'believ': 157,
 'mr': 1368,
 'ill': 1006,
 'bath': 142,
 'carlo': 298,
 'got money': 845,
 'stay': 1983,
 'til': 2124,
 'smoke': 1913,
 'worth': 2434,
 'doesnt': 548,
 'log': 1182,
 'spoke': 1961,
 'satisfi': 1799,
 'experi': 647,
 'lift': 1156,
 'especi': 622,
 'studi': 2016,
 'gr': 849,
 'trust': 2186,
 'guy': 885,
 'bye': 233,
 'toward': 2169,
 'boytoy': 207,
 'get back': 780,
 'awesom': 128,
 'minut': 1308,
 'haha awesom': 891,
 'freephon': 743,
 'repres freephon': 1740,
 'xmas': 2461,
 'radio': 1672,
 'jus': 1074,
 'sis': 1896,
 'reach home': 1694,
 'th': 2092,
 'co uk': 364,
 'touch': 2166,
 'deal': 501,
 'keep touch': 1082,
 'great week': 856,
 'cours': 444,
 'howev': 981,
 'suggest': 2026,
 'abl': 2,
 'everi': 630,
 'settl': 1861,
 'gr day': 850,
 'mrng': 1369,
 'hav': 909,
 'gud mrng': 880,
 'nice day': 1423,
 'stori': 2008,
 'person stori': 1556,
 'dead': 500,
 'tmr': 2137,
 'orchard': 1511,
 'mrt': 1370,
 'kate': 1079,
 'see tomorrow': 1827,
 'found': 722,
 'buck': 220,
 'gt buck': 865,
 'darlin': 486,
 'ive': 1045,
 'colleg': 377,
 'success': 2024,
 'decim': 507,
 'balanc': 136,
 'rs': 1777,
 'transact': 2173,
 'id': 1000,
 'lt decim': 1216,
 'decim gt': 508,
 'rs lt': 1778,
 'goodmorn': 838,
 'sleep': 1906,
 'dat': 488,
 'oso': 1517,
 'cannot': 288,
 'oredi': 1513,
 'like dat': 1161,
 'straight': 2011,
 'connect': 408,
 'bill': 166,
 'give us': 797,
 'big': 164,
 'readi': 1696,
 'get readi': 783,
 'break': 210,
 'semest': 1835,
 'hope great': 968,
 'noe': 1430,
 'leh': 1142,
 'sound': 1944,
 'head': 911,
 'slept': 1908,
 'past': 1541,
 'easi': 586,
 'sen': 1836,
 'exam': 639,
 'march': 1253,
 'atm': 107,
 'regist': 1718,
 'ok prob': 1480,
 'import': 1013,
 'file': 684,
 'system': 2050,
 'shop': 1872,
 'romant': 1767,
 'nite': 1428,
 'tc': 2063,
 'biz': 176,
 'optout': 1508,
 'gbp': 773,
 'mtmsg': 1377,
 'new mobil': 1413,
 'txt nokia': 2202,
 'appreci': 81,
 'partner': 1537,
 'career': 297,
 'star': 1977,
 'sign': 1884,
 'compani': 393,
 'bcoz': 146,
 'teach': 2065,
 'good morn': 835,
 'walk': 2318,
 'cross': 456,
 'road': 1763,
 'side': 1881,
 'street': 2012,
 'batteri': 143,
 'die': 529,
 'flirt': 708,
 'sam': 1797,
 'text meet': 2088,
 'print': 1639,
 'bus stop': 227,
 'wil': 2397,
 'argument': 88,
 'lose': 1199,
 'argu': 87,
 'kick': 1086,
 'person dont': 1555,
 'ur friend': 2243,
 'secret': 1821,
 'admir': 18,
 'reveal': 1750,
 'secret admir': 1822,
 'admir look': 19,
 'look make': 1195,
 'make contact': 1236,
 'contact find': 415,
 'find reveal': 692,
 'reveal think': 1751,
 'think ur': 2109,
 'ur special': 2258,
 'special call': 1954,
 'laptop': 1109,
 'case': 300,
 'tel': 2071,
 'meant': 1272,
 'told': 2149,
 'face': 653,
 'fr': 723,
 'thanx': 2098,
 'everyth': 635,
 'websit': 2359,
 'kalli': 1077,
 'didnt': 527,
 'goodnight': 840,
 'fix': 700,
 'wake': 2317,
 'oh ok': 1472,
 'good night': 836,
 'congratul': 406,
 'cd': 312,
 'voucher': 2309,
 'gift': 790,
 'music': 1383,
 'tncs': 2138,
 'ldew': 1130,
 'ppmx': 1623,
 'congratul ur': 407,
 'gift guarante': 791,
 'draw txt': 564,
 'txt music': 2201,
 'music tncs': 1385,
 'tncs www': 2139,
 'www ldew': 2451,
 'ldew com': 1131,
 'com win': 383,
 'win ppmx': 2402,
 'ppmx age': 1624,
 'cal': 239,
 'hold': 947,
 'bcum': 147,
 'angri': 60,
 'wid': 2392,
 'dnt': 545,
 'childish': 338,
 'true': 2184,
 'deep': 510,
 'affect': 25,
 'care': 296,
 'manda': 1246,
 'ur lovabl': 2249,
 'angri childish': 61,
 ...}

In [18]:
## Output feature
## We will use pd.get_dummies to label (ham,spam) as (0,1)

y=pd.get_dummies(messages['label'],dtype=int)
y

      ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5572 rows x 2 columns]

There are several ways to perform this but we want to try new things. We will take the spam column since that will be our main target ('1')

In [19]:
y=y.spam
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: spam, Length: 5572, dtype: int32

In [20]:
## Train Test Split
from sklearn.model_selection import train_test_split

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20, random_state=42)

In [22]:
from sklearn.naive_bayes import MultinomialNB

NOTE: **`Naive Bayes`** works very well with `Sparse Matrix`. This is the type of matrix we are getting using Bag Of Words.

In [23]:
mnb=MultinomialNB()
mnb.fit(X_train,y_train)

MultinomialNB()

In [26]:
## Predict
y_pred=mnb.predict(X_test)

In [27]:
## Get performance report

from sklearn.metrics import accuracy_score,classification_report
accuracy_score(y_test,y_pred)

0.9874439461883409

In [28]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.96      0.95      0.95       149

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

This was just to give you an idea. Next time ensure you follow all training steps eg Checking if the data is balanced.

### Vectorise (TF-IDF)

In [29]:
## Create TF-IDF Model
from sklearn.feature_extraction.text import TfidfVectorizer

In [31]:
tfidf=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X=tfidf.fit_transform(corpus).toarray()

In [32]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.268, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.272, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.406, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.194, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.345, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [33]:
tfidf.vocabulary_

{'go': 803,
 'point': 1605,
 'crazi': 450,
 'avail': 115,
 'bugi': 222,
 'great': 853,
 'world': 2429,
 'la': 1099,
 'cine': 344,
 'got': 842,
 'wat': 2338,
 'ok': 1474,
 'lar': 1110,
 'joke': 1067,
 'wif': 2394,
 'ok lar': 1477,
 'free': 725,
 'entri': 617,
 'wkli': 2418,
 'comp': 392,
 'win': 2399,
 'cup': 468,
 'final': 687,
 'tkts': 2135,
 'st': 1969,
 'may': 1268,
 'text': 2082,
 'receiv': 1704,
 'question': 1663,
 'std': 1984,
 'txt': 2199,
 'rate': 1680,
 'appli': 79,
 'free entri': 730,
 'entri wkli': 619,
 'cup final': 469,
 'std txt': 1985,
 'txt rate': 2203,
 'rate appli': 1682,
 'dun': 575,
 'say': 1806,
 'earli': 583,
 'alreadi': 50,
 'nah': 1389,
 'think': 2104,
 'goe': 822,
 'usf': 2273,
 'live': 1174,
 'around': 91,
 'though': 2114,
 'freemsg': 742,
 'hey': 922,
 'darl': 485,
 'week': 2363,
 'word': 2425,
 'back': 132,
 'like': 1160,
 'fun': 759,
 'still': 1987,
 'tb': 2062,
 'xxx': 2464,
 'send': 1837,
 'rcv': 1688,
 'even': 627,
 'brother': 215,
 'speak': 1949,
 'treat': 2176,
 'per': 1548,
 'request': 1742,
 'mell': 1279,
 'oru': 1516,
 'set': 1859,
 'callertun': 274,
 'caller': 271,
 'press': 1632,
 'copi': 430,
 'friend': 747,
 'per request': 1552,
 'set callertun': 1860,
 'callertun caller': 275,
 'caller press': 272,
 'press copi': 1633,
 'copi friend': 431,
 'friend callertun': 748,
 'winner': 2404,
 'valu': 2281,
 'network': 1406,
 'custom': 474,
 'select': 1831,
 'prize': 1642,
 'reward': 1753,
 'claim': 347,
 'call': 240,
 'code': 365,
 'valid': 2278,
 'hour': 977,
 'claim call': 348,
 'call claim': 245,
 'claim code': 349,
 'valid hour': 2279,
 'mobil': 1328,
 'month': 1349,
 'entitl': 615,
 'updat': 2229,
 'latest': 1120,
 'colour': 378,
 'camera': 281,
 'co': 362,
 'entitl updat': 616,
 'updat latest': 2231,
 'latest colour': 1122,
 'free call': 728,
 'call mobil': 258,
 'mobil updat': 1338,
 'updat co': 2230,
 'co free': 363,
 'gonna': 827,
 'home': 957,
 'soon': 1937,
 'want': 2326,
 'talk': 2058,
 'stuff': 2017,
 'anymor': 67,
 'tonight': 2159,
 'cri': 455,
 'enough': 612,
 'today': 2142,
 'want talk': 2334,
 'chanc': 321,
 'cash': 301,
 'pound': 1617,
 'cost': 435,
 'day': 491,
 'repli': 1732,
 'hl': 939,
 'info': 1022,
 'chanc win': 323,
 'win cash': 2400,
 'repli hl': 1734,
 'hl info': 940,
 'urgent': 2262,
 'www': 2448,
 'net': 1404,
 'pobox': 1601,
 'ldnw': 1133,
 'week free': 2367,
 'txt word': 2205,
 'search': 1817,
 'right': 1755,
 'thank': 2094,
 'promis': 1652,
 'wont': 2424,
 'take': 2052,
 'help': 920,
 'wonder': 2423,
 'bless': 180,
 'time': 2126,
 'date': 489,
 'sunday': 2032,
 'use': 2271,
 'credit': 453,
 'click': 357,
 'wap': 2335,
 'link': 1169,
 'next': 1419,
 'messag': 1285,
 'http': 987,
 'com': 381,
 'oh': 1470,
 'watch': 2343,
 'eh': 595,
 'rememb': 1724,
 'spell': 1957,
 'name': 1391,
 'yes': 2482,
 'naughti': 1396,
 'make': 1235,
 'wet': 2383,
 'fine': 693,
 'way': 2349,
 'feel': 674,
 'england': 608,
 'dont': 553,
 'miss': 1315,
 'goal': 819,
 'team': 2066,
 'news': 1418,
 'ur': 2236,
 'nation': 1393,
 'eg': 593,
 'tri': 2177,
 'wq': 2440,
 'dont miss': 555,
 'serious': 1855,
 'ha': 887,
 'ha ha': 888,
 'pay': 1542,
 'first': 697,
 'da': 479,
 'stock': 1990,
 'comin': 390,
 'aft': 26,
 'finish': 695,
 'lunch': 1224,
 'str': 2010,
 'lor': 1197,
 'ard': 85,
 'smth': 1917,
 'alright': 51,
 'meet': 1275,
 'forc': 714,
 'eat': 589,
 'realli': 1700,
 'hungri': 992,
 'tho': 2113,
 'suck': 2025,
 'mark': 1254,
 'get': 779,
 'worri': 2431,
 'know': 1096,
 'sick': 1880,
 'turn': 2195,
 'pizza': 1573,
 'lol': 1187,
 'alway': 54,
 'convinc': 426,
 'catch': 308,
 'bus': 226,
 'fri': 745,
 'egg': 594,
 'tea': 2064,
 'mom': 1344,
 'left': 1141,
 'dinner': 536,
 'love': 1203,
 'amp': 57,
 'pack': 1525,
 'car': 294,
 'let': 1148,
 'room': 1769,
 'let know': 1149,
 'work': 2426,
 'feel like': 676,
 'wait': 2313,
 'clear': 356,
 'sure': 2041,
 'us': 2270,
 'yeah': 2475,
 'till': 2125,
 'bad': 133,
 'cheer': 335,
 'yeah got': 2476,
 'tell': 2072,
 'anyth': 69,
 'tell anyth': 2073,
 'quick': 1664,
 'subscript': 2023,
 'rington': 1758,
 'uk': 2213,
 'charg': 326,
 'pleas': 1580,
 'confirm': 403,
 'mobil charg': 1330,
 'repli yes': 1737,
 'yup': 2498,
 'look': 1193,
 'msg': 1372,
 'learn': 1135,
 'nd': 1397,
 'lesson': 1147,
 'ok go': 1476,
 'go home': 809,
 'oop': 1499,
 'roommat': 1770,
 'done': 552,
 'see': 1825,
 'letter': 1150,
 'decid': 506,
 'anyth lor': 71,
 'hello': 919,
 'saturday': 1800,
 'tomo': 2150,
 'invit': 1031,
 'pls': 1585,
 'ahead': 34,
 'weekend': 2371,
 'abiola': 1,
 'great weekend': 857,
 'forget': 716,
 'need': 1401,
 'crave': 449,
 'sweet': 2046,
 'want need': 2331,
 'burn': 225,
 'sms': 1915,
 'nokia': 1431,
 'camcord': 277,
 'deliveri': 518,
 'tomorrow': 2151,
 'call repli': 263,
 'free nokia': 736,
 'nokia mobil': 1435,
 'mobil free': 1334,
 'free camcord': 729,
 'pleas call': 1581,
 'call deliveri': 247,
 'deliveri tomorrow': 519,
 'hope': 963,
 'man': 1242,
 'well': 2375,
 'lt': 1215,
 'gt': 864,
 'inch': 1017,
 'lt gt': 1217,
 'gt inch': 867,
 'miss call': 1318,
 'nigeria': 1424,
 'tyler': 2210,
 'could': 440,
 'mayb': 1269,
 'ask': 99,
 'bit': 173,
 'hospit': 972,
 'kept': 1083,
 'weak': 2356,
 'want go': 2329,
 'saw': 1805,
 'class': 354,
 'first time': 698,
 'usual': 2274,
 'run': 1783,
 'half': 894,
 'almost': 48,
 'whole': 2391,
 'second': 1820,
 'like lt': 1163,
 'fyi': 762,
 'ride': 1754,
 'morn': 1354,
 'place': 1574,
 'wow': 2439,
 'never': 1410,
 'realiz': 1699,
 'embarass': 600,
 'thought': 2115,
 'sinc': 1889,
 'best': 159,
 'seem': 1829,
 'happi': 902,
 'sorri': 1938,
 'give': 795,
 'offer': 1464,
 'ac': 4,
 'new': 1411,
 'red': 1710,
 'play': 1577,
 'ice': 999,
 'correct': 432,
 'end': 603,
 'sms ac': 1916,
 'yesterday': 2488,
 'find': 689,
 'congrat': 404,
 'year': 2479,
 'special': 1952,
 'cinema': 345,
 'pass': 1538,
 'etc': 623,
 'bx': 231,
 'ip': 1035,
 'pm': 1595,
 'etc free': 624,
 'bx ip': 232,
 'ip pm': 1036,
 'later': 1117,
 'sorri call': 1939,
 'call later': 256,
 'later meet': 1118,
 'reach': 1692,
 'pick': 1565,
 'move': 1364,
 'pain': 1529,
 'kill': 1089,
 'way home': 2351,
 'good': 829,
 'girl': 793,
 'situat': 1900,
 'part': 1534,
 'check': 334,
 'took': 2161,
 'forev': 715,
 'come': 384,
 'ok come': 1475,
 'doubl': 558,
 'hair': 893,
 'said': 1791,
 'wun': 2447,
 'cut': 476,
 'short': 1874,
 'nice': 1422,
 'follow': 710,
 'recent': 1708,
 'review': 1752,
 'mob': 1326,
 'award': 121,
 'bonus': 186,
 'award bonus': 122,
 'prize call': 1643,
 'song': 1933,
 'frnds': 754,
 'rpli': 1776,
 'send ur': 1850,
 'complimentari': 396,
 'trip': 2182,
 'dis': 539,
 'ls': 1214,
 'ur award': 2237,
 'hear': 912,
 'plane': 1576,
 'lucki': 1222,
 'save': 1804,
 'money': 1348,
 'hee': 916,
 'hi': 927,
 'babe': 129,
 'im': 1007,
 'wanna': 2325,
 'someth': 1928,
 'xx': 2463,
 'hi babe': 928,
 'call free': 248,
 'that': 2099,
 'cool': 428,
 'respect': 1743,
 'that cool': 2100,
 'peopl': 1547,
 'much': 1379,
 'pa': 1523,
 'oper': 1501,
 'job': 1062,
 'ta': 2051,
 'ah': 32,
 'hi hi': 931,
 'stop': 1994,
 'urgnt': 2268,
 'real': 1697,
 'yo': 2492,
 'ticket': 2123,
 'one': 1493,
 'start': 1978,
 'came': 279,
 'bed': 151,
 'coin': 370,
 'gotta': 848,
 'kano': 1078,
 'il': 1005,
 'download': 560,
 'wen': 2378,
 'wen ur': 2379,
 'stand': 1974,
 'close': 359,
 'anoth': 63,
 'night': 1425,
 'spent': 1959,
 'late': 1116,
 'afternoon': 27,
 'mean': 1271,
 'moro': 1359,
 'includ': 1018,
 'smile': 1912,
 'pleasur': 1583,
 'troubl': 2183,
 'rain': 1673,
 'sum': 2029,
 'hurt': 995,
 'someon': 1926,
 'servic': 1856,
 'repres': 1739,
 'guarante': 875,
 'call custom': 246,
 'custom servic': 475,
 'servic repres': 1858,
 'repres pm': 1741,
 'pm guarante': 1597,
 'guarante cash': 877,
 'cash prize': 305,
 'havent': 910,
 'plan': 1575,
 'buy': 229,
 'show': 1875,
 'collect': 374,
 'simpli': 1888,
 'password': 1540,
 'verifi': 2283,
 'po': 1599,
 'box': 199,
 'mk': 1322,
 'free rington': 739,
 'po box': 1600,
 'box mk': 202,
 'movi': 1365,
 'abt': 3,
 'wat abt': 2339,
 'load': 1178,
 'loan': 1179,
 'wk': 2416,
 'hol': 946,
 'forgot': 717,
 'appoint': 80,
 'shower': 1878,
 'caus': 309,
 'prob': 1647,
 'need get': 1402,
 'get home': 782,
 'coffe': 369,
 'noth': 1448,
 'els': 597,
 'okay': 1487,
 'price': 1636,
 'long': 1190,
 'ave': 116,
 'gone': 826,
 'drive': 569,
 'test': 2081,
 'yet': 2489,
 'guess': 883,
 'gave': 769,
 'boston': 194,
 'men': 1282,
 'chang': 324,
 'locat': 1181,
 'cuz': 478,
 'page': 1527,
 'umma': 2215,
 'life': 1155,
 'lot': 1201,
 'dear': 502,
 'love lot': 1208,
 'wish': 2406,
 'birthday': 169,
 'truli': 2185,
 'aight': 36,
 'hit': 937,
 'would': 2437,
 'address': 17,
 'consid': 409,
 'comput': 397,
 'old': 1490,
 'better': 161,
 'lie': 1154,
 'busi': 228,
 'go dinner': 807,
 'cos': 433,
 'thing': 2103,
 'scare': 1809,
 'mah': 1230,
 'contact': 411,
 'last': 1111,
 'draw': 561,
 'hrs': 985,
 'ppm': 1622,
 'tri contact': 2178,
 'contact last': 416,
 'last weekend': 1115,
 'weekend draw': 2372,
 'draw show': 563,
 'show prize': 1876,
 'prize guarante': 1645,
 'guarante call': 876,
 'code valid': 368,
 'valid hrs': 2280,
 'hrs ppm': 986,
 'wa': 2312,
 'anyway': 74,
 'juz': 1076,
 'tt': 2191,
 'eatin': 590,
 'weight': 2373,
 'haha': 890,
 'happen': 901,
 'enter': 613,
 'cabin': 234,
 'boss': 192,
 'felt': 677,
 'askd': 100,
 'apart': 76,
 'went': 2380,
 'enter cabin': 614,
 'cabin pa': 235,
 'pa said': 1524,
 'said happi': 1792,
 'happi day': 904,
 'day boss': 492,
 'boss felt': 193,
 'felt special': 678,
 'special askd': 1953,
 'askd lunch': 101,
 'lunch lunch': 1226,
 'lunch invit': 1225,
 'invit apart': 1032,
 'apart went': 77,
 'holiday': 951,
 'flight': 706,
 'inc': 1016,
 'min': 1297,
 'winner special': 2405,
 'special select': 1955,
 'select receiv': 1832,
 'holiday flight': 954,
 'flight inc': 707,
 'speak live': 1950,
 'live oper': 1176,
 'oper claim': 1502,
 'must': 1386,
 'friday': 746,
 'hmm': 942,
 'uncl': 2219,
 'inform': 1023,
 'school': 1811,
 'direct': 538,
 'food': 712,
 'privat': 1640,
 'account': 8,
 'statement': 1980,
 'identifi': 1002,
 'expir': 648,
 'privat account': 1641,
 'account statement': 9,
 'statement show': 1981,
 'call identifi': 252,
 'identifi code': 1003,
 'code expir': 366,
 'landlin': 1106,
 'urgent mobil': 2265,
 'mobil award': 1329,
 'bonus caller': 187,
 'caller prize': 273,
 'contact call': 412,
 'call landlin': 255,
 'voda': 2303,
 'number': 1455,
 'match': 1257,
 'quot': 1668,
 'standard': 1975,
 'app': 78,
 'today voda': 2147,
 'voda number': 2304,
 'number end': 1457,
 'end select': 604,
 'receiv award': 1705,
 'match pleas': 1258,
 'call quot': 262,
 'quot claim': 1669,
 'code standard': 367,
 'standard rate': 1976,
 'rate app': 1681,
 'mu': 1378,
 'predict': 1628,
 'wat time': 2341,
 'time finish': 2128,
 'sent': 1852,
 'bother': 195,
 'del': 514,
 'bak': 135,
 'long time': 1191,
 'give call': 796,
 'dear call': 503,
 'answer': 65,
 'sunshin': 2034,
 'quiz': 1666,
 'top': 2162,
 'soni': 1934,
 'dvd': 581,
 'player': 1579,
 'countri': 442,
 'sp': 1947,
 'sunshin quiz': 2035,
 'quiz wkli': 1667,
 'soni dvd': 1935,
 'dvd player': 582,
 'laid': 1102,
 'dog': 549,
 'join': 1065,
 'bt': 217,
 'txting': 2207,
 'nt': 1450,
 'ec': 591,
 'want get': 2328,
 'sent direct': 1853,
 'ur mob': 2253,
 'join uk': 1066,
 'haf': 889,
 'yiju': 2490,
 'activ': 13,
 'msgs': 1375,
 'chat': 331,
 'age': 30,
 'yr': 2495,
 'go get': 808,
 'lazi': 1129,
 'type': 2211,
 'lect': 1139,
 'sir': 1894,
 'mail': 1232,
 'sir wait': 1895,
 'swt': 2049,
 'tire': 2132,
 'littl': 1173,
 'lovabl': 1202,
 'person': 1554,
 'coz': 446,
 'biggest': 165,
 'heart': 914,
 'gud': 878,
 'ni': 1421,
 'gud ni': 881,
 'open': 1500,
 'ya': 2468,
 'yes see': 2486,
 'what': 2384,
 'sexi': 1863,
 'local': 1180,
 'luv': 1227,
 'ltd': 1219,
 'per msg': 1551,
 'repli stop': 1736,
 'stop end': 1997,
 'begin': 155,
 'qatar': 1658,
 'pray': 1627,
 'hard': 906,
 'delet': 516,
 'got job': 844,
 'wine': 2403,
 'thk': 2111,
 'need go': 1403,
 'shirt': 1870,
 'sometim': 1931,
 'dream': 565,
 'without': 2414,
 'joy': 1070,
 'tv': 2196,
 'becom': 150,
 'leav': 1137,
 'hous': 978,
 'leav hous': 1138,
 'interview': 1029,
 'boy': 206,
 'arrang': 93,
 'new year': 1417,
 'receiv cash': 1706,
 'keep': 1081,
 'safe': 1790,
 'everyon': 634,
 'miss alreadi': 1316,
 'parent': 1531,
 'hand': 898,
 'new job': 1412,
 'excit': 642,
 'spend': 1958,
 'make happi': 1238,
 'frnd': 753,
 'invit friend': 1033,
 'friend repli': 749,
 'see www': 1828,
 'www sms': 2452,
 'stop send': 2001,
 'send stop': 1847,
 'stop frnd': 1999,
 'order': 1512,
 'content': 421,
 'goto': 847,
 'internet': 1028,
 'menu': 1283,
 'ur mobil': 2254,
 'urgent tri': 2267,
 'avoid': 117,
 'wit': 2411,
 'fanci': 659,
 'complet': 395,
 'also': 53,
 'wast': 2337,
 'bank': 138,
 'hmmm': 943,
 'hop': 962,
 'muz': 1387,
 'discuss': 542,
 'liao': 1151,
 'time come': 2127,
 'hell': 917,
 'cant': 289,
 'believ': 157,
 'mr': 1368,
 'ill': 1006,
 'bath': 142,
 'carlo': 298,
 'got money': 845,
 'stay': 1983,
 'til': 2124,
 'smoke': 1913,
 'worth': 2434,
 'doesnt': 548,
 'log': 1182,
 'spoke': 1961,
 'satisfi': 1799,
 'experi': 647,
 'lift': 1156,
 'especi': 622,
 'studi': 2016,
 'gr': 849,
 'trust': 2186,
 'guy': 885,
 'bye': 233,
 'toward': 2169,
 'boytoy': 207,
 'get back': 780,
 'awesom': 128,
 'minut': 1308,
 'haha awesom': 891,
 'freephon': 743,
 'repres freephon': 1740,
 'xmas': 2461,
 'radio': 1672,
 'jus': 1074,
 'sis': 1896,
 'reach home': 1694,
 'th': 2092,
 'co uk': 364,
 'touch': 2166,
 'deal': 501,
 'keep touch': 1082,
 'great week': 856,
 'cours': 444,
 'howev': 981,
 'suggest': 2026,
 'abl': 2,
 'everi': 630,
 'settl': 1861,
 'gr day': 850,
 'mrng': 1369,
 'hav': 909,
 'gud mrng': 880,
 'nice day': 1423,
 'stori': 2008,
 'person stori': 1556,
 'dead': 500,
 'tmr': 2137,
 'orchard': 1511,
 'mrt': 1370,
 'kate': 1079,
 'see tomorrow': 1827,
 'found': 722,
 'buck': 220,
 'gt buck': 865,
 'darlin': 486,
 'ive': 1045,
 'colleg': 377,
 'success': 2024,
 'decim': 507,
 'balanc': 136,
 'rs': 1777,
 'transact': 2173,
 'id': 1000,
 'lt decim': 1216,
 'decim gt': 508,
 'rs lt': 1778,
 'goodmorn': 838,
 'sleep': 1906,
 'dat': 488,
 'oso': 1517,
 'cannot': 288,
 'oredi': 1513,
 'like dat': 1161,
 'straight': 2011,
 'connect': 408,
 'bill': 166,
 'give us': 797,
 'big': 164,
 'readi': 1696,
 'get readi': 783,
 'break': 210,
 'semest': 1835,
 'hope great': 968,
 'noe': 1430,
 'leh': 1142,
 'sound': 1944,
 'head': 911,
 'slept': 1908,
 'past': 1541,
 'easi': 586,
 'sen': 1836,
 'exam': 639,
 'march': 1253,
 'atm': 107,
 'regist': 1718,
 'ok prob': 1480,
 'import': 1013,
 'file': 684,
 'system': 2050,
 'shop': 1872,
 'romant': 1767,
 'nite': 1428,
 'tc': 2063,
 'biz': 176,
 'optout': 1508,
 'gbp': 773,
 'mtmsg': 1377,
 'new mobil': 1413,
 'txt nokia': 2202,
 'appreci': 81,
 'partner': 1537,
 'career': 297,
 'star': 1977,
 'sign': 1884,
 'compani': 393,
 'bcoz': 146,
 'teach': 2065,
 'good morn': 835,
 'walk': 2318,
 'cross': 456,
 'road': 1763,
 'side': 1881,
 'street': 2012,
 'batteri': 143,
 'die': 529,
 'flirt': 708,
 'sam': 1797,
 'text meet': 2088,
 'print': 1639,
 'bus stop': 227,
 'wil': 2397,
 'argument': 88,
 'lose': 1199,
 'argu': 87,
 'kick': 1086,
 'person dont': 1555,
 'ur friend': 2243,
 'secret': 1821,
 'admir': 18,
 'reveal': 1750,
 'secret admir': 1822,
 'admir look': 19,
 'look make': 1195,
 'make contact': 1236,
 'contact find': 415,
 'find reveal': 692,
 'reveal think': 1751,
 'think ur': 2109,
 'ur special': 2258,
 'special call': 1954,
 'laptop': 1109,
 'case': 300,
 'tel': 2071,
 'meant': 1272,
 'told': 2149,
 'face': 653,
 'fr': 723,
 'thanx': 2098,
 'everyth': 635,
 'websit': 2359,
 'kalli': 1077,
 'didnt': 527,
 'goodnight': 840,
 'fix': 700,
 'wake': 2317,
 'oh ok': 1472,
 'good night': 836,
 'congratul': 406,
 'cd': 312,
 'voucher': 2309,
 'gift': 790,
 'music': 1383,
 'tncs': 2138,
 'ldew': 1130,
 'ppmx': 1623,
 'congratul ur': 407,
 'gift guarante': 791,
 'draw txt': 564,
 'txt music': 2201,
 'music tncs': 1385,
 'tncs www': 2139,
 'www ldew': 2451,
 'ldew com': 1131,
 'com win': 383,
 'win ppmx': 2402,
 'ppmx age': 1624,
 'cal': 239,
 'hold': 947,
 'bcum': 147,
 'angri': 60,
 'wid': 2392,
 'dnt': 545,
 'childish': 338,
 'true': 2184,
 'deep': 510,
 'affect': 25,
 'care': 296,
 'manda': 1246,
 'ur lovabl': 2249,
 'angri childish': 61,
 ...}

In [34]:
## Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [36]:
from sklearn.naive_bayes import MultinomialNB

In [37]:
mnb2=MultinomialNB()
mnb2.fit(X_train,y_train)

MultinomialNB()

In [38]:
## predict
y_pred=mnb2.predict(X_test)

In [39]:
## Get performance report

from sklearn.metrics import accuracy_score,classification_report
accuracy_score(y_test,y_pred)

0.9829596412556054

In [40]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       966
           1       0.99      0.88      0.93       149

    accuracy                           0.98      1115
   macro avg       0.99      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115

## Best Practices for Training

Our Initial Practice:
1. Preprocessing and Cleaning
2. BOW and TF-IDF (sentences---->vectors)
3. Train Test Split
4. Trained our model

Please note. We are supposed to split the text data before BOW and TF-IDF vectorizing because to avoid data leakage

**`The Best Practice:`**
1. Preprocessing and Cleaning
2. Train Test Split
3. BOW and TF-IDF (sentences---->vectors)
4. Trained our model

**Ensure to make the corrections below!!**

In [ ]:
## Start correction here

## Vectorize (Word2Vec)

In [41]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [43]:
import gensim.downloader as api

wv=api.load('word2vec-google-news-300')
vec_king=wv['king']

In [44]:
vec_king

array([0.126, 0.0298, 0.00861, 0.14, -0.0256, -0.0361, 0.112, -0.198, 0.0513, 0.363, -0.242, -0.303, -0.178, -0.0249, -0.168, -0.17, 0.0347, 0.00522, 0.0464, 0.129, 0.137, 0.113, 0.0596, 0.137, 0.101, -0.177, -0.252, 0.0598, 0.342, -0.0311, 0.104, 0.0618, 0.125, 0.4, -0.322, 0.084, 0.0391, 0.00586, 0.0703, 0.173, 0.139, -0.231, 0.283, 0.143, 0.342, -0.0239, -0.11, 0.0332, -0.0547, 0.0153, -0.162, 0.158, -0.26, 0.0201, -0.163, 0.00136, -0.145, -0.0569, 0.043, -0.0247, 0.186, 0.447, 0.00958, 0.132, 0.0986, -0.186, -0.1, -0.134, -0.125, 0.283, 0.123, 0.0532, -0.178, 0.0859, -0.0219, 0.0205, -0.14, 0.0251, 0.139, -0.105, 0.139, 0.0889, -0.0752, -0.0214, 0.173, 0.0464, -0.266, 0.00891, 0.149, 0.0378, 0.238, -0.125, -0.218, -0.182, 0.0298, 0.0571, -0.0289, 0.0125, 0.0967, -0.231, 0.0581, 0.0669, 0.0708, -0.309, -0.215, 0.146, -0.428, -0.0094, 0.154, -0.0767, 0.289, 0.277, -0.000486, -0.137, 0.324, -0.246, -0.00304, -0.212, 0.125, 0.27, 0.204, 0.0825, -0.201, -0.16, -0.0378, -0.12, 0.115, -0.041, -0.0396, -0.0898, 0.00635, 0.203, 0.187, 0.273, 0.063, 0.142, -0.0981, 0.139, 0.183, 0.174, 0.174, -0.237, 0.179, 0.0635, 0.236, -0.209, 0.0874, -0.166, -0.0791, 0.243, -0.0889, 0.127, -0.217, -0.174, -0.359, -0.0825, -0.0649, 0.0508, 0.136, -0.0747, -0.164, 0.0115, 0.445, -0.216, -0.111, -0.192, 0.171, -0.125, 0.00266, 0.192, -0.175, 0.14, 0.293, 0.113, 0.0596, -0.064, 0.0996, -0.0272, 0.0197, 0.0427, -0.246, 0.064, -0.226, -0.169, 0.0029, 0.082, 0.342, 0.0432, 0.133, 0.143, 0.0762, 0.0598, -0.119, 0.00275, -0.063, -0.0272, -0.00482, -0.082, -0.0249, -0.4, -0.107, 0.0425, 0.0776, -0.117, 0.0737, -0.0923, 0.108, 0.158, 0.0425, 0.127, 0.0361, 0.268, -0.101, -0.303, -0.0576, 0.0505, 0.000526, -0.207, -0.139, -0.00897, -0.0278, -0.142, 0.207, -0.158, 0.128, 0.149, -0.0225, -0.0845, 0.123, 0.216, -0.214, -0.312, -0.373, 0.00409, 0.107, 0.107, 0.0732, 0.00897, -0.0388, -0.13, 0.149, -0.215, -0.00184, 0.0991, 0.157, -0.114, -0.205, 0.0991, 0.369, -0.197, 0.0354, 0.109, 0.132, 0.167, 0.235, 0.105, -0.496, -0.164, -0.156, -0.0522, 0.103, 0.243, -0.188, 0.0508, -0.0938, -0.0669, 0.0227, 0.0762, 0.289, 0.311, -0.0537, 0.229, 0.0251, 0.0679, -0.121, -0.216, -0.273, -0.0308, -0.338, 0.153, 0.233, -0.208, 0.373, 0.082, 0.252, -0.0762, -0.0466, -0.0223, 0.0299, -0.0593, -0.00467, -0.244, -0.21, -0.287, -0.0454, -0.178, -0.279, -0.0859, 0.0913, 0.252], dtype=float32)

Now we are going to build our own word2vec from scratch with the spam dataset.

In [46]:
import pandas as pd
messages=pd.read_csv("SMSSpamCollection.txt", sep='\t', names=['label','message'])

In [47]:
from nltk.stem import WordNetLemmatizer

In [48]:
lemmatizer=WordNetLemmatizer()

In [49]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()

    # review=[lemmatizer.lemmatize(word) for word in review if word not in stopwords.words('english')]
    ## we will not filter out the stop words here. Let the lemmatizer do its job
    review=[lemmatizer.lemmatize(word) for word in review] ## The lemmatizer will stem/root the words including stop words
    review=' '.join(review)
    corpus.append(review)

Lets check out other processes to handle what we have just don above

In [52]:
from nltk import sent_tokenize ## Tokenize paragraphs to sentences
from gensim.utils import simple_preprocess ## Convert a document into a list of lowercase tokens, ignoring tokens that are too short or too long.

In [53]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [54]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'speak',
  'with',
  'me',
  'they',
  'treat',
  'me',
  'like',
  'aid',
  'patent'],
 ['per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'ha',
  'been',
  'set',
  'your',
  'callertune',
  'for',
  'all',
  'caller',
  'press',
  'to',
  'copy',
  'your',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'you',
  'have',
  'been',
  'selected',
  'to',
  'receivea',
  'prize',
  'reward',
  'to',
  'claim',
  'call',
  'claim',
  'code',
  'kl',
  'valid',
  'hour',
  'only'],
 ['had',
  'your',
  'mobile',
  'month',
  'or',
  'more',
  'entitled',
  'to',
  'update',
  'to',
  'the',
  'latest',
  'colour',
  'mobile',
  'with',
  'camera',
  'for',
  'free',
  'call',
  'the',
  'mobile',
  'update',
  'co',
  'free',
  'on'],
 ['gonna',
  'be',
  'home',
  'soon',
  'and',
  'don',
  'want',
  'to',
  'talk',
  'about',
  'this',
  'stuff',
  'anymore',
  'tonight',
  've',
  'cried',
  'enough',
  'today'],
 ['six',
  'chance',
  'to',
  'win',
  'cash',
  'from',
  'to',
  'pound',
  'txt',
  'csh',
  'and',
  'send',
  'to',
  'cost',
  'day',
  'day',
  'tsandcs',
  'apply',
  'reply',
  'hl',
  'info'],
 ['urgent',
  'you',
  'have',
  'won',
  'week',
  'free',
  'membership',
  'in',
  'our',
  'prize',
  'jackpot',
  'txt',
  'the',
  'word',
  'claim',
  'to',
  'no',
  'www',
  'dbuk',
  'net',
  'lccltd',
  'pobox',
  'ldnw',
  'rw'],
 ['ve',
  'been',
  'searching',
  'for',
  'the',
  'right',
  'word',
  'to',
  'thank',
  'you',
  'for',
  'this',
  'breather',
  'promise',
  'wont',
  'take',
  'your',
  'help',
  'for',
  'granted',
  'and',
  'will',
  'fulfil',
  'my',
  'promise',
  'you',
  'have',
  'been',
  'wonderful',
  'and',
  'blessing',
  'at',
  'all',
  'time'],
 ['have', 'date', 'on', 'sunday', 'with', 'will'],
 ['to',
  'use',
  'your',
  'credit',
  'click',
  'the',
  'wap',
  'link',
  'in',
  'the',
  'next',
  'txt',
  'message',
  'or',
  'click',
  'here',
  'http',
  'wap',
  'com',
  'qjkgighjjgcbl'],
 ['oh', 'watching', 'here'],
 ['eh',
  'remember',
  'how',
  'spell',
  'his',
  'name',
  'yes',
  'did',
  'he',
  'naughty',
  'make',
  'until',
  'wet'],
 ['fine',
  'if',
  'that',
  'the',
  'way',
  'feel',
  'that',
  'the',
  'way',
  'it',
  'gota'],
 ['england',
  'macedonia',
  'dont',
  'miss',
  'the',
  'goal',
  'team',
  'news',
  'txt',
  'ur',
  'national',
  'team',
  'to',
  'eg',
  'england',
  'to',
  'try',
  'wale',
  'scotland',
  'txt',
  'poboxox',
  'wq'],
 ['is', 'that', 'seriously', 'how', 'you', 'spell', 'his', 'name'],
 ['going', 'to', 'try', 'for', 'month', 'ha', 'ha', 'only', 'joking'],
 ['so', 'pay', 'first', 'lar', 'then', 'when', 'is', 'da', 'stock', 'comin'],
 ['aft',
  'finish',
  'my',
  'lunch',
  'then',
  'go',
  'str',
  'down',
  'lor',
  'ard',
  'smth',
  'lor',
  'finish',
  'ur',
  'lunch',
  'already'],
 ['ffffffffff',
  'alright',
  'no',
  'way',
  'can',
  'meet',
  'up',
  'with',
  'you',
  'sooner'],
 ['just',
  'forced',
  'myself',
  'to',
  'eat',
  'slice',
  'really',
  'not',
  'hungry',
  'tho',
  'this',
  'suck',
  'mark',
  'is',
  'getting',
  'worried',
  'he',
  'know',
  'sick',
  'when',
  'turn',
  'down',
  'pizza',
  'lol'],
 ['lol', 'your', 'always', 'so', 'convincing'],
 ['did',
  'you',
  'catch',
  'the',
  'bus',
  'are',
  'you',
  'frying',
  'an',
  'egg',
  'did',
  'you',
  'make',
  'tea',
  'are',
  'you',
  'eating',
  'your',
  'mom',
  'left',
  'over',
  'dinner',
  'do',
  'you',
  'feel',
  'my',
  'love'],
 ['back',
  'amp',
  'we',
  're',
  'packing',
  'the',
  'car',
  'now',
  'll',
  'let',
  'you',
  'know',
  'if',
  'there',
  'room'],
 ['ahhh',
  'work',
  'vaguely',
  'remember',
  'that',
  'what',
  'doe',
  'it',
  'feel',
  'like',
  'lol'],
 ['wait',
  'that',
  'still',
  'not',
  'all',
  'that',
  'clear',
  'were',
  'you',
  'not',
  'sure',
  'about',
  'me',
  'being',
  'sarcastic',
  'or',
  'that',
  'that',
  'why',
  'doesn',
  'want',
  'to',
  'live',
  'with'],
 ['yeah',
  'he',
  'got',
  'in',
  'at',
  'and',
  'wa',
  'apologetic',
  'had',
  'fallen',
  'out',
  'and',
  'she',
  'wa',
  'actin',
  'like',
  'spoilt',
  'child',
  'and',
  'he',
  'got',
  'caught',
  'up',
  'in',
  'that',
  'till',
  'but',
  'we',
  'won',
  'go',
  'there',
  'not',
  'doing',
  'too',
  'badly',
  'cheer',
  'you'],
 ['tell', 'me', 'anything', 'about', 'you'],
 ['for',
  'fear',
  'of',
  'fainting',
  'with',
  'the',
  'of',
  'all',
  'that',
  'housework',
  'you',
  'just',
  'did',
  'quick',
  'have',
  'cuppa'],
 ['thanks',
  'for',
  'your',
  'subscription',
  'to',
  'ringtone',
  'uk',
  'your',
  'mobile',
  'will',
  'be',
  'charged',
  'month',
  'please',
  'confirm',
  'by',
  'replying',
  'yes',
  'or',
  'no',
  'if',
  'you',
  'reply',
  'no',
  'you',
  'will',
  'not',
  'be',
  'charged'],
 ['yup',
  'ok',
  'go',
  'home',
  'look',
  'at',
  'the',
  'timing',
  'then',
  'msg',
  'again',
  'xuhui',
  'going',
  'to',
  'learn',
  'on',
  'nd',
  'may',
  'too',
  'but',
  'her',
  'lesson',
  'is',
  'at',
  'am'],
 ['oops', 'll', 'let', 'you', 'know', 'when', 'my', 'roommate', 'done'],
 ['see', 'the', 'letter', 'on', 'my', 'car'],
 ['anything', 'lor', 'decide'],
 ['hello',
  'how',
  'you',
  'and',
  'how',
  'did',
  'saturday',
  'go',
  'wa',
  'just',
  'texting',
  'to',
  'see',
  'if',
  'you',
  'decided',
  'to',
  'do',
  'anything',
  'tomo',
  'not',
  'that',
  'trying',
  'to',
  'invite',
  'myself',
  'or',
  'anything'],
 ['pls',
  'go',
  'ahead',
  'with',
  'watt',
  'just',
  'wanted',
  'to',
  'be',
  'sure',
  'do',
  'have',
  'great',
  'weekend',
  'abiola'],
 ['did',
  'forget',
  'to',
  'tell',
  'you',
  'want',
  'you',
  'need',
  'you',
  'crave',
  'you',
  'but',
  'most',
  'of',
  'all',
  'love',
  'you',
  'my',
  'sweet',
  'arabian',
  'steed',
  'mmmmmm',
  'yummy'],
 ['rodger',
  'burn',
  'msg',
  'we',
  'tried',
  'to',
  'call',
  'you',
  're',
  'your',
  'reply',
  'to',
  'our',
  'sm',
  'for',
  'free',
  'nokia',
  'mobile',
  'free',
  'camcorder',
  'please',
  'call',
  'now',
  'for',
  'delivery',
  'tomorrow'],
 ['who', 'are', 'you', 'seeing'],
 ['great',
  'hope',
  'you',
  'like',
  'your',
  'man',
  'well',
  'endowed',
  'am',
  'lt',
  'gt',
  'inch'],
 ['no', 'call', 'message', 'missed', 'call'],
 ['didn', 'you', 'get', 'hep', 'immunisation', 'in', 'nigeria'],
 ['fair', 'enough', 'anything', 'going', 'on'],
 ['yeah',
  'hopefully',
  'if',
  'tyler',
  'can',
  'do',
  'it',
  'could',
  'maybe',
  'ask',
  'around',
  'bit'],
 ['don',
  'know',
  'how',
  'stubborn',
  'am',
  'didn',
  'even',
  'want',
  'to',
  'go',
  'to',
  'the',
  'hospital',
  'kept',
  'telling',
  'mark',
  'not',
  'weak',
  'sucker',
  'hospital',
  'are',
  'for',
  'weak',
  'sucker'],
 ['what',
  'you',
  'thinked',
  'about',
  'me',
  'first',
  'time',
  'you',
  'saw',
  'me',
  'in',
  'class'],
 ['gram',
  'usually',
  'run',
  'like',
  'lt',
  'gt',
  'half',
  'eighth',
  'is',
  'smarter',
  'though',
  'and',
  'get',
  'you',
  'almost',
  'whole',
  'second',
  'gram',
  'for',
  'lt',
  'gt'],
 ['fyi',
  'ha',
  'ride',
  'early',
  'tomorrow',
  'morning',
  'but',
  'he',
  'crashing',
  'at',
  'our',
  'place',
  'tonight'],
 ['wow',
  'never',
  'realized',
  'that',
  'you',
  'were',
  'so',
  'embarassed',
  'by',
  'your',
  'accomodations',
  'thought',
  'you',
  'liked',
  'it',
  'since',
  'wa',
  'doing',
  'the',
  'best',
  'could',
  'and',
  'you',
  'always',
  'seemed',
  'so',
  'happy',
  'about',
  'the',
  'cave',
  'sorry',
  'didn',
  'and',
  'don',
  'have',
  'more',
  'to',
  'give',
  'sorry',
  'offered',
  'sorry',
  'your',
  'room',
  'wa',
  'so',
  'embarassing'],
 ['sm',
  'ac',
  'sptv',
  'the',
  'new',
  'jersey',
  'devil',
  'and',
  'the',
  'detroit',
  'red',
  'wing',
  'play',
  'ice',
  'hockey',
  'correct',
  'or',
  'incorrect',
  'end',
  'reply',
  'end',
  'sptv'],
 ['do',
  'you',
  'know',
  'what',
  'mallika',
  'sherawat',
  'did',
  'yesterday',
  'find',
  'out',
  'now',
  'lt',
  'url',
  'gt'],
 ['congrats',
  'year',
  'special',
  'cinema',
  'pas',
  'for',
  'is',
  'yours',
  'call',
  'now',
  'suprman',
  'matrix',
  'starwars',
  'etc',
  'all',
  'free',
  'bx',
  'ip',
  'we',
  'pm',
  'dont',
  'miss',
  'out'],
 ['sorry', 'll', 'call', 'later', 'in', 'meeting'],
 ['tell', 'where', 'you', 'reached'],
 ['yes', 'gauti', 'and', 'sehwag', 'out', 'of', 'odi', 'series'],
 ['your',
  'gonna',
  'have',
  'to',
  'pick',
  'up',
  'burger',
  'for',
  'yourself',
  'on',
  'your',
  'way',
  'home',
  'can',
  'even',
  'move',
  'pain',
  'is',
  'killing',
  'me'],
 ['ha', 'ha', 'ha', 'good', 'joke', 'girl', 'are', 'situation', 'seeker'],
 ['it', 'part', 'of', 'checking', 'iq'],
 ['sorry',
  'my',
  'roommate',
  'took',
  'forever',
  'it',
  'ok',
  'if',
  'come',
  'by',
  'now'],
 ['ok',
  'lar',
  'double',
  'check',
  'wif',
  'da',
  'hair',
  'dresser',
  'already',
  'he',
  'said',
  'wun',
  'cut',
  'short',
  'he',
  'said',
  'will',
  'cut',
  'until',
  'look',
  'nice'],
 ['valued',
  'customer',
  'am',
  'pleased',
  'to',
  'advise',
  'you',
  'that',
  'following',
  'recent',
  'review',
  'of',
  'your',
  'mob',
  'no',
  'you',
  'are',
  'awarded',
  'with',
  'bonus',
  'prize',
  'call'],
 ['today',
  'is',
  'song',
  'dedicated',
  'day',
  'which',
  'song',
  'will',
  'dedicate',
  'for',
  'me',
  'send',
  'this',
  'to',
  'all',
  'ur',
  'valuable',
  'frnds',
  'but',
  'first',
  'rply',
  'me'],
 ['urgent',
  'ur',
  'awarded',
  'complimentary',
  'trip',
  'to',
  'eurodisinc',
  'trav',
  'aco',
  'entry',
  'or',
  'to',
  'claim',
  'txt',
  'dis',
  'to',
  'morefrmmob',
  'aj'],
 ['did',
  'you',
  'hear',
  'about',
  'the',
  'new',
  'divorce',
  'barbie',
  'it',
  'come',
  'with',
  'all',
  'of',
  'ken',
  'stuff'],
 ['plane', 'to', 'give', 'on', 'this', 'month', 'end'],
 ['wah', 'lucky', 'man', 'then', 'can', 'save', 'money', 'hee'],
 ['finished', 'class', 'where', 'are', 'you'],
 ['hi', 'babe', 'im', 'at', 'home', 'now', 'wanna', 'do', 'something', 'xx'],
 ['where', 'are', 'you', 'how', 'did', 'you', 'performed'],
 ['can', 'call', 'me', 'now'],
 ['am', 'waiting', 'machan', 'call', 'me', 'once', 'you', 'free'],
 ['thats',
  'cool',
  'am',
  'gentleman',
  'and',
  'will',
  'treat',
  'you',
  'with',
  'dignity',
  'and',
  'respect'],
 ['like', 'you', 'people', 'very', 'much', 'but', 'am', 'very', 'shy', 'pa'],
 ['doe', 'not', 'operate', 'after', 'lt', 'gt', 'or', 'what'],
 ['it',
  'not',
  'the',
  'same',
  'here',
  'still',
  'looking',
  'for',
  'job',
  'how',
  'much',
  'do',
  'ta',
  'earn',
  'there'],
 ['sorry', 'll', 'call', 'later'],
 ['did', 'you', 'call', 'me', 'just', 'now', 'ah'],
 ['ok', 'am', 'on', 'the', 'way', 'to', 'home', 'hi', 'hi'],
 ['you', 'will', 'be', 'in', 'the', 'place', 'of', 'that', 'man'],
 ['yup', 'next', 'stop'],
 ['call', 'you', 'later', 'don', 'have', 'network', 'if', 'urgnt', 'sm', 'me'],
 ['for',
  'real',
  'when',
  'getting',
  'on',
  'yo',
  'only',
  'need',
  'more',
  'ticket',
  'and',
  'one',
  'more',
  'jacket',
  'and',
  'done',
  'already',
  'used',
  'all',
  'my',
  'multis'],
 ['yes',
  'started',
  'to',
  'send',
  'request',
  'to',
  'make',
  'it',
  'but',
  'pain',
  'came',
  'back',
  'so',
  'back',
  'in',
  'bed',
  'double',
  'coin',
  'at',
  'the',
  'factory',
  'too',
  'gotta',
  'cash',
  'in',
  'all',
  'my',
  'nitros'],
 ['really', 'not', 'up', 'to', 'it', 'still', 'tonight', 'babe'],
 ['ela', 'kano', 'il', 'download', 'come', 'wen', 'ur', 'free'],
 ['yeah',
  'do',
  'don',
  'stand',
  'to',
  'close',
  'tho',
  'you',
  'll',
  'catch',
  'something'],
 ['sorry',
  'to',
  'be',
  'pain',
  'is',
  'it',
  'ok',
  'if',
  'we',
  'meet',
  'another',
  'night',
  'spent',
  'late',
  'afternoon',
  'in',
  'casualty',
  'and',
  'that',
  'mean',
  'haven',
  'done',
  'any',
  'of',
  'stuff',
  'moro',
  'and',
  'that',
  'includes',
  'all',
  'my',
  'time',
  'sheet',
  'and',
  'that',
  'sorry'],
 ['smile',
  'in',
  'pleasure',
  'smile',
  'in',
  'pain',
  'smile',
  'when',
  'trouble',
  'pours',
  'like',
  'rain',
  'smile',
  'when',
  'sum',
  'hurt',
  'smile',
  'becoz',
  'someone',
  'still',
  'love',
  'to',
  'see',
  'smiling'],
 ['please',
  'call',
  'our',
  'customer',
  'service',
  'representative',
  'on',
  'between',
  'am',
  'pm',
  'you',
  'have',
  'won',
  'guaranteed',
  'cash',
  'or',
  'prize'],
 ['havent',
  'planning',
  'to',
  'buy',
  'later',
  'check',
  'already',
  'lido',
  'only',
  'got',
  'show',
  'in',
  'afternoon',
  'finish',
  'work',
  'already'],
 ['your',
  'free',
  'ringtone',
  'is',
  'waiting',
  'to',
  'be',
  'collected',
  'simply',
  'text',
  'the',
  'password',
  'mix',
  'to',
  'to',
  'verify',
  'get',
  'usher',
  'and',
  'britney',
  'fml',
  'po',
  'box',
  'mk',
  'ppw'],
 ['watching', 'telugu', 'movie', 'wat', 'abt'],
 ['see',
  'when',
  'we',
  'finish',
  'we',
  'have',
  'load',
  'of',
  'loan',
  'to',
  'pay'],
 ['hi',
  'wk',
  'been',
  'ok',
  'on',
  'hols',
  'now',
  'yes',
  'on',
  'for',
  'bit',
  'of',
  'run',
  'forgot',
  'that',
  'have',
  'hairdresser',
  'appointment',
  'at',
  'four',
  'so',
  'need',
  'to',
  'get',
  'home',
  'shower',
  'beforehand',
  'doe',
  'that',
  'cause',
  'prob',
  'for'],
 ['see', 'cup', 'of', 'coffee', 'animation'],
 ['please',
  'don',
  'text',
  'me',
  'anymore',
  'have',
  'nothing',
  'else',
  'to',
  'say'],
 ['okay',
  'name',
  'ur',
  'price',
  'long',
  'it',
  'legal',
  'wen',
  'can',
  'pick',
  'them',
  'up',
  'ave',
  'am',
  'xx'],
 ['still',
  'looking',
  'for',
  'car',
  'to',
  'buy',
  'and',
  'have',
  'not',
  'gone',
  'the',
  'driving',
  'test',
  'yet'],
 ['per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'ha',
  'been',
  'set',
  'your',
  'callertune',
  'for',
  'all',
  'caller',
  'press',
  'to',
  'copy',
  'your',
  'friend',
  'callertune'],
 ['wow',
  'you',
  're',
  'right',
  'didn',
  'mean',
  'to',
  'do',
  'that',
  'guess',
  'once',
  'gave',
  'up',
  'on',
  'boston',
  'men',
  'and',
  'changed',
  'my',
  'search',
  'location',
  'to',
  'nyc',
  'something',
  'changed',
  'cuz',
  'on',
  'my',
  'signin',
  'page',
  'it',
  'still',
  'say',
  'boston'],
 ['umma', 'my', 'life', 'and', 'vava', 'umma', 'love', 'you', 'lot', 'dear'],
 ['thanks',
  'lot',
  'for',
  'your',
  'wish',
  'on',
  'my',
  'birthday',
  'thanks',
  'you',
  'for',
  'making',
  'my',
  'birthday',
  'truly',
  'memorable'],
 ['aight', 'll', 'hit', 'you', 'up', 'when', 'get', 'some', 'cash'],
 ['how',
  'would',
  'my',
  'ip',
  'address',
  'test',
  'that',
  'considering',
  'my',
  'computer',
  'isn',
  'minecraft',
  'server'],
 ['know',
  'grumpy',
  'old',
  'people',
  'my',
  'mom',
  'wa',
  'like',
  'you',
  'better',
  'not',
  'be',
  'lying',
  'then',
  'again',
  'am',
  'always',
  'the',
  'one',
  'to',
  'play',
  'joke'],
 ['dont', 'worry', 'guess', 'he', 'busy'],
 ['what', 'is', 'the', 'plural', 'of', 'the', 'noun', 'research'],
 ['going', 'for', 'dinner', 'msg', 'you', 'after'],
 ['ok',
  'wif',
  'it',
  'co',
  'like',
  'try',
  'new',
  'thing',
  'but',
  'scared',
  'dun',
  'like',
  'mah',
  'co',
  'said',
  'not',
  'too',
  'loud'],
 ['gent',
  'we',
  'are',
  'trying',
  'to',
  'contact',
  'you',
  'last',
  'weekend',
  'draw',
  'show',
  'that',
  'you',
  'won',
  'prize',
  'guaranteed',
  'call',
  'claim',
  'code',
  'valid',
  'hr',
  'only',
  'ppm'],
 ['wa',
  'ur',
  'openin',
  'sentence',
  'very',
  'formal',
  'anyway',
  'fine',
  'too',
  'juz',
  'tt',
  'eatin',
  'too',
  'much',
  'puttin',
  'on',
  'weight',
  'haha',
  'so',
  'anythin',
  'special',
  'happened'],
 ['entered',
  'my',
  'cabin',
  'my',
  'pa',
  'said',
  'happy',
  'day',
  'bos',
  'felt',
  'special',
  'she',
  'askd',
  'me',
  'lunch',
  'after',
  'lunch',
  'she',
  'invited',
  'me',
  'to',
  'her',
  'apartment',
  'we',
  'went',
  'there'],
 ['you',
  'are',
  'winner',
  'have',
  'been',
  'specially',
  'selected',
  'receive',
  'or',
  'holiday',
  'flight',
  'inc',
  'speak',
  'to',
  'live',
  'operator',
  'claim',
  'min'],
 ['goodo',
  'yes',
  'we',
  'must',
  'speak',
  'friday',
  'egg',
  'potato',
  'ratio',
  'for',
  'tortilla',
  'needed'],
 ['hmm',
  'my',
  'uncle',
  'just',
  'informed',
  'me',
  'that',
  'he',
  'paying',
  'the',
  'school',
  'directly',
  'so',
  'pls',
  'buy',
  'food'],
 ['private',
  'your',
  'account',
  'statement',
  'for',
  'show',
  'unredeemed',
  'bonus',
  'point',
  'to',
  'claim',
  'call',
  'identifier',
  'code',
  'expires'],
 ['urgent',
  'your',
  'mobile',
  'no',
  'wa',
  'awarded',
  'bonus',
  'caller',
  'prize',
  'on',
  'this',
  'is',
  'our',
  'final',
  'try',
  'to',
  'contact',
  'call',
  'from',
  'landline',
  'box',
  'wr',
  'ppm'],
 ['here',
  'is',
  'my',
  'new',
  'address',
  'apple',
  'pair',
  'all',
  'that',
  'malarky'],
 ['today',
  'voda',
  'number',
  'ending',
  'are',
  'selected',
  'to',
  'receive',
  'award',
  'if',
  'you',
  'have',
  'match',
  'please',
  'call',
  'quoting',
  'claim',
  'code',
  'standard',
  'rate',
  'app'],
 ['am',
  'going',
  'to',
  'sao',
  'mu',
  'today',
  'will',
  'be',
  'done',
  'only',
  'at'],
 ['predict', 'wat', 'time', 'll', 'finish', 'buying'],
 ['good', 'stuff', 'will', 'do'],
 ['just',
  'so',
  'that',
  'you',
  'know',
  'yetunde',
  'hasn',
  'sent',
  'money',
  'yet',
  'just',
  'sent',
  'her',
  'text',
  'not',
  'to',
  'bother',
  'sending',
  'so',
  'it',
  'over',
  'you',
  'dont',
  'have',
  'to',
  'involve',
  'yourself',
  'in',
  'anything',
  'shouldn',
  'have',
  'imposed',
  'anything',
  'on',
  'you',
  'in',
  'the',
  'first',
  'place',
  'so',
  'for',
  'that',
  'apologise'],
 ['are', 'you', 'there', 'in', 'room'],
 ['hey',
  'girl',
  'how',
  'hope',
  'well',
  'me',
  'an',
  'del',
  'bak',
  'again',
  'long',
  'time',
  'no',
  'give',
  'me',
  'call',
  'sum',
  'time',
  'from',
  'lucyxx'],
 ['how', 'much', 'doe', 'it', 'cost'],
 ['home'],
 ['dear', 'will', 'call', 'tmorrow', 'pls', 'accomodate'],
 ['first', 'answer', 'my', 'question'],
 ['sunshine',
  'quiz',
  'wkly',
  'win',
  'top',
  'sony',
  'dvd',
  'player',
  'if',
  'know',
  'which',
  'country',
  'the',
  'algarve',
  'is',
  'in',
  'txt',
  'ansr',
  'to',
  'sp',
  'tyrone'],
 ['want',
  'get',
  'laid',
  'tonight',
  'want',
  'real',
  'dogging',
  'location',
  'sent',
  'direct',
  'ur',

In [55]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile update co free on',
 'i m gonna be home soon and i don t want to talk about this stuff anymore tonight k i ve cried enough today',
 'six chance to win cash from to pound txt csh and send to cost p day day tsandcs apply reply hl info',
 'urgent you have won a week free membership in our prize jackpot txt the word claim to no t c www dbuk net lccltd pobox ldnw a rw',
 'i ve been searching for the right word to thank you for this breather i promise i wont take your help for granted and will fulfil my promise you have been wonderful and a blessing at all time',
 'i have a date on sunday with will',
 'xxxmobilemovieclub to use your credit click the wap link in the next txt message or click here http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k i m watching here',
 'eh u remember how spell his name yes i did he v naughty make until i v wet',
 'fine if that s the way u feel that s the way it gota b',
 'england v macedonia dont miss the goal team news txt ur national team to eg england to try wale scotland txt poboxox w wq',
 'is that seriously how you spell his name',
 'i m going to try for month ha ha only joking',
 'so pay first lar then when is da stock comin',
 'aft i finish my lunch then i go str down lor ard smth lor u finish ur lunch already',
 'ffffffffff alright no way i can meet up with you sooner',
 'just forced myself to eat a slice i m really not hungry tho this suck mark is getting worried he know i m sick when i turn down pizza lol',
 'lol your always so convincing',
 'did you catch the bus are you frying an egg did you make a tea are you eating your mom s left over dinner do you feel my love',
 'i m back amp we re packing the car now i ll let you know if there s room',
 'ahhh work i vaguely remember that what doe it feel like lol',
 'wait that s still not all that clear were you not sure about me being sarcastic or that that s why x doesn t want to live with u',
 'yeah he got in at and wa v apologetic n had fallen out and she wa actin like spoilt child and he got caught up in that till but we won t go there not doing too badly cheer you',
 'k tell me anything about you',
 'for fear of fainting with the of all that housework you just did quick have a cuppa',
 'thanks for your subscription to ringtone uk your mobile will be charged month please confirm by replying yes or no if you reply no you will not be charged',
 'yup ok i go home look at the timing then i msg again xuhui going to learn on nd may too but her lesson is at am',
 'oops i ll let you know when my roommate s done',
 'i see the letter b on my car',
 'anything lor u decide',
 'hello how s you and how did saturday go i wa just texting to see if you d decided to do anything tomo not that i m trying to invite myself or anything',
 'pls go ahead with watt i just wanted to be sure do have a great weekend abiola',
 'did i forget to tell you i want you i need you i crave you but most of all i love you my sweet arabian steed mmmmmm yummy',
 'rodger burn msg we tried to call you re your reply to our sm for a free nokia mobile free camcorder please call now for delivery tomorrow',
 'who are you seeing',
 'great i hope you like your man well endowed i am lt gt inch',
 'no call message missed call',
 'didn t you get hep b immunisation in nigeria',
 'fair enough anything going on',
 'yeah hopefully if tyler can t do it i could maybe ask around a bit',
 'u don t know how stubborn i am i didn t even want to go to the hospital i kept telling mark i m not a weak sucker hospital are for weak sucker',
 'what you thinked about me first time you saw me in class',
 'a gram usually run like lt gt a half eighth is smarter though and get you almost a whole second gram for lt gt',
 'k fyi x ha a ride early tomorrow morning but he s crashing at our place tonight',
 'wow i never realized that you were so embarassed by your accomodations i thought you liked it since i wa doing the best i could and you always seemed so happy about the cave i m sorry i didn t and don t have more to give i m sorry i offered i m sorry your room wa so embarassing',
 'sm ac sptv the new jersey devil and the detroit red wing play ice hockey correct or incorrect end reply end sptv',
 'do you know what mallika sherawat did yesterday find out now lt url gt',
 'congrats year special cinema pas for is yours call now c suprman v matrix starwars etc all free bx ip we pm dont miss out',
 'sorry i ll call later in meeting',
 'tell where you reached',
 'yes gauti and sehwag out of odi series',
 'your gonna have to pick up a burger for yourself on your way home i can t even move pain is killing me',
 'ha ha ha good joke girl are situation seeker',
 'it a part of checking iq',
 'sorry my roommate took forever it ok if i come by now',
 'ok lar i double check wif da hair dresser already he said wun cut v short he said will cut until i look nice',
 'a a valued customer i am pleased to advise you that following recent review of your mob no you are awarded with a bonus prize call',
 'today is song dedicated day which song will u dedicate for me send this to all ur valuable frnds but first rply me',
 'urgent ur awarded a complimentary trip to eurodisinc trav aco entry or to claim txt dis to morefrmmob shracomorsglsuplt l aj',
 'did you hear about the new divorce barbie it come with all of ken s stuff',
 'i plane to give on this month end',
 'wah lucky man then can save money hee',
 'finished class where are you',
 'hi babe im at home now wanna do something xx',
 'k k where are you how did you performed',
 'u can call me now',
 'i am waiting machan call me once you free',
 'thats cool i am a gentleman and will treat you with dignity and respect',
 'i like you people very much but am very shy pa',
 'doe not operate after lt gt or what',
 'it not the same here still looking for a job how much do ta s earn there',
 'sorry i ll call later',
 'k did you call me just now ah',
 'ok i am on the way to home hi hi',
 'you will be in the place of that man',
 'yup next stop',
 'i call you later don t have network if urgnt sm me',
 'for real when u getting on yo i only need more ticket and one more jacket and i m done i already used all my multis',
 'yes i started to send request to make it but pain came back so i m back in bed double coin at the factory too i gotta cash in all my nitros',
 'i m really not up to it still tonight babe',
 'ela kano il download come wen ur free',
 'yeah do don t stand to close tho you ll catch something',
 'sorry to be a pain is it ok if we meet another night i spent late afternoon in casualty and that mean i haven t done any of y stuff moro and that includes all my time sheet and that sorry',
 'smile in pleasure smile in pain smile when trouble pours like rain smile when sum hurt u smile becoz someone still love to see u smiling',
 'please call our customer service representative on between am pm a you have won a guaranteed cash or prize',
 'havent planning to buy later i check already lido only got show in e afternoon u finish work already',
 'your free ringtone is waiting to be collected simply text the password mix to to verify get usher and britney fml po box mk h ppw',
 'watching telugu movie wat abt u',
 'i see when we finish we have load of loan to pay',
 'hi wk been ok on hols now yes on for a bit of a run forgot that i have hairdresser appointment at four so need to get home n shower beforehand doe that cause prob for u',
 'i see a cup of coffee animation',
 'please don t text me anymore i have nothing else to say',
 'okay name ur price a long a it legal wen can i pick them up y u ave x am xx',
 'i m still looking for a car to buy and have not gone the driving test yet',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'wow you re right i didn t mean to do that i guess once i gave up on boston men and changed my search location to nyc something changed cuz on my signin page it still say boston',
 'umma my life and vava umma love you lot dear',
 'thanks a lot for your wish on my birthday thanks you for making my birthday truly memorable',
 'aight i ll hit you up when i get some cash',
 'how would my ip address test that considering my computer isn t a minecraft server',
 'i know grumpy old people my mom wa like you better not be lying then again i am always the one to play joke',
 'dont worry i guess he s busy',
 'what is the plural of the noun research',
 'going for dinner msg you after',
 'i m ok wif it co i like try new thing but i scared u dun like mah co u said not too loud',
 'gent we are trying to contact you last weekend draw show that you won a prize guaranteed call claim code k valid hr only ppm',
 'wa ur openin sentence very formal anyway i m fine too juz tt i m eatin too much n puttin on weight haha so anythin special happened',
 'a i entered my cabin my pa said happy b day bos i felt special she askd me lunch after lunch she invited me to her apartment we went there',
 'you are a winner u have been specially selected receive or a holiday flight inc speak to a live operator claim p min',
 'goodo yes we must speak friday egg potato ratio for tortilla needed',
 'hmm my uncle just informed me that he s paying the school directly so pls buy food',
 'private your account statement for show unredeemed bonus point to claim call identifier code expires',
 'urgent your mobile no wa awarded bonus caller prize on this is our final try to contact u call from landline box wr c ppm',
 'here is my new address apple pair all that malarky',
 'today voda number ending are selected to receive a award if you have a match please call quoting claim code standard rate app',
 'i am going to sao mu today will be done only at',
 'predict wat time ll finish buying',
 'good stuff will do',
 'just so that you know yetunde hasn t sent money yet i just sent her a text not to bother sending so it over you dont have to involve yourself in anything i shouldn t have imposed anything on you in the first place so for that i apologise',
 'are you there in room',
 'hey girl how r u hope u r well me an del r bak again long time no c give me a call sum time from lucyxx',
 'k k how much doe it cost',
 'i m home',
 'dear will call tmorrow pls accomodate',
 'first answer my question',
 'sunshine quiz wkly q win a top sony dvd player if u know which country the algarve is in txt ansr to sp tyrone',
 'want get laid tonight want real dogging location sent direct ur mob join the uk s largest dogging network bt txting gravel to nt ec a p msg p',
 'i only haf msn it s yijue hotmail com',
 'he is there you call and meet him',
 'no no i will check all room befor activity',
 'you ll not rcv any more msg from the chat svc for free hardcore service text go to if u get nothing u must age verify with yr network try again',
 'got c i lazy to type i forgot in lect i saw a pouch but like not v nice',
 'k text me when you re on the way',
 'sir waiting for your mail',
 'a swt thought nver get tired of doing little thing lovable person coz somtimes those little thing occupy d biggest part in their heart gud ni',
 'i know you are can you pls open the back',
 'yes see ya not on the dot',
 'whats the staff name who is taking class for u',
 'freemsg why haven t you replied to my text i m randy sexy female and live local luv to hear from u netcollex ltd p per msg reply stop to end',
 'ummma will call after check in our life will begin from qatar so pls pray very hard',
 'k i deleted my contact that why',
 'sindu got job in birla soft',
 'the wine is flowing and i m i have nevering',
 'yup i thk cine is better co no need go down plaza mah',
 'ok ur typical reply',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'you are everywhere dirt on the floor the window even on my shirt and sometimes when i open my mouth you are all that come flowing out i dream of my world without you then half my chore are out too a time of joy for me lot of tv show i ll see but i guess like all thing you just must exist like rain hail and mist and when my time here is done you and i become one',
 'aaooooright are you at work',
 'i m leaving my house now',
 'hello my love what are you doing did you get to that interview today are you you happy are you being a good boy do you think of me are you missing me',
 'customer service annoncement you have a new year delivery waiting for you please call now to arrange delivery',
 'you are a winner u have been specially selected receive cash or a holiday flight inc speak to a live operator claim',
 'keep yourself safe for me because i need you and i miss you already and i envy everyone that see s you in real life',
 'new car and house for my parent i have only new job in hand',
 'i m so in love with you i m excited each day i spend with you you make me so happy',
 'pls stop bootydelious f is inviting you to be her friend reply yes or no see her www sm ac u bootydelious stop send stop frnd to',
 'bangbabes ur order is on the way u should receive a service msg download ur content if u do not goto wap bangb tv on ur mobile internet service menu',
 'i place all ur point on e culture module already',
 'urgent we are trying to contact you last weekend draw show that you have won a prize guaranteed call claim code s valid hr only',
 'hi frnd which is best way to avoid missunderstding wit our beloved one s',
 'great escape i fancy the bridge but need her lager see you tomo',
 'yes it completely in out of form clark also utter waste',
 'sir i need axis bank account no and bank address',
 'hmmm thk sure got time to hop ard ya can go free abt muz call u to discus liao',
 'what time you coming down later',
 'bloody hell cant believe you forgot my surname mr ill give u a clue it spanish and begin with m',
 'well i m gonna finish my bath now have a good fine night',
 'let me know when you ve got the money so carlos can make the call',
 'u still going to the mall',
 'turn out my friend are staying for the whole show and won t be back til lt gt so feel free to go ahead and smoke that lt gt worth',
 'text her if she doesnt reply let me know so i can have her log in',
 'hi you just spoke to maneesha v we d like to know if you were satisfied with the experience reply toll free with yes or no',
 'you lifted my hope with the offer of money i am in need especially when the end of the month approach and it hurt my studying anyways have a gr weekend',
 'lol no u can trust me',
 'ok i am a gentleman and will treat you with dignity and respect',
 'he will you guy close',
 'going on nothing great bye',
 'hello handsome are you finding that job not being lazy working towards getting back that net for mummy where s my boytoy now doe he miss me',
 'haha awesome be there in a minute',
 'please call our customer service representative on freephone between am pm a you have won a guaranteed cash or prize',
 'have you got xmas radio time if not i will get it now',
 'i jus reached home i go bathe first but my si using net tell u when she finish k',
 'are you unique enough find out from th august www areyouunique co uk',
 'i m sorry i ve joined the league of people that dont keep in touch you mean a great deal to me you have been a friend at all time even at great personal cost do have a great week',
 'hi finally i completed the course',
 'it will stop on itself i however suggest she stay with someone that will be able to give or for every stool',
 'how are you doing hope you ve settled in for the new school year just wishin you a gr day',
 'gud mrng dear hav a nice day',
 'did u got that person story',
 'is your hamster dead hey so tmr i meet you at pm orchard mrt',
 'hi it kate how is your evening i hope i can see you tomorrow for a bit but i have to bloody babyjontet txt back if u can xxx',
 'found it enc lt gt where you at',
 'i sent you lt gt buck',
 'hello darlin ive finished college now so txt me when u finish if u can love kate xxx',
 'your account ha been refilled successfully by inr lt decimal gt your keralacircle prepaid account balance is r lt decimal gt your transaction id is kr lt gt',
 'goodmorning sleeping ga',
 'u call me alter at ok',
 'say until like dat i dun buy ericsson oso cannot oredi lar',
 'a i entered my cabin my pa said happy b day bos i felt special she askd me lunch after lunch she invited me to her apartment we went there',
 'aight yo dat straight dogg',
 'you please give u connection today itself before lt decimal gt or refund the bill',
 'both i shoot big load so get ready',
 'what s up bruv hope you had a great break do have a rewarding semester',
 'home so we can always chat',
 'k k good study well',
 'yup how noe leh',
 'sound great are you home now',
 'finally the match heading towards draw a your prediction',
 'tired i haven t slept well the past few night',
 'easy ah sen got selected mean it good',
 'i have to take exam with march',
 'yeah you should i think you can use your gt atm now to register not sure but if there s anyway i can help let me know but when you do be sure you are ready',
 'ok no prob take ur time',
 'there is o called ubandu which will run without installing in hard disk you can use that o to copy the important file in system and give it to repair shop',
 'sorry i ll call later',
 'u say leh of course nothing happen lar not say v romantic jus a bit only lor i thk e nite scenery not so nice leh',
 'new mobile from must go txt nokia to no collect yours today from only www tc biz optout gbp mtmsg',
 'would really appreciate if you call me just need someone to talk to',
 'will u meet ur dream partner soon is ur career off a flyng start find out free txt horo followed by ur star sign e g horo aries',
 'hey company elama po mudyadhu',
 'life is more strict than teacher bcoz teacher teach lesson amp then conduct exam but life first conduct exam amp then teach lesson happy morning',
 'dear good morning now only i am up',
 'get down in gandhipuram and walk to cross cut road right side lt gt street road and turn at first right',
 'dear we are going to our rubber place',
 'sorry battery died yeah i m here',
 'yes here tv is always available in work place',
 'text meet someone sexy today u can find a date or even flirt it up to u join just p reply with name age eg sam msg recd thirtyeight penny',
 'i have printed it oh so lt gt come upstairs',
 'or ill be a little closer like at the bus stop on the same street',
 'where are you when wil you reach here',
 'new theory argument win d situation but loses the person so dont argue with ur friend just kick them amp say i m always correct',
 'u have a secret admirer who is looking make contact with u find out who they r reveal who think ur so special call on',
 'tomarrow final hearing on my laptop case so i cant',
 'pleassssssseeeeee tel me v avent done sportsx',
 'okay no no just shining on that wa meant to be signing but that sound better',

You can see that they are both almost the same. So any of the methods applied can help with developing our corpus.

In [56]:
## Lets train word2vec from scratch. Rather than using google pretrained word2vec model
import gensim
w2v_model=gensim.models.Word2Vec(
    sentences=words,
    vector_size=100, ## recall google used 300. 100 is default
)

In [58]:
## To get all the vocabulary
w2v_model.wv.index_to_key

['to',
 'you',
 'the',
 'it',
 'and',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'will',
 'if',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'home',
 'she',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'hi',
 'phone',
 'they',
 'new',
 'please',
 'later',
 'pls',
 'any',
 'her',
 'ha',
 'co',
 'did',
 'been',
 'msg',
 'min',
 'some',
 'an',
 'night',
 'make',
 'dear',
 'who',
 'here',
 'message',
 'say',
 'well',
 'where',
 're',
 'thing',
 'much',
 'oh',
 'great',
 'claim',
 'hope',
 'hey',
 'him',
 'number',
 'give',
 'more',
 'too',
 'happy',
 'work',
 'wat',
 'friend',
 'had',
 'yes',
 'way',
 'www',
 've',
 'let',
 'should',
 'prize',
 'won',
 'right',
 'tomorrow',
 'already',
 'tone',
 'after',
 'ask',
 'win',
 'said',
 'life',
 'amp',
 'cash',
 'doing',
 'im',
 'yeah',
 'really',
 'meet',
 'babe',
 'why',
 'find',
 'them',
 'miss',
 'morning',
 'very',
 'last',
 'year',
 'service',
 'thanks',
 'uk',
 'care',
 'com',
 'would',
 'anything',
 'lol',
 'nokia',
 'also',
 'every',
 'feel',
 'keep',
 'sure',
 'pick',
 'urgent',
 'over',
 'sent',
 'contact',
 'something',
 'buy',
 'gud',
 'again',
 'cant',
 'wait',
 'before',
 'place',
 'box',
 'first',
 'his',
 'even',
 'someone',
 'guy',
 'help',
 'went',
 'wish',
 'next',
 'tonight',
 'were',
 'nice',
 'soon',
 'show',
 'which',
 'off',
 'around',
 'word',
 'could',
 'customer',
 'money',
 'sleep',
 'chat',
 'per',
 'many',
 'late',
 'always',
 'ya',
 'gonna',
 'sm',
 'down',
 'leave',
 'wan',
 'name',
 'lot',
 'end',
 'other',
 'dun',
 'pm',
 'told',
 'st',
 'person',
 'waiting',
 'hello',
 'special',
 'try',
 'month',
 'girl',
 'hour',
 'may',
 'fine',
 'best',
 'haha',
 'minute',
 'heart',
 'people',
 'coming',
 'done',
 'guaranteed',
 'yet',
 'thk',
 'same',
 'th',
 'getting',
 'smile',
 'ppm',
 'use',
 'thought',
 'god',
 'didn',
 'offer',
 'stuff',
 'holiday',
 'talk',
 'start',
 'class',
 'man',
 'cost',
 'live',
 'mean',
 'bit',
 'line',
 'car',
 'lunch',
 'few',
 'draw',
 'finish',
 'job',
 'being',
 'problem',
 'never',
 'yup',
 'ill',
 'better',
 'plan',
 'trying',
 'house',
 'thats',
 'cool',
 'hr',
 'meeting',
 'account',
 'rate',
 'mind',
 'pobox',
 'ready',
 'having',
 'dat',
 'long',
 'weekend',
 'game',
 'chance',
 'world',
 'real',
 'half',
 'enjoy',
 'latest',
 'wk',
 'po',
 'room',
 'yo',
 'sir',
 'check',
 'because',
 'than',
 'bt',
 'guess',
 'play',
 'awarded',
 'wanna',
 'nothing',
 'lar',
 'receive',
 'boy',
 'voucher',
 'eat',
 'sweet',
 'luv',
 'look',
 'camera',
 'pic',
 'another',
 'liao',
 'big',
 'shit',
 'dinner',
 'into',
 'ah',
 'landline',
 'birthday',
 'xxx',
 'jus',
 'might',
 'ever',
 'quite',
 'video',
 'kiss',
 'age',
 'watching',
 'wont',
 'question',
 'land',
 'watch',
 'dream',
 'orange',
 'early',
 'thanx',
 'worry',
 'baby',
 'called',
 'speak',
 'two',
 'tv',
 'aight',
 'once',
 'hear',
 'fun',
 'probably',
 'nd',
 'point',
 'bed',
 'pa',
 'pay',
 'doe',
 'actually',
 'network',
 'princess',
 'nite',
 'apply',
 'maybe',
 'shall',
 'bus',
 'part',
 'sat',
 'left',
 'forgot',
 'den',
 'bad',
 'ringtone',
 'remember',
 'office',
 'hurt',
 'easy',
 'reach',
 'code',
 'shopping',
 'between',
 'dunno',
 'made',
 'xx',
 'dis',
 'little',
 'evening',
 'didnt',
 'award',
 'put',
 'true',
 'leh',
 'fuck',
 'everything',
 'wife',
 'anyway',
 'face',
 'dad',
 'looking',
 'town',
 'thank',
 'afternoon',
 'gift',
 'school',
 'enough',
 'sound',
 'those',
 'mail',
 'working',
 'mate',
 'selected',
 'yr',
 'movie',
 'most',
 'collect',
 'pound',
 'detail',
 'without',
 'asked',
 'entry',
 'while',
 'missing',
 'tmr',
 'hav',
 'join',
 'price',
 'sexy',
 'okay',
 'though',
 'pain',
 'wif',
 'important',
 'must',
 'xmas',
 'wanted',
 'until',
 'since',
 'valid',
 'came',
 'update',
 'mob',
 'answer',
 'wot',
 'lesson',
 'missed',
 'wake',
 'book',
 'abt',
 'run',
 'collection',
 'bring',
 'able',
 'til',
 'wen',
 'haven',
 'decimal',
 'de',
 'test',
 'charge',
 'juz',
 'plus',
 'change',
 'stay',
 'date',
 'plz',
 'colour',
 'away',
 'double',
 'weekly',
 'havent',
 'yesterday',
 'saw',
 'else',
 'music',
 'till',
 'shop',
 'dude',
 'bored',
 'attempt',
 'alright',
 'hair',
 'lei',
 'food',
 'optout',
 'trip',
 'credit',
 'friendship',
 'making',
 'drink',
 'net',
 'these',
 'online',
 'id',
 'haf',
 'yours',
 'top',
 'oso',
 'coz',
 'goin',
 'tried',
 'gr',
 'family',
 'address',
 'delivery',
 'sch',
 'hot',
 'player',
 'club',
 'either',
 'smoke',
 'ard',
 'driving',
 'feeling',
 'national',
 'yourself',
 'nt',
 'sad',
 'order',
 'lose',
 'together',
 'calling',
 'full',
 'wid',
 'second',
 'story',
 'mom',
 'busy',
 'ring',
 'beautiful',
 'head',
 'bonus',
 'walk',
 'http',
 'brother',
 'tot',
 'both',
 'si',
 'sae',
 'post',
 'believe',
 'smiling',
 'huh',
 'close',
 'poly',
 'old',
 'eve',
 'row',
 'chikku',
 'happen',
 'noe',
 'drive',
 'await',
 'set',
 'info',
 'hand',
 'saying',
 'mum',
 'sleeping',
 'leaving',
 'awesome',
 'mths',
 'took',
 'congrats',
 'pub',
 'hl',
 'email',
 'drop',
 'parent',
 'wil',
 'rite',
 'tomo',
 'match',
 'thinking',
 'suite',
 'started',
 'news',
 'simple',
 'aft',
 'finished',
 'private',
 'cause',
 'doesn',
 'okie',
 'tho',
 'unsubscribe',
 'auction',
 'available',
 'tc',
 'forget',
 'content',
 'everyone',
 'company',
 'anyone',
 'sister',
 'touch',
 'break',
 'caller',
 'valentine',
 'reason',
 'mine',
 'final',
 'card',
 'angry',
 'neva',
 'taking',
 'gd',
 'statement',
 'open',
 'dating',
 'loving',
 'whats',
 'alone',
 'found',
 'treat',
 'whatever',
 'lucky',
 'fancy',
 'carlos',
 'gal',
 'choose',
 'worth',
 'opt',
 'each',
 'ticket',
 'search',
 'sun',
 'knw',
 'type',
 'bank',
 'expires',
 'wonderful',
 'frnd',
 'hows',
 'mobileupd',
 'hit',
 'winner',
 'hard',
 'boytoy',
 'gone',
 'saturday',
 'gbp',
 'welcome',
 'fast',
 'happened',
 'quiz',
 'anytime',
 'kind',
 'congratulation',
 'bout',
 'secret',
 'far',
 'identifier',
 'decided',
 'sub',
 'ni',
 'exam',
 'uncle',
 'ltd',
 'party',
 'smth',
 'friday',
 'college',
 'visit',
 'nyt',
 'prob',
 'song',
 'darlin',
 'mu',
 'hold',
 'read',
 'light',
 'operator',
 'oredi',
 'goodmorning',
 'finally',
 'mrng',
 'tel',
 'sea',
 'wit',
 'project',
 'pretty',
 'outside',
 'nope',
 'term',
 'used',
 'drug',
 'fucking',
 'wonder',
 'camcorder',
 'lovely',
 'wrong',
 'least',
 'chennai',
 'fri',
 'crazy',
 'ten',
 'log',
 'cum',
 'listen',
 'frnds',
 'freemsg',
 'seeing',
 'blue',
 'telling',
 'fone',
 'case',
 'meant',
 'jay',
 'whole',
 'fr',
 'unlimited',
 'cd',
 'their',
 'wasn',
 'isn',
 'support',
 'course',
 'frm',
 'sunday',
 'hmm',
 'wq',
 'savamob',
 'snow',
 'hungry',
 'earlier',
 'wkly',
 'stupid',
 'die',
 'happiness',
 'un',
 'dnt',
 'move',
 'etc',
 'hee',
 'within',
 'single',
 'yar',
 'hmmm',
 'cut',
 'mr',
 'eh',
 'moment',
 'march',
 'enter',
 'joy',
 'luck',
 'film',
 'na',
 'balance',
 'gn',
 'john',
 'gas',
 'child',
 'knew',
 'understand',
 'pas',
 'father',
 'valued',
 'store',
 'tired',
 'bslvyl',
 'mayb',
 'sell',
 'almost',
 'sex',
 'paper',
 'press',
 'side',
 'area',
 'sk',
 'currently',
 'couple',
 'txts',
 'computer',
 'rock',
 'invited',
 'felt',
 'as',
 'ago',
 'download',
 'india',
 'lost',
 'mah',
 'christmas',
 'talking',
 'reading',
 'load',
 'motorola',
 'park',
 'shower',
 'bill',
 'hospital',
 'askd',
 'picking',
 'charged',
 'photo',
 'direct',
 'heard',
 'return',
 'rental',
 'eye',
 'via',
 'darren',
 'confirm',
 'semester',
 'correct',
 'reveal',
 'red',
 'doin',
 'ac',
 'laptop',
 'xy',
 'supposed',
 'wow',
 'sort',
 'ugh',
 'extra',
 'information',
 'bcoz',
 'kid',
 'gym',
 'swing',
 'redeemed',
 'surprise',
 'seen',
 'difficult',
 'through',
 'ge',
 'promise',
 'met',
 'max',
 'sending',
 'lady',
 'complimentary',
 'comp',
 'figure',
 'ipod',
 'gotta',
 'grin',
 'ish',
 'abiola',
 'slowly',
 'ex',
 'whenever',
 'discount',
 'lovable',
 'yep',
 'muz',
 'request',
 'std',
 'bath',
 'police',
 'hg',
 'crave',
 'usf',
 'safe',
 'reward',
 'nobody',
 'eg',
 'orchard',
 'road',
 'kate',
 'wine',
 'comin',
 'slow',
 'weed',
 'link',
 'asap',
 'truth',
 'wap',
 'fantasy',
 'study',
 'fact',
 'loved',
 'loan',
 'cheer',
 'small',
 'somebody',
 'page',
 'rest',
 'laugh',
 'rply',
 'hmv',
 'joke',
 'leaf',
 'entered',
 'txting',
 'blood',
 'wana',
 'idea',
 'noon',
 'clean',
 'dogging',
 'door',
 'checking',
 'asking',
 'train',
 'own',
 'remove',
 'lover',
 'monday',
 'save',
 'rent',
 'pete',
 'member',
 'energy',
 'nah',
 'deal',
 'near',
 'del',
 'forever',
 'mistake',
 'cup',
 'copy',
 'normal',
 'somewhere',
 'men',
 'england',
 'la',
 'opinion',
 'situation',
 'em',
 'cheap',
 'warm',
 'hoping',
 'empty',
 'across',
 'hw',
 'woke',
 'usual',
 'rakhesh',
 'callertune',
 'spend',
 'med',
 'gave',
 'cover',
 'write',
 'short',
 'bb',
 'tonite',
 'ringtones',
 'bathe',
 'water',
 'different',
 'representative',
 'sony',
 'ho',
 'ntt',
 'voice',
 'king',
 'merry',
 'gap',
 'poor',
 'fantastic',
 'booked',
 'oops',
 'wc',
 'gettin',
 'bag',
 'admirer',
 'getzed',
 'ldn',
 'kick',
 'less',
 'immediately',
 'glad',
 'summer',
 'wishing',
 'street',
 'teach',
 'cr',
 'otherwise',
 'worried',
 'doctor',
 'sale',
 'il',
 'convey',
 'custcare',
 'indian',
 ...]

In [59]:
w2v_model.corpus_count

5569

In [60]:
w2v_model.epochs

5

Note: The more the number of epochs, the better the model has been trained

In [64]:
## Now lets check for similarities
w2v_model.wv.similar_by_word('good')

[('my', 0.9990570545196533),
 ('day', 0.9988284707069397),
 ('all', 0.9987824559211731),
 ('wa', 0.9986265301704407),
 ('well', 0.9986189007759094),
 ('night', 0.998611330986023),
 ('happy', 0.9985939264297485),
 ('of', 0.9984655380249023),
 ('not', 0.9984592199325562),
 ('morning', 0.9984151721000671)]

Recall: We just trained with 5 epochs. We might have to increase that for better similarity accuracy.

In [66]:
## Lets view the vector
w2v_model.wv['good']

array([-0.274, 0.233, 0.0942, 0.143, 0.0534, -0.636, 0.224, 0.726, -0.359, -0.154, -0.307, -0.541, -0.0657, 0.106, 0.223, -0.278, 0.225, -0.473, -0.0175, -0.819, 0.348, 0.141, 0.268, -0.223, 0.0554, -0.00238, -0.331, -0.296, -0.381, 0.0554, 0.391, -0.0717, 0.232, -0.298, -0.163, 0.492, -0.0566, -0.219, -0.208, -0.726, 0.0251, -0.268, -0.227, 0.0507, 0.285, -0.0353, -0.294, -0.133, 0.299, 0.197, 0.231, -0.258, -0.128, 0.0188, -0.0548, 0.0273, 0.287, 0.166, -0.548, 0.184, -0.0104, 0.0623, -0.16, -0.141, -0.422, 0.333, 0.0648, 0.341, -0.416, 0.474, -0.264, 0.269, 0.527, -0.0945, 0.435, -0.00968, 0.106, -0.221, -0.237, 0.131, -0.324, -0.0314, -0.353, 0.663, -0.276, -0.154, 0.172, 0.319, 0.507, 0.0713, 0.495, 0.191, 0.111, 0.101, 0.782, 0.298, 0.255, -0.28, 0.202, -0.0378], dtype=float32)

In [67]:
w2v_model.wv['good'].shape

(100,)

Now we can see that for every word we have created a 100 dimension vector. What we need is a vector for each sentence. That is where **`AvgWord2Vec`** comes in. We will calculate the average of the vectors for each word in the sentence to get a vector representation for the sentence.

PS: This model has not yet been improved. This is just practicals.

In [100]:
import numpy as np

# Krish func
# def avg_word2vec(doc):
#     ## remove out-of-vocabulary words
#     #sent=[word for word.in doc if word is in w2v_model.wv.index_to_key]
#     #print(sent)

#     return np.mean([w2v_model.wv[word] for word in doc if word in w2v_model.wv.index_to_key],axis=0)

# Izu func. Created because a sentence can have no word in the model vocabulary and then it will return an empty list
# I captured that and returned zeros vector instead
def avg_word2vec(doc):
    vectors = [
        w2v_model.wv[word]
        for word in doc
        if word in w2v_model.wv
    ]

    if len(vectors) == 0:
        return np.zeros(w2v_model.vector_size)

    return np.mean(vectors, axis=0)

In [68]:
## To understand the progress let us install a progressiontab called tqdm
!pip install tqdm

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tqdm in c:\users\pc\appdata\roaming\python\python312\site-packages (4.67.3)
Requirement already satisfied: colorama in c:\users\pc\appdata\roaming\python\python312\site-packages (from tqdm) (0.4.6)

In [69]:
from tqdm import tqdm

In [95]:
# Apply for the entire sentences
X=[]
for i in tqdm(range(len(words))):
    print("Hello", i)
    X.append(avg_word2vec(words[i]))

  7%|█████                                                                        | 362/5569 [00:00<00:01, 3591.38it/s]

Hello 0
Hello 1
Hello 2
Hello 3
Hello 4
Hello 5
Hello 6
Hello 7
Hello 8
Hello 9
Hello 10
Hello 11
Hello 12
Hello 13
Hello 14
Hello 15
Hello 16
Hello 17
Hello 18
Hello 19
Hello 20
Hello 21
Hello 22
Hello 23
Hello 24
Hello 25
Hello 26
Hello 27
Hello 28
Hello 29
Hello 30
Hello 31
Hello 32
Hello 33
Hello 34
Hello 35
Hello 36
Hello 37
Hello 38
Hello 39
Hello 40
Hello 41
Hello 42
Hello 43
Hello 44
Hello 45
Hello 46
Hello 47
Hello 48
Hello 49
Hello 50
Hello 51
Hello 52
Hello 53
Hello 54
Hello 55
Hello 56
Hello 57
Hello 58
Hello 59
Hello 60
Hello 61
Hello 62
Hello 63
Hello 64
Hello 65
Hello 66
Hello 67
Hello 68
Hello 69
Hello 70
Hello 71
Hello 72
Hello 73
Hello 74
Hello 75
Hello 76
Hello 77
Hello 78
Hello 79
Hello 80
Hello 81
Hello 82
Hello 83
Hello 84
Hello 85
Hello 86
Hello 87
Hello 88
Hello 89
Hello 90
Hello 91
Hello 92
Hello 93
Hello 94
Hello 95
Hello 96
Hello 97
Hello 98
Hello 99
Hello 100
Hello 101
Hello 102
Hello 103
Hello 104
Hello 105
Hello 106
Hello 107
Hello 108
Hello 109
Hello 110
Hello 111
Hello 112
Hello 113
Hello 114
Hello 115
Hello 116
Hello 117
Hello 118
Hello 119
Hello 120
Hello 121
Hello 122
Hello 123
Hello 124
Hello 125
Hello 126
Hello 127
Hello 128
Hello 129
Hello 130
Hello 131
Hello 132
Hello 133
Hello 134
Hello 135
Hello 136
Hello 137
Hello 138
Hello 139
Hello 140
Hello 141
Hello 142
Hello 143
Hello 144
Hello 145
Hello 146
Hello 147
Hello 148
Hello 149
Hello 150
Hello 151
Hello 152
Hello 153
Hello 154
Hello 155
Hello 156
Hello 157
Hello 158
Hello 159
Hello 160
Hello 161
Hello 162
Hello 163
Hello 164
Hello 165
Hello 166
Hello 167
Hello 168
Hello 169
Hello 170
Hello 171
Hello 172
Hello 173
Hello 174
Hello 175
Hello 176
Hello 177
Hello 178
Hello 179
Hello 180
Hello 181
Hello 182
Hello 183
Hello 184
Hello 185
Hello 186
Hello 187
Hello 188
Hello 189
Hello 190
Hello 191
Hello 192
Hello 193
Hello 194
Hello 195
Hello 196
Hello 197
Hello 198
Hello 199
Hello 200
Hello 201
Hello 202
Hello 203
Hello 204
Hello 205
Hello 206
Hello 207
Hello 208
Hello 209
Hello 210
Hello 211
Hello 212
Hello 213
Hello 214
Hello 215
Hello 216
Hello 217
Hello 218
Hello 219
Hello 220
Hello 221
Hello 222
Hello 223
Hello 224
Hello 225
Hello 226
Hello 227
Hello 228
Hello 229
Hello 230
Hello 231
Hello 232
Hello 233
Hello 234
Hello 235
Hello 236
Hello 237
Hello 238
Hello 239
Hello 240
Hello 241
Hello 242
Hello 243
Hello 244
Hello 245
Hello 246
Hello 247
Hello 248
Hello 249
Hello 250
Hello 251
Hello 252
Hello 253
Hello 254
Hello 255
Hello 256
Hello 257
Hello 258
Hello 259
Hello 260
Hello 261
Hello 262
Hello 263
Hello 264
Hello 265
Hello 266
Hello 267
Hello 268
Hello 269
Hello 270
Hello 271
Hello 272
Hello 273
Hello 274
Hello 275
Hello 276
Hello 277
Hello 278
Hello 279
Hello 280
Hello 281
Hello 282
Hello 283
Hello 284
Hello 285
Hello 286
Hello 287
Hello 288
Hello 289
Hello 290
Hello 291
Hello 292
Hello 293
Hello 294
Hello 295
Hello 296
Hello 297
Hello 298
Hello 299
Hello 300
Hello 301
Hello 302
Hello 303
Hello 304
Hello 305
Hello 306
Hello 307
Hello 308
Hello 309
Hello 310
Hello 311
Hello 312
Hello 313
Hello 314
Hello 315
Hello 316
Hello 317
Hello 318
Hello 319
Hello 320
Hello 321
Hello 322
Hello 323
Hello 324
Hello 325
Hello 326
Hello 327
Hello 328
Hello 329
Hello 330
Hello 331
Hello 332
Hello 333
Hello 334
Hello 335
Hello 336
Hello 337
Hello 338
Hello 339
Hello 340
Hello 341
Hello 342
Hello 343
Hello 344
Hello 345
Hello 346
Hello 347
Hello 348
Hello 349
Hello 350
Hello 351
Hello 352
Hello 353
Hello 354
Hello 355
Hello 356
Hello 357
Hello 358
Hello 359
Hello 360
Hello 361
Hello 362
Hello 363
Hello 364
Hello 365
Hello 366
Hello 367
Hello 368
Hello 369
Hello 370
Hello 371
Hello 372
Hello 373
Hello 374
Hello 375
Hello 376
Hello 377
Hello 378
Hello 379
Hello 380
Hello 381
Hello 382
Hello 383
Hello 384
Hello 385
Hello 386
Hello 387
Hello 388
Hello 389
Hello 390
Hello 391
Hello 392
Hello 393
Hello 394
Hello 395
Hello 396
Hello 397
Hello 398
Hello 399
Hello 400
Hello 401
Hello 402
Hello 403
Hello 404
Hello 405
Hello 406
Hello 407
Hello 408
Hello 409
Hello 410
Hello 411
Hello 412
Hello 413
Hello 414
Hello 415
Hello 416
Hello 417
Hello 418
Hello 419
Hello 420
Hello 421
Hello 422
Hello 423
Hello 424
Hello 425
Hello 426
Hello 427
Hello 428
Hello 429
Hello 430
Hello 431
Hello 432
Hello 433
Hello 434
Hello 435
Hello 436
Hello 437
Hello 438
Hello 439
Hello 440
Hello 441
Hello 442
Hello 443
Hello 444
Hello 445
Hello 446
Hello 447
Hello 448
Hello 449
Hello 450
Hello 451
Hello 452
Hello 453
Hello 454
Hello 455
Hello 456
Hello 457
Hello 458
Hello 459
Hello 460
Hello 461
Hello 462
Hello 463
Hello 464
Hello 465
Hello 466
Hello 467
Hello 468
Hello 469
Hello 470
Hello 471
Hello 472
Hello 473
Hello 474
Hello 475
Hello 476
Hello 477
Hello 478
Hello 479
Hello 480
Hello 481
Hello 482
Hello 483
Hello 484
Hello 485
Hello 486
Hello 487
Hello 488
Hello 489
Hello 490
Hello 491
Hello 492
Hello 493
Hello 494
Hello 495
Hello 496
Hello 497
Hello 498
Hello 499
Hello 500
Hello 501
Hello 502
Hello 503
Hello 504
Hello 505
Hello 506
Hello 507
Hello 508
Hello 509
Hello 510
Hello 511
Hello 512
Hello 513
Hello 514
Hello 515
Hello 516
Hello 517
Hello 518
Hello 519
Hello 520
Hello 521
Hello 522
Hello 523
Hello 524
Hello 525
Hello 526
Hello 527
Hello 528
Hello 529
Hello 530
Hello 531
Hello 532
Hello 533
Hello 534
Hello 535
Hello 536
Hello 537
Hello 538
Hello 539
Hello 540
Hello 541
Hello 542
Hello 543
Hello 544
Hello 545
Hello 546
Hello 547
Hello 548
Hello 549
Hello 550
Hello 551
Hello 552
Hello 553
Hello 554
Hello 555
Hello 556
Hello 557
Hello 558
Hello 559
Hello 560
Hello 561
Hello 562
Hello 563
Hello 564
Hello 565
Hello 566
Hello 567
Hello 568
Hello 569
Hello 570
Hello 571
Hello 572
Hello 573
Hello 574
Hello 575
Hello 576
Hello 577
Hello 578
Hello 579
Hello 580
Hello 581
Hello 582
Hello 583
Hello 584
Hello 585
Hello 586
Hello 587
Hello 588
Hello 589
Hello 590
Hello 591
Hello 592
Hello 593
Hello 594
Hello 595
Hello 596
Hello 597
Hello 598
Hello 599
Hello 600
Hello 601
Hello 602
Hello 603
Hello 604
Hello 605
Hello 606
Hello 607
Hello 608
Hello 609
Hello 610
Hello 611
Hello 612
Hello 613
Hello 614
Hello 615
Hello 616
Hello 617
Hello 618
Hello 619
Hello 620
Hello 621
Hello 622
Hello 623
Hello 624
Hello 625
Hello 626
Hello 627
Hello 628
Hello 629
Hello 630
Hello 631
Hello 632
Hello 633
Hello 634
Hello 635
Hello 636
Hello 637
Hello 638
Hello 639
Hello 640
Hello 641
Hello 642
Hello 643
Hello 644
Hello 645
Hello 646
Hello 647
Hello 648
Hello 649
Hello 650
Hello 651
Hello 652
Hello 653
Hello 654
Hello 655
Hello 656
Hello 657
Hello 658
Hello 659
Hello 660
Hello 661
Hello 662

 19%|██████████████                                                              | 1035/5569 [00:00<00:01, 2708.64it/s]

Hello 663
Hello 664
Hello 665
Hello 666
Hello 667
Hello 668
Hello 669
Hello 670
Hello 671
Hello 672
Hello 673
Hello 674
Hello 675
Hello 676
Hello 677
Hello 678
Hello 679
Hello 680
Hello 681
Hello 682
Hello 683
Hello 684
Hello 685
Hello 686
Hello 687
Hello 688
Hello 689
Hello 690
Hello 691
Hello 692
Hello 693
Hello 694
Hello 695
Hello 696
Hello 697
Hello 698
Hello 699
Hello 700
Hello 701
Hello 702
Hello 703
Hello 704
Hello 705
Hello 706
Hello 707
Hello 708
Hello 709
Hello 710
Hello 711
Hello 712
Hello 713
Hello 714
Hello 715
Hello 716
Hello 717
Hello 718
Hello 719
Hello 720
Hello 721
Hello 722
Hello 723
Hello 724
Hello 725
Hello 726
Hello 727
Hello 728
Hello 729
Hello 730
Hello 731
Hello 732
Hello 733
Hello 734
Hello 735
Hello 736
Hello 737
Hello 738
Hello 739
Hello 740
Hello 741
Hello 742
Hello 743
Hello 744
Hello 745
Hello 746
Hello 747
Hello 748
Hello 749
Hello 750
Hello 751
Hello 752
Hello 753
Hello 754
Hello 755
Hello 756
Hello 757
Hello 758
Hello 759
Hello 760
Hello 761
Hello 762
Hello 763
Hello 764
Hello 765
Hello 766
Hello 767
Hello 768
Hello 769
Hello 770
Hello 771
Hello 772
Hello 773
Hello 774
Hello 775
Hello 776
Hello 777
Hello 778
Hello 779
Hello 780
Hello 781
Hello 782
Hello 783
Hello 784
Hello 785
Hello 786
Hello 787
Hello 788
Hello 789
Hello 790
Hello 791
Hello 792
Hello 793
Hello 794
Hello 795
Hello 796
Hello 797
Hello 798
Hello 799
Hello 800
Hello 801
Hello 802
Hello 803
Hello 804
Hello 805
Hello 806
Hello 807
Hello 808
Hello 809
Hello 810
Hello 811
Hello 812
Hello 813
Hello 814
Hello 815
Hello 816
Hello 817
Hello 818
Hello 819
Hello 820
Hello 821
Hello 822
Hello 823
Hello 824
Hello 825
Hello 826
Hello 827
Hello 828
Hello 829
Hello 830
Hello 831
Hello 832
Hello 833
Hello 834
Hello 835
Hello 836
Hello 837
Hello 838
Hello 839
Hello 840
Hello 841
Hello 842
Hello 843
Hello 844
Hello 845
Hello 846
Hello 847
Hello 848
Hello 849
Hello 850
Hello 851
Hello 852
Hello 853
Hello 854
Hello 855
Hello 856
Hello 857
Hello 858
Hello 859
Hello 860
Hello 861
Hello 862
Hello 863
Hello 864
Hello 865
Hello 866
Hello 867
Hello 868
Hello 869
Hello 870
Hello 871
Hello 872
Hello 873
Hello 874
Hello 875
Hello 876
Hello 877
Hello 878
Hello 879
Hello 880
Hello 881
Hello 882
Hello 883
Hello 884
Hello 885
Hello 886
Hello 887
Hello 888
Hello 889
Hello 890
Hello 891
Hello 892
Hello 893
Hello 894
Hello 895
Hello 896
Hello 897
Hello 898
Hello 899
Hello 900
Hello 901
Hello 902
Hello 903
Hello 904
Hello 905
Hello 906
Hello 907
Hello 908
Hello 909
Hello 910
Hello 911
Hello 912
Hello 913
Hello 914
Hello 915
Hello 916
Hello 917
Hello 918
Hello 919
Hello 920
Hello 921
Hello 922
Hello 923
Hello 924
Hello 925
Hello 926
Hello 927
Hello 928
Hello 929
Hello 930
Hello 931
Hello 932
Hello 933
Hello 934
Hello 935
Hello 936
Hello 937
Hello 938
Hello 939
Hello 940
Hello 941
Hello 942
Hello 943
Hello 944
Hello 945
Hello 946
Hello 947
Hello 948
Hello 949
Hello 950
Hello 951
Hello 952
Hello 953
Hello 954
Hello 955
Hello 956
Hello 957
Hello 958
Hello 959
Hello 960
Hello 961
Hello 962
Hello 963
Hello 964
Hello 965
Hello 966
Hello 967
Hello 968
Hello 969
Hello 970
Hello 971
Hello 972
Hello 973
Hello 974
Hello 975
Hello 976
Hello 977
Hello 978
Hello 979
Hello 980
Hello 981
Hello 982
Hello 983
Hello 984
Hello 985
Hello 986
Hello 987
Hello 988
Hello 989
Hello 990
Hello 991
Hello 992
Hello 993
Hello 994
Hello 995
Hello 996
Hello 997
Hello 998
Hello 999
Hello 1000
Hello 1001
Hello 1002
Hello 1003
Hello 1004
Hello 1005
Hello 1006
Hello 1007
Hello 1008
Hello 1009
Hello 1010
Hello 1011
Hello 1012
Hello 1013
Hello 1014
Hello 1015
Hello 1016
Hello 1017
Hello 1018
Hello 1019
Hello 1020
Hello 1021
Hello 1022
Hello 1023
Hello 1024
Hello 1025
Hello 1026
Hello 1027
Hello 1028
Hello 1029
Hello 1030
Hello 1031
Hello 1032
Hello 1033
Hello 1034
Hello 1035
Hello 1036
Hello 1037
Hello 1038
Hello 1039
Hello 1040
Hello 1041
Hello 1042
Hello 1043
Hello 1044
Hello 1045
Hello 1046
Hello 1047
Hello 1048
Hello 1049
Hello 1050
Hello 1051
Hello 1052
Hello 1053
Hello 1054
Hello 1055
Hello 1056
Hello 1057
Hello 1058
Hello 1059
Hello 1060
Hello 1061
Hello 1062
Hello 1063
Hello 1064
Hello 1065
Hello 1066
Hello 1067
Hello 1068
Hello 1069
Hello 1070
Hello 1071
Hello 1072
Hello 1073
Hello 1074
Hello 1075
Hello 1076
Hello 1077
Hello 1078
Hello 1079
Hello 1080
Hello 1081
Hello 1082
Hello 1083
Hello 1084
Hello 1085
Hello 1086
Hello 1087
Hello 1088
Hello 1089
Hello 1090
Hello 1091
Hello 1092
Hello 1093
Hello 1094
Hello 1095
Hello 1096
Hello 1097
Hello 1098
Hello 1099
Hello 1100
Hello 1101
Hello 1102
Hello 1103
Hello 1104
Hello 1105
Hello 1106
Hello 1107
Hello 1108
Hello 1109
Hello 1110
Hello 1111
Hello 1112
Hello 1113
Hello 1114
Hello 1115
Hello 1116
Hello 1117
Hello 1118
Hello 1119
Hello 1120
Hello 1121
Hello 1122
Hello 1123
Hello 1124
Hello 1125
Hello 1126
Hello 1127
Hello 1128
Hello 1129
Hello 1130
Hello 1131
Hello 1132
Hello 1133
Hello 1134
Hello 1135
Hello 1136
Hello 1137
Hello 1138
Hello 1139
Hello 1140
Hello 1141
Hello 1142
Hello 1143
Hello 1144
Hello 1145
Hello 1146
Hello 1147
Hello 1148
Hello 1149
Hello 1150
Hello 1151
Hello 1152
Hello 1153
Hello 1154
Hello 1155

 30%|██████████████████████▍                                                     | 1645/5569 [00:00<00:01, 2887.65it/s]

Hello 1156
Hello 1157
Hello 1158
Hello 1159
Hello 1160
Hello 1161
Hello 1162
Hello 1163
Hello 1164
Hello 1165
Hello 1166
Hello 1167
Hello 1168
Hello 1169
Hello 1170
Hello 1171
Hello 1172
Hello 1173
Hello 1174
Hello 1175
Hello 1176
Hello 1177
Hello 1178
Hello 1179
Hello 1180
Hello 1181
Hello 1182
Hello 1183
Hello 1184
Hello 1185
Hello 1186
Hello 1187
Hello 1188
Hello 1189
Hello 1190
Hello 1191
Hello 1192
Hello 1193
Hello 1194
Hello 1195
Hello 1196
Hello 1197
Hello 1198
Hello 1199
Hello 1200
Hello 1201
Hello 1202
Hello 1203
Hello 1204
Hello 1205
Hello 1206
Hello 1207
Hello 1208
Hello 1209
Hello 1210
Hello 1211
Hello 1212
Hello 1213
Hello 1214
Hello 1215
Hello 1216
Hello 1217
Hello 1218
Hello 1219
Hello 1220
Hello 1221
Hello 1222
Hello 1223
Hello 1224
Hello 1225
Hello 1226
Hello 1227
Hello 1228
Hello 1229
Hello 1230
Hello 1231
Hello 1232
Hello 1233
Hello 1234
Hello 1235
Hello 1236
Hello 1237
Hello 1238
Hello 1239
Hello 1240
Hello 1241
Hello 1242
Hello 1243
Hello 1244
Hello 1245
Hello 1246
Hello 1247
Hello 1248
Hello 1249
Hello 1250
Hello 1251
Hello 1252
Hello 1253
Hello 1254
Hello 1255
Hello 1256
Hello 1257
Hello 1258
Hello 1259
Hello 1260
Hello 1261
Hello 1262
Hello 1263
Hello 1264
Hello 1265
Hello 1266
Hello 1267
Hello 1268
Hello 1269
Hello 1270
Hello 1271
Hello 1272
Hello 1273
Hello 1274
Hello 1275
Hello 1276
Hello 1277
Hello 1278
Hello 1279
Hello 1280
Hello 1281
Hello 1282
Hello 1283
Hello 1284
Hello 1285
Hello 1286
Hello 1287
Hello 1288
Hello 1289
Hello 1290
Hello 1291
Hello 1292
Hello 1293
Hello 1294
Hello 1295
Hello 1296
Hello 1297
Hello 1298
Hello 1299
Hello 1300
Hello 1301
Hello 1302
Hello 1303
Hello 1304
Hello 1305
Hello 1306
Hello 1307
Hello 1308
Hello 1309
Hello 1310
Hello 1311
Hello 1312
Hello 1313
Hello 1314
Hello 1315
Hello 1316
Hello 1317
Hello 1318
Hello 1319
Hello 1320
Hello 1321
Hello 1322
Hello 1323
Hello 1324
Hello 1325
Hello 1326
Hello 1327
Hello 1328
Hello 1329
Hello 1330
Hello 1331
Hello 1332
Hello 1333
Hello 1334
Hello 1335
Hello 1336
Hello 1337
Hello 1338
Hello 1339
Hello 1340
Hello 1341
Hello 1342
Hello 1343
Hello 1344
Hello 1345
Hello 1346
Hello 1347
Hello 1348
Hello 1349
Hello 1350
Hello 1351
Hello 1352
Hello 1353
Hello 1354
Hello 1355
Hello 1356
Hello 1357
Hello 1358
Hello 1359
Hello 1360
Hello 1361
Hello 1362
Hello 1363
Hello 1364
Hello 1365
Hello 1366
Hello 1367
Hello 1368
Hello 1369
Hello 1370
Hello 1371
Hello 1372
Hello 1373
Hello 1374
Hello 1375
Hello 1376
Hello 1377
Hello 1378
Hello 1379
Hello 1380
Hello 1381
Hello 1382
Hello 1383
Hello 1384
Hello 1385
Hello 1386
Hello 1387
Hello 1388
Hello 1389
Hello 1390
Hello 1391
Hello 1392
Hello 1393
Hello 1394
Hello 1395
Hello 1396
Hello 1397
Hello 1398
Hello 1399
Hello 1400
Hello 1401
Hello 1402
Hello 1403
Hello 1404
Hello 1405
Hello 1406
Hello 1407
Hello 1408
Hello 1409
Hello 1410
Hello 1411
Hello 1412
Hello 1413
Hello 1414
Hello 1415
Hello 1416
Hello 1417
Hello 1418
Hello 1419
Hello 1420
Hello 1421
Hello 1422
Hello 1423
Hello 1424
Hello 1425
Hello 1426
Hello 1427
Hello 1428
Hello 1429
Hello 1430
Hello 1431
Hello 1432
Hello 1433
Hello 1434
Hello 1435
Hello 1436
Hello 1437
Hello 1438
Hello 1439
Hello 1440
Hello 1441
Hello 1442
Hello 1443
Hello 1444
Hello 1445
Hello 1446
Hello 1447
Hello 1448
Hello 1449
Hello 1450
Hello 1451
Hello 1452
Hello 1453
Hello 1454
Hello 1455
Hello 1456
Hello 1457
Hello 1458
Hello 1459
Hello 1460
Hello 1461
Hello 1462
Hello 1463
Hello 1464
Hello 1465
Hello 1466
Hello 1467
Hello 1468
Hello 1469
Hello 1470
Hello 1471
Hello 1472
Hello 1473
Hello 1474
Hello 1475
Hello 1476
Hello 1477
Hello 1478
Hello 1479
Hello 1480
Hello 1481
Hello 1482
Hello 1483
Hello 1484
Hello 1485
Hello 1486
Hello 1487
Hello 1488
Hello 1489
Hello 1490
Hello 1491
Hello 1492
Hello 1493
Hello 1494
Hello 1495
Hello 1496
Hello 1497
Hello 1498
Hello 1499
Hello 1500
Hello 1501
Hello 1502
Hello 1503
Hello 1504
Hello 1505
Hello 1506
Hello 1507
Hello 1508
Hello 1509
Hello 1510
Hello 1511
Hello 1512
Hello 1513
Hello 1514
Hello 1515
Hello 1516
Hello 1517
Hello 1518
Hello 1519
Hello 1520
Hello 1521
Hello 1522
Hello 1523
Hello 1524
Hello 1525
Hello 1526
Hello 1527
Hello 1528
Hello 1529
Hello 1530
Hello 1531
Hello 1532
Hello 1533
Hello 1534
Hello 1535
Hello 1536
Hello 1537
Hello 1538
Hello 1539
Hello 1540
Hello 1541
Hello 1542
Hello 1543
Hello 1544
Hello 1545
Hello 1546
Hello 1547
Hello 1548
Hello 1549
Hello 1550
Hello 1551
Hello 1552
Hello 1553
Hello 1554
Hello 1555
Hello 1556
Hello 1557
Hello 1558
Hello 1559
Hello 1560
Hello 1561
Hello 1562
Hello 1563
Hello 1564
Hello 1565
Hello 1566
Hello 1567
Hello 1568
Hello 1569
Hello 1570
Hello 1571
Hello 1572
Hello 1573
Hello 1574
Hello 1575
Hello 1576
Hello 1577
Hello 1578
Hello 1579
Hello 1580
Hello 1581
Hello 1582
Hello 1583
Hello 1584
Hello 1585
Hello 1586
Hello 1587
Hello 1588
Hello 1589
Hello 1590
Hello 1591
Hello 1592
Hello 1593
Hello 1594
Hello 1595
Hello 1596
Hello 1597
Hello 1598
Hello 1599
Hello 1600
Hello 1601
Hello 1602
Hello 1603
Hello 1604
Hello 1605
Hello 1606
Hello 1607
Hello 1608
Hello 1609
Hello 1610
Hello 1611
Hello 1612
Hello 1613
Hello 1614
Hello 1615
Hello 1616
Hello 1617
Hello 1618
Hello 1619
Hello 1620
Hello 1621
Hello 1622
Hello 1623
Hello 1624
Hello 1625
Hello 1626
Hello 1627
Hello 1628
Hello 1629
Hello 1630
Hello 1631
Hello 1632
Hello 1633
Hello 1634
Hello 1635
Hello 1636
Hello 1637
Hello 1638
Hello 1639
Hello 1640
Hello 1641
Hello 1642
Hello 1643
Hello 1644
Hello 1645
Hello 1646
Hello 1647
Hello 1648
Hello 1649
Hello 1650
Hello 1651
Hello 1652
Hello 1653
Hello 1654
Hello 1655
Hello 1656
Hello 1657
Hello 1658
Hello 1659
Hello 1660
Hello 1661
Hello 1662
Hello 1663
Hello 1664
Hello 1665
Hello 1666
Hello 1667
Hello 1668
Hello 1669
Hello 1670
Hello 1671
Hello 1672
Hello 1673
Hello 1674
Hello 1675
Hello 1676
Hello 1677
Hello 1678
Hello 1679
Hello 1680
Hello 1681
Hello 1682
Hello 1683
Hello 1684
Hello 1685
Hello 1686
Hello 1687
Hello 1688
Hello 1689
Hello 1690
Hello 1691
Hello 1692
Hello 1693
Hello 1694
Hello 1695
Hello 1696
Hello 1697
Hello 1698
Hello 1699
Hello 1700
Hello 1701
Hello 1702
Hello 1703
Hello 1704
Hello 1705
Hello 1706
Hello 1707
Hello 1708
Hello 1709
Hello 1710
Hello 1711
Hello 1712
Hello 1713
Hello 1714
Hello 1715
Hello 1716
Hello 1717
Hello 1718
Hello 1719
Hello 1720
Hello 1721
Hello 1722
Hello 1723
Hello 1724
Hello 1725
Hello 1726
Hello 1727
Hello 1728
Hello 1729
Hello 1730
Hello 1731
Hello 1732
Hello 1733
Hello 1734
Hello 1735
Hello 1736
Hello 1737
Hello 1738
Hello 1739
Hello 1740
Hello 1741
Hello 1742
Hello 1743
Hello 1744
Hello 1745
Hello 1746
Hello 1747
Hello 1748
Hello 1749
Hello 1750
Hello 1751
Hello 1752
Hello 1753
Hello 1754
Hello 1755
Hello 1756
Hello 1757
Hello 1758
Hello 1759
Hello 1760
Hello 1761
Hello 1762
Hello 1763
Hello 1764
Hello 1765
Hello 1766
Hello 1767
Hello 1768
Hello 1769
Hello 1770
Hello 1771
Hello 1772
Hello 1773
Hello 1774
Hello 1775
Hello 1776
Hello 1777
Hello 1778
Hello 1779
Hello 1780
Hello 1781
Hello 1782
Hello 1783
Hello 1784

 41%|███████████████████████████████                                             | 2272/5569 [00:00<00:01, 2866.81it/s]

Hello 1785
Hello 1786
Hello 1787
Hello 1788
Hello 1789
Hello 1790
Hello 1791
Hello 1792
Hello 1793
Hello 1794
Hello 1795
Hello 1796
Hello 1797
Hello 1798
Hello 1799
Hello 1800
Hello 1801
Hello 1802
Hello 1803
Hello 1804
Hello 1805
Hello 1806
Hello 1807
Hello 1808
Hello 1809
Hello 1810
Hello 1811
Hello 1812
Hello 1813
Hello 1814
Hello 1815
Hello 1816
Hello 1817
Hello 1818
Hello 1819
Hello 1820
Hello 1821
Hello 1822
Hello 1823
Hello 1824
Hello 1825
Hello 1826
Hello 1827
Hello 1828
Hello 1829
Hello 1830
Hello 1831
Hello 1832
Hello 1833
Hello 1834
Hello 1835
Hello 1836
Hello 1837
Hello 1838
Hello 1839
Hello 1840
Hello 1841
Hello 1842
Hello 1843
Hello 1844
Hello 1845
Hello 1846
Hello 1847
Hello 1848
Hello 1849
Hello 1850
Hello 1851
Hello 1852
Hello 1853
Hello 1854
Hello 1855
Hello 1856
Hello 1857
Hello 1858
Hello 1859
Hello 1860
Hello 1861
Hello 1862
Hello 1863
Hello 1864
Hello 1865
Hello 1866
Hello 1867
Hello 1868
Hello 1869
Hello 1870
Hello 1871
Hello 1872
Hello 1873
Hello 1874
Hello 1875
Hello 1876
Hello 1877
Hello 1878
Hello 1879
Hello 1880
Hello 1881
Hello 1882
Hello 1883
Hello 1884
Hello 1885
Hello 1886
Hello 1887
Hello 1888
Hello 1889
Hello 1890
Hello 1891
Hello 1892
Hello 1893
Hello 1894
Hello 1895
Hello 1896
Hello 1897
Hello 1898
Hello 1899
Hello 1900
Hello 1901
Hello 1902
Hello 1903
Hello 1904
Hello 1905
Hello 1906
Hello 1907
Hello 1908
Hello 1909
Hello 1910
Hello 1911
Hello 1912
Hello 1913
Hello 1914
Hello 1915
Hello 1916
Hello 1917
Hello 1918
Hello 1919
Hello 1920
Hello 1921
Hello 1922
Hello 1923
Hello 1924
Hello 1925
Hello 1926
Hello 1927
Hello 1928
Hello 1929
Hello 1930
Hello 1931
Hello 1932
Hello 1933
Hello 1934
Hello 1935
Hello 1936
Hello 1937
Hello 1938
Hello 1939
Hello 1940
Hello 1941
Hello 1942
Hello 1943
Hello 1944
Hello 1945
Hello 1946
Hello 1947
Hello 1948
Hello 1949
Hello 1950
Hello 1951
Hello 1952
Hello 1953
Hello 1954
Hello 1955
Hello 1956
Hello 1957
Hello 1958
Hello 1959
Hello 1960
Hello 1961
Hello 1962
Hello 1963
Hello 1964
Hello 1965
Hello 1966
Hello 1967
Hello 1968
Hello 1969
Hello 1970
Hello 1971
Hello 1972
Hello 1973
Hello 1974
Hello 1975
Hello 1976
Hello 1977
Hello 1978
Hello 1979
Hello 1980
Hello 1981
Hello 1982
Hello 1983
Hello 1984
Hello 1985
Hello 1986
Hello 1987
Hello 1988
Hello 1989
Hello 1990
Hello 1991
Hello 1992
Hello 1993
Hello 1994
Hello 1995
Hello 1996
Hello 1997
Hello 1998
Hello 1999
Hello 2000
Hello 2001
Hello 2002
Hello 2003
Hello 2004
Hello 2005
Hello 2006
Hello 2007
Hello 2008
Hello 2009
Hello 2010
Hello 2011
Hello 2012
Hello 2013
Hello 2014
Hello 2015
Hello 2016
Hello 2017
Hello 2018
Hello 2019
Hello 2020
Hello 2021
Hello 2022
Hello 2023
Hello 2024
Hello 2025
Hello 2026
Hello 2027
Hello 2028
Hello 2029
Hello 2030
Hello 2031
Hello 2032
Hello 2033
Hello 2034
Hello 2035
Hello 2036
Hello 2037
Hello 2038
Hello 2039
Hello 2040
Hello 2041
Hello 2042
Hello 2043
Hello 2044
Hello 2045
Hello 2046
Hello 2047
Hello 2048
Hello 2049
Hello 2050
Hello 2051
Hello 2052
Hello 2053
Hello 2054
Hello 2055
Hello 2056
Hello 2057
Hello 2058
Hello 2059
Hello 2060
Hello 2061
Hello 2062
Hello 2063
Hello 2064
Hello 2065
Hello 2066
Hello 2067
Hello 2068
Hello 2069
Hello 2070
Hello 2071
Hello 2072
Hello 2073
Hello 2074
Hello 2075
Hello 2076
Hello 2077
Hello 2078
Hello 2079
Hello 2080
Hello 2081
Hello 2082
Hello 2083
Hello 2084
Hello 2085
Hello 2086
Hello 2087
Hello 2088
Hello 2089
Hello 2090
Hello 2091
Hello 2092
Hello 2093
Hello 2094
Hello 2095
Hello 2096
Hello 2097
Hello 2098
Hello 2099
Hello 2100
Hello 2101
Hello 2102
Hello 2103
Hello 2104
Hello 2105
Hello 2106
Hello 2107
Hello 2108
Hello 2109
Hello 2110
Hello 2111
Hello 2112
Hello 2113
Hello 2114
Hello 2115
Hello 2116
Hello 2117
Hello 2118
Hello 2119
Hello 2120
Hello 2121
Hello 2122
Hello 2123
Hello 2124
Hello 2125
Hello 2126
Hello 2127
Hello 2128
Hello 2129
Hello 2130
Hello 2131
Hello 2132
Hello 2133
Hello 2134
Hello 2135
Hello 2136
Hello 2137
Hello 2138
Hello 2139
Hello 2140
Hello 2141
Hello 2142
Hello 2143
Hello 2144
Hello 2145
Hello 2146
Hello 2147
Hello 2148
Hello 2149
Hello 2150
Hello 2151
Hello 2152
Hello 2153
Hello 2154
Hello 2155
Hello 2156
Hello 2157
Hello 2158
Hello 2159
Hello 2160
Hello 2161
Hello 2162
Hello 2163
Hello 2164
Hello 2165
Hello 2166
Hello 2167
Hello 2168
Hello 2169
Hello 2170
Hello 2171
Hello 2172
Hello 2173
Hello 2174
Hello 2175
Hello 2176
Hello 2177
Hello 2178
Hello 2179
Hello 2180
Hello 2181
Hello 2182
Hello 2183
Hello 2184
Hello 2185
Hello 2186
Hello 2187
Hello 2188
Hello 2189
Hello 2190
Hello 2191
Hello 2192
Hello 2193
Hello 2194
Hello 2195
Hello 2196
Hello 2197
Hello 2198
Hello 2199
Hello 2200
Hello 2201
Hello 2202
Hello 2203
Hello 2204
Hello 2205
Hello 2206
Hello 2207
Hello 2208
Hello 2209
Hello 2210
Hello 2211
Hello 2212
Hello 2213
Hello 2214
Hello 2215
Hello 2216
Hello 2217
Hello 2218
Hello 2219
Hello 2220
Hello 2221
Hello 2222
Hello 2223
Hello 2224
Hello 2225
Hello 2226
Hello 2227
Hello 2228
Hello 2229
Hello 2230
Hello 2231
Hello 2232
Hello 2233
Hello 2234
Hello 2235
Hello 2236
Hello 2237
Hello 2238
Hello 2239
Hello 2240
Hello 2241
Hello 2242
Hello 2243
Hello 2244
Hello 2245
Hello 2246
Hello 2247
Hello 2248
Hello 2249
Hello 2250
Hello 2251
Hello 2252
Hello 2253
Hello 2254
Hello 2255
Hello 2256
Hello 2257
Hello 2258
Hello 2259
Hello 2260
Hello 2261
Hello 2262
Hello 2263
Hello 2264
Hello 2265
Hello 2266
Hello 2267
Hello 2268
Hello 2269
Hello 2270
Hello 2271
Hello 2272
Hello 2273
Hello 2274
Hello 2275
Hello 2276
Hello 2277
Hello 2278
Hello 2279
Hello 2280
Hello 2281
Hello 2282
Hello 2283
Hello 2284
Hello 2285
Hello 2286
Hello 2287
Hello 2288
Hello 2289
Hello 2290
Hello 2291
Hello 2292
Hello 2293
Hello 2294
Hello 2295
Hello 2296
Hello 2297
Hello 2298
Hello 2299
Hello 2300
Hello 2301
Hello 2302
Hello 2303
Hello 2304
Hello 2305
Hello 2306
Hello 2307
Hello 2308
Hello 2309
Hello 2310
Hello 2311
Hello 2312
Hello 2313
Hello 2314
Hello 2315
Hello 2316
Hello 2317
Hello 2318
Hello 2319
Hello 2320
Hello 2321
Hello 2322
Hello 2323
Hello 2324
Hello 2325
Hello 2326
Hello 2327
Hello 2328
Hello 2329
Hello 2330
Hello 2331
Hello 2332
Hello 2333
Hello 2334
Hello 2335
Hello 2336
Hello 2337
Hello 2338
Hello 2339
Hello 2340
Hello 2341
Hello 2342
Hello 2343
Hello 2344
Hello 2345
Hello 2346
Hello 2347
Hello 2348
Hello 2349
Hello 2350
Hello 2351
Hello 2352
Hello 2353
Hello 2354
Hello 2355
Hello 2356
Hello 2357
Hello 2358
Hello 2359
Hello 2360
Hello 2361
Hello 2362
Hello 2363
Hello 2364
Hello 2365
Hello 2366
Hello 2367
Hello 2368
Hello 2369
Hello 2370
Hello 2371
Hello 2372
Hello 2373
Hello 2374
Hello 2375
Hello 2376
Hello 2377
Hello 2378
Hello 2379
Hello 2380
Hello 2381

 51%|██████████████████████████████████████▉                                     | 2854/5569 [00:01<00:00, 2814.92it/s]

Hello 2382
Hello 2383
Hello 2384
Hello 2385
Hello 2386
Hello 2387
Hello 2388
Hello 2389
Hello 2390
Hello 2391
Hello 2392
Hello 2393
Hello 2394
Hello 2395
Hello 2396
Hello 2397
Hello 2398
Hello 2399
Hello 2400
Hello 2401
Hello 2402
Hello 2403
Hello 2404
Hello 2405
Hello 2406
Hello 2407
Hello 2408
Hello 2409
Hello 2410
Hello 2411
Hello 2412
Hello 2413
Hello 2414
Hello 2415
Hello 2416
Hello 2417
Hello 2418
Hello 2419
Hello 2420
Hello 2421
Hello 2422
Hello 2423
Hello 2424
Hello 2425
Hello 2426
Hello 2427
Hello 2428
Hello 2429
Hello 2430
Hello 2431
Hello 2432
Hello 2433
Hello 2434
Hello 2435
Hello 2436
Hello 2437
Hello 2438
Hello 2439
Hello 2440
Hello 2441
Hello 2442
Hello 2443
Hello 2444
Hello 2445
Hello 2446
Hello 2447
Hello 2448
Hello 2449
Hello 2450
Hello 2451
Hello 2452
Hello 2453
Hello 2454
Hello 2455
Hello 2456
Hello 2457
Hello 2458
Hello 2459
Hello 2460
Hello 2461
Hello 2462
Hello 2463
Hello 2464
Hello 2465
Hello 2466
Hello 2467
Hello 2468
Hello 2469
Hello 2470
Hello 2471
Hello 2472
Hello 2473
Hello 2474
Hello 2475
Hello 2476
Hello 2477
Hello 2478
Hello 2479
Hello 2480
Hello 2481
Hello 2482
Hello 2483
Hello 2484
Hello 2485
Hello 2486
Hello 2487
Hello 2488
Hello 2489
Hello 2490
Hello 2491
Hello 2492
Hello 2493
Hello 2494
Hello 2495
Hello 2496
Hello 2497
Hello 2498
Hello 2499
Hello 2500
Hello 2501
Hello 2502
Hello 2503
Hello 2504
Hello 2505
Hello 2506
Hello 2507
Hello 2508
Hello 2509
Hello 2510
Hello 2511
Hello 2512
Hello 2513
Hello 2514
Hello 2515
Hello 2516
Hello 2517
Hello 2518
Hello 2519
Hello 2520
Hello 2521
Hello 2522
Hello 2523
Hello 2524
Hello 2525
Hello 2526
Hello 2527
Hello 2528
Hello 2529
Hello 2530
Hello 2531
Hello 2532
Hello 2533
Hello 2534
Hello 2535
Hello 2536
Hello 2537
Hello 2538
Hello 2539
Hello 2540
Hello 2541
Hello 2542
Hello 2543
Hello 2544
Hello 2545
Hello 2546
Hello 2547
Hello 2548
Hello 2549
Hello 2550
Hello 2551
Hello 2552
Hello 2553
Hello 2554
Hello 2555
Hello 2556
Hello 2557
Hello 2558
Hello 2559
Hello 2560
Hello 2561
Hello 2562
Hello 2563
Hello 2564
Hello 2565
Hello 2566
Hello 2567
Hello 2568
Hello 2569
Hello 2570
Hello 2571
Hello 2572
Hello 2573
Hello 2574
Hello 2575
Hello 2576
Hello 2577
Hello 2578
Hello 2579
Hello 2580
Hello 2581
Hello 2582
Hello 2583
Hello 2584
Hello 2585
Hello 2586
Hello 2587
Hello 2588
Hello 2589
Hello 2590
Hello 2591
Hello 2592
Hello 2593
Hello 2594
Hello 2595
Hello 2596
Hello 2597
Hello 2598
Hello 2599
Hello 2600
Hello 2601
Hello 2602
Hello 2603
Hello 2604
Hello 2605
Hello 2606
Hello 2607
Hello 2608
Hello 2609
Hello 2610
Hello 2611
Hello 2612
Hello 2613
Hello 2614
Hello 2615
Hello 2616
Hello 2617
Hello 2618
Hello 2619
Hello 2620
Hello 2621
Hello 2622
Hello 2623
Hello 2624
Hello 2625
Hello 2626
Hello 2627
Hello 2628
Hello 2629
Hello 2630
Hello 2631
Hello 2632
Hello 2633
Hello 2634
Hello 2635
Hello 2636
Hello 2637
Hello 2638
Hello 2639
Hello 2640
Hello 2641
Hello 2642
Hello 2643
Hello 2644
Hello 2645
Hello 2646
Hello 2647
Hello 2648
Hello 2649
Hello 2650
Hello 2651
Hello 2652
Hello 2653
Hello 2654
Hello 2655
Hello 2656
Hello 2657
Hello 2658
Hello 2659
Hello 2660
Hello 2661
Hello 2662
Hello 2663
Hello 2664
Hello 2665
Hello 2666
Hello 2667
Hello 2668
Hello 2669
Hello 2670
Hello 2671
Hello 2672
Hello 2673
Hello 2674
Hello 2675
Hello 2676
Hello 2677
Hello 2678
Hello 2679
Hello 2680
Hello 2681
Hello 2682
Hello 2683
Hello 2684
Hello 2685
Hello 2686
Hello 2687
Hello 2688
Hello 2689
Hello 2690
Hello 2691
Hello 2692
Hello 2693
Hello 2694
Hello 2695
Hello 2696
Hello 2697
Hello 2698
Hello 2699
Hello 2700
Hello 2701
Hello 2702
Hello 2703
Hello 2704
Hello 2705
Hello 2706
Hello 2707
Hello 2708
Hello 2709
Hello 2710
Hello 2711
Hello 2712
Hello 2713
Hello 2714
Hello 2715
Hello 2716
Hello 2717
Hello 2718
Hello 2719
Hello 2720
Hello 2721
Hello 2722
Hello 2723
Hello 2724
Hello 2725
Hello 2726
Hello 2727
Hello 2728
Hello 2729
Hello 2730
Hello 2731
Hello 2732
Hello 2733
Hello 2734
Hello 2735
Hello 2736
Hello 2737
Hello 2738
Hello 2739
Hello 2740
Hello 2741
Hello 2742
Hello 2743
Hello 2744
Hello 2745
Hello 2746
Hello 2747
Hello 2748
Hello 2749
Hello 2750
Hello 2751
Hello 2752
Hello 2753
Hello 2754
Hello 2755
Hello 2756
Hello 2757
Hello 2758
Hello 2759
Hello 2760
Hello 2761
Hello 2762
Hello 2763
Hello 2764
Hello 2765
Hello 2766
Hello 2767
Hello 2768
Hello 2769
Hello 2770
Hello 2771
Hello 2772
Hello 2773
Hello 2774
Hello 2775
Hello 2776
Hello 2777
Hello 2778
Hello 2779
Hello 2780
Hello 2781
Hello 2782
Hello 2783
Hello 2784
Hello 2785
Hello 2786
Hello 2787
Hello 2788
Hello 2789
Hello 2790
Hello 2791
Hello 2792
Hello 2793
Hello 2794
Hello 2795
Hello 2796
Hello 2797
Hello 2798
Hello 2799
Hello 2800
Hello 2801
Hello 2802
Hello 2803
Hello 2804
Hello 2805
Hello 2806
Hello 2807
Hello 2808
Hello 2809
Hello 2810
Hello 2811
Hello 2812
Hello 2813
Hello 2814
Hello 2815
Hello 2816
Hello 2817
Hello 2818
Hello 2819
Hello 2820
Hello 2821
Hello 2822
Hello 2823
Hello 2824
Hello 2825
Hello 2826
Hello 2827
Hello 2828
Hello 2829
Hello 2830
Hello 2831
Hello 2832
Hello 2833
Hello 2834
Hello 2835
Hello 2836
Hello 2837
Hello 2838
Hello 2839
Hello 2840
Hello 2841
Hello 2842
Hello 2843
Hello 2844
Hello 2845
Hello 2846
Hello 2847
Hello 2848
Hello 2849
Hello 2850
Hello 2851
Hello 2852
Hello 2853
Hello 2854
Hello 2855
Hello 2856
Hello 2857
Hello 2858
Hello 2859
Hello 2860
Hello 2861
Hello 2862
Hello 2863
Hello 2864
Hello 2865
Hello 2866
Hello 2867
Hello 2868
Hello 2869
Hello 2870
Hello 2871
Hello 2872
Hello 2873
Hello 2874
Hello 2875
Hello 2876
Hello 2877
Hello 2878
Hello 2879
Hello 2880
Hello 2881
Hello 2882
Hello 2883
Hello 2884
Hello 2885
Hello 2886
Hello 2887
Hello 2888
Hello 2889
Hello 2890
Hello 2891
Hello 2892
Hello 2893
Hello 2894
Hello 2895
Hello 2896
Hello 2897
Hello 2898
Hello 2899
Hello 2900
Hello 2901
Hello 2902
Hello 2903
Hello 2904
Hello 2905
Hello 2906
Hello 2907
Hello 2908
Hello 2909
Hello 2910
Hello 2911
Hello 2912
Hello 2913
Hello 2914
Hello 2915
Hello 2916
Hello 2917
Hello 2918
Hello 2919
Hello 2920
Hello 2921
Hello 2922
Hello 2923
Hello 2924
Hello 2925
Hello 2926
Hello 2927
Hello 2928
Hello 2929
Hello 2930
Hello 2931
Hello 2932
Hello 2933
Hello 2934
Hello 2935
Hello 2936
Hello 2937
Hello 2938
Hello 2939
Hello 2940
Hello 2941
Hello 2942
Hello 2943
Hello 2944
Hello 2945
Hello 2946
Hello 2947
Hello 2948
Hello 2949
Hello 2950
Hello 2951
Hello 2952
Hello 2953
Hello 2954
Hello 2955
Hello 2956
Hello 2957
Hello 2958
Hello 2959
Hello 2960
Hello 2961
Hello 2962
Hello 2963
Hello 2964
Hello 2965
Hello 2966
Hello 2967
Hello 2968
Hello 2969
Hello 2970
Hello 2971
Hello 2972
Hello 2973
Hello 2974
Hello 2975
Hello 2976
Hello 2977
Hello 2978
Hello 2979
Hello 2980
Hello 2981
Hello 2982
Hello 2983
Hello 2984
Hello 2985
Hello 2986
Hello 2987
Hello 2988
Hello 2989
Hello 2990
Hello 2991
Hello 2992
Hello 2993
Hello 2994
Hello 2995
Hello 2996
Hello 2997
Hello 2998
Hello 2999
Hello 3000
Hello 3001
Hello 3002
Hello 3003
Hello 3004
Hello 3005
Hello 3006
Hello 3007
Hello 3008
Hello 3009
Hello 3010
Hello 3011
Hello 3012
Hello 3013
Hello 3014
Hello 3015
Hello 3016
Hello 3017
Hello 3018
Hello 3019
Hello 3020
Hello 3021

 65%|█████████████████████████████████████████████████▎                          | 3609/5569 [00:01<00:00, 3183.04it/s]

Hello 3022
Hello 3023
Hello 3024
Hello 3025
Hello 3026
Hello 3027
Hello 3028
Hello 3029
Hello 3030
Hello 3031
Hello 3032
Hello 3033
Hello 3034
Hello 3035
Hello 3036
Hello 3037
Hello 3038
Hello 3039
Hello 3040
Hello 3041
Hello 3042
Hello 3043
Hello 3044
Hello 3045
Hello 3046
Hello 3047
Hello 3048
Hello 3049
Hello 3050
Hello 3051
Hello 3052
Hello 3053
Hello 3054
Hello 3055
Hello 3056
Hello 3057
Hello 3058
Hello 3059
Hello 3060
Hello 3061
Hello 3062
Hello 3063
Hello 3064
Hello 3065
Hello 3066
Hello 3067
Hello 3068
Hello 3069
Hello 3070
Hello 3071
Hello 3072
Hello 3073
Hello 3074
Hello 3075
Hello 3076
Hello 3077
Hello 3078
Hello 3079
Hello 3080
Hello 3081
Hello 3082
Hello 3083
Hello 3084
Hello 3085
Hello 3086
Hello 3087
Hello 3088
Hello 3089
Hello 3090
Hello 3091
Hello 3092
Hello 3093
Hello 3094
Hello 3095
Hello 3096
Hello 3097
Hello 3098
Hello 3099
Hello 3100
Hello 3101
Hello 3102
Hello 3103
Hello 3104
Hello 3105
Hello 3106
Hello 3107
Hello 3108
Hello 3109
Hello 3110
Hello 3111
Hello 3112
Hello 3113
Hello 3114
Hello 3115
Hello 3116
Hello 3117
Hello 3118
Hello 3119
Hello 3120
Hello 3121
Hello 3122
Hello 3123
Hello 3124
Hello 3125
Hello 3126
Hello 3127
Hello 3128
Hello 3129
Hello 3130
Hello 3131
Hello 3132
Hello 3133
Hello 3134
Hello 3135
Hello 3136
Hello 3137
Hello 3138
Hello 3139
Hello 3140
Hello 3141
Hello 3142
Hello 3143
Hello 3144
Hello 3145
Hello 3146
Hello 3147
Hello 3148
Hello 3149
Hello 3150
Hello 3151
Hello 3152
Hello 3153
Hello 3154
Hello 3155
Hello 3156
Hello 3157
Hello 3158
Hello 3159
Hello 3160
Hello 3161
Hello 3162
Hello 3163
Hello 3164
Hello 3165
Hello 3166
Hello 3167
Hello 3168
Hello 3169
Hello 3170
Hello 3171
Hello 3172
Hello 3173
Hello 3174
Hello 3175
Hello 3176
Hello 3177
Hello 3178
Hello 3179
Hello 3180
Hello 3181
Hello 3182
Hello 3183
Hello 3184
Hello 3185
Hello 3186
Hello 3187
Hello 3188
Hello 3189
Hello 3190
Hello 3191
Hello 3192
Hello 3193
Hello 3194
Hello 3195
Hello 3196
Hello 3197
Hello 3198
Hello 3199
Hello 3200
Hello 3201
Hello 3202
Hello 3203
Hello 3204
Hello 3205
Hello 3206
Hello 3207
Hello 3208
Hello 3209
Hello 3210
Hello 3211
Hello 3212
Hello 3213
Hello 3214
Hello 3215
Hello 3216
Hello 3217
Hello 3218
Hello 3219
Hello 3220
Hello 3221
Hello 3222
Hello 3223
Hello 3224
Hello 3225
Hello 3226
Hello 3227
Hello 3228
Hello 3229
Hello 3230
Hello 3231
Hello 3232
Hello 3233
Hello 3234
Hello 3235
Hello 3236
Hello 3237
Hello 3238
Hello 3239
Hello 3240
Hello 3241
Hello 3242
Hello 3243
Hello 3244
Hello 3245
Hello 3246
Hello 3247
Hello 3248
Hello 3249
Hello 3250
Hello 3251
Hello 3252
Hello 3253
Hello 3254
Hello 3255
Hello 3256
Hello 3257
Hello 3258
Hello 3259
Hello 3260
Hello 3261
Hello 3262
Hello 3263
Hello 3264
Hello 3265
Hello 3266
Hello 3267
Hello 3268
Hello 3269
Hello 3270
Hello 3271
Hello 3272
Hello 3273
Hello 3274
Hello 3275
Hello 3276
Hello 3277
Hello 3278
Hello 3279
Hello 3280
Hello 3281
Hello 3282
Hello 3283
Hello 3284
Hello 3285
Hello 3286
Hello 3287
Hello 3288
Hello 3289
Hello 3290
Hello 3291
Hello 3292
Hello 3293
Hello 3294
Hello 3295
Hello 3296
Hello 3297
Hello 3298
Hello 3299
Hello 3300
Hello 3301
Hello 3302
Hello 3303
Hello 3304
Hello 3305
Hello 3306
Hello 3307
Hello 3308
Hello 3309
Hello 3310
Hello 3311
Hello 3312
Hello 3313
Hello 3314
Hello 3315
Hello 3316
Hello 3317
Hello 3318
Hello 3319
Hello 3320
Hello 3321
Hello 3322
Hello 3323
Hello 3324
Hello 3325
Hello 3326
Hello 3327
Hello 3328
Hello 3329
Hello 3330
Hello 3331
Hello 3332
Hello 3333
Hello 3334
Hello 3335
Hello 3336
Hello 3337
Hello 3338
Hello 3339
Hello 3340
Hello 3341
Hello 3342
Hello 3343
Hello 3344
Hello 3345
Hello 3346
Hello 3347
Hello 3348
Hello 3349
Hello 3350
Hello 3351
Hello 3352
Hello 3353
Hello 3354
Hello 3355
Hello 3356
Hello 3357
Hello 3358
Hello 3359
Hello 3360
Hello 3361
Hello 3362
Hello 3363
Hello 3364
Hello 3365
Hello 3366
Hello 3367
Hello 3368
Hello 3369
Hello 3370
Hello 3371
Hello 3372
Hello 3373
Hello 3374
Hello 3375
Hello 3376
Hello 3377
Hello 3378
Hello 3379
Hello 3380
Hello 3381
Hello 3382
Hello 3383
Hello 3384
Hello 3385
Hello 3386
Hello 3387
Hello 3388
Hello 3389
Hello 3390
Hello 3391
Hello 3392
Hello 3393
Hello 3394
Hello 3395
Hello 3396
Hello 3397
Hello 3398
Hello 3399
Hello 3400
Hello 3401
Hello 3402
Hello 3403
Hello 3404
Hello 3405
Hello 3406
Hello 3407
Hello 3408
Hello 3409
Hello 3410
Hello 3411
Hello 3412
Hello 3413
Hello 3414
Hello 3415
Hello 3416
Hello 3417
Hello 3418
Hello 3419
Hello 3420
Hello 3421
Hello 3422
Hello 3423
Hello 3424
Hello 3425
Hello 3426
Hello 3427
Hello 3428
Hello 3429
Hello 3430
Hello 3431
Hello 3432
Hello 3433
Hello 3434
Hello 3435
Hello 3436
Hello 3437
Hello 3438
Hello 3439
Hello 3440
Hello 3441
Hello 3442
Hello 3443
Hello 3444
Hello 3445
Hello 3446
Hello 3447
Hello 3448
Hello 3449
Hello 3450
Hello 3451
Hello 3452
Hello 3453
Hello 3454
Hello 3455
Hello 3456
Hello 3457
Hello 3458
Hello 3459
Hello 3460
Hello 3461
Hello 3462
Hello 3463
Hello 3464
Hello 3465
Hello 3466
Hello 3467
Hello 3468
Hello 3469
Hello 3470
Hello 3471
Hello 3472
Hello 3473
Hello 3474
Hello 3475
Hello 3476
Hello 3477
Hello 3478
Hello 3479
Hello 3480
Hello 3481
Hello 3482
Hello 3483
Hello 3484
Hello 3485
Hello 3486
Hello 3487
Hello 3488
Hello 3489
Hello 3490
Hello 3491
Hello 3492
Hello 3493
Hello 3494
Hello 3495
Hello 3496
Hello 3497
Hello 3498
Hello 3499
Hello 3500
Hello 3501
Hello 3502
Hello 3503
Hello 3504
Hello 3505
Hello 3506
Hello 3507
Hello 3508
Hello 3509
Hello 3510
Hello 3511
Hello 3512
Hello 3513
Hello 3514
Hello 3515
Hello 3516
Hello 3517
Hello 3518
Hello 3519
Hello 3520
Hello 3521
Hello 3522
Hello 3523
Hello 3524
Hello 3525
Hello 3526
Hello 3527
Hello 3528
Hello 3529
Hello 3530
Hello 3531
Hello 3532
Hello 3533
Hello 3534
Hello 3535
Hello 3536
Hello 3537
Hello 3538
Hello 3539
Hello 3540
Hello 3541
Hello 3542
Hello 3543
Hello 3544
Hello 3545
Hello 3546
Hello 3547
Hello 3548
Hello 3549
Hello 3550
Hello 3551
Hello 3552
Hello 3553
Hello 3554
Hello 3555
Hello 3556
Hello 3557
Hello 3558
Hello 3559
Hello 3560
Hello 3561
Hello 3562
Hello 3563
Hello 3564
Hello 3565
Hello 3566
Hello 3567
Hello 3568
Hello 3569
Hello 3570
Hello 3571
Hello 3572
Hello 3573
Hello 3574
Hello 3575
Hello 3576
Hello 3577
Hello 3578
Hello 3579
Hello 3580
Hello 3581
Hello 3582
Hello 3583
Hello 3584
Hello 3585
Hello 3586
Hello 3587
Hello 3588
Hello 3589
Hello 3590
Hello 3591
Hello 3592
Hello 3593
Hello 3594
Hello 3595
Hello 3596
Hello 3597
Hello 3598
Hello 3599
Hello 3600
Hello 3601
Hello 3602
Hello 3603
Hello 3604
Hello 3605
Hello 3606
Hello 3607
Hello 3608
Hello 3609
Hello 3610
Hello 3611
Hello 3612
Hello 3613
Hello 3614
Hello 3615
Hello 3616
Hello 3617
Hello 3618
Hello 3619
Hello 3620
Hello 3621
Hello 3622
Hello 3623
Hello 3624
Hello 3625
Hello 3626
Hello 3627
Hello 3628
Hello 3629
Hello 3630
Hello 3631
Hello 3632
Hello 3633
Hello 3634
Hello 3635
Hello 3636
Hello 3637
Hello 3638
Hello 3639
Hello 3640
Hello 3641
Hello 3642
Hello 3643
Hello 3644
Hello 3645
Hello 3646
Hello 3647
Hello 3648
Hello 3649
Hello 3650
Hello 3651
Hello 3652
Hello 3653
Hello 3654
Hello 3655
Hello 3656
Hello 3657
Hello 3658
Hello 3659
Hello 3660
Hello 3661
Hello 3662
Hello 3663
Hello 3664
Hello 3665
Hello 3666
Hello 3667
Hello 3668
Hello 3669
Hello 3670
Hello 3671
Hello 3672
Hello 3673
Hello 3674
Hello 3675
Hello 3676
Hello 3677
Hello 3678
Hello 3679
Hello 3680
Hello 3681
Hello 3682
Hello 3683
Hello 3684
Hello 3685
Hello 3686
Hello 3687
Hello 3688
Hello 3689
Hello 3690
Hello 3691
Hello 3692
Hello 3693
Hello 3694
Hello 3695
Hello 3696
Hello 3697
Hello 3698
Hello 3699
Hello 3700
Hello 3701
Hello 3702
Hello 3703
Hello 3704

 71%|█████████████████████████████████████████████████████▋                      | 3930/5569 [00:01<00:00, 3085.42it/s]

Hello 3705
Hello 3706
Hello 3707
Hello 3708
Hello 3709
Hello 3710
Hello 3711
Hello 3712
Hello 3713
Hello 3714
Hello 3715
Hello 3716
Hello 3717
Hello 3718
Hello 3719
Hello 3720
Hello 3721
Hello 3722
Hello 3723
Hello 3724
Hello 3725
Hello 3726
Hello 3727
Hello 3728
Hello 3729
Hello 3730
Hello 3731
Hello 3732
Hello 3733
Hello 3734
Hello 3735
Hello 3736
Hello 3737
Hello 3738
Hello 3739
Hello 3740
Hello 3741
Hello 3742
Hello 3743
Hello 3744
Hello 3745
Hello 3746
Hello 3747
Hello 3748
Hello 3749
Hello 3750
Hello 3751
Hello 3752
Hello 3753
Hello 3754
Hello 3755
Hello 3756
Hello 3757
Hello 3758
Hello 3759
Hello 3760
Hello 3761
Hello 3762
Hello 3763
Hello 3764
Hello 3765
Hello 3766
Hello 3767
Hello 3768
Hello 3769
Hello 3770
Hello 3771
Hello 3772
Hello 3773
Hello 3774
Hello 3775
Hello 3776
Hello 3777
Hello 3778
Hello 3779
Hello 3780
Hello 3781
Hello 3782
Hello 3783
Hello 3784
Hello 3785
Hello 3786
Hello 3787
Hello 3788
Hello 3789
Hello 3790
Hello 3791
Hello 3792
Hello 3793
Hello 3794
Hello 3795
Hello 3796
Hello 3797
Hello 3798
Hello 3799
Hello 3800
Hello 3801
Hello 3802
Hello 3803
Hello 3804
Hello 3805
Hello 3806
Hello 3807
Hello 3808
Hello 3809
Hello 3810
Hello 3811
Hello 3812
Hello 3813
Hello 3814
Hello 3815
Hello 3816
Hello 3817
Hello 3818
Hello 3819
Hello 3820
Hello 3821
Hello 3822
Hello 3823
Hello 3824
Hello 3825
Hello 3826
Hello 3827
Hello 3828
Hello 3829
Hello 3830
Hello 3831
Hello 3832
Hello 3833
Hello 3834
Hello 3835
Hello 3836
Hello 3837
Hello 3838
Hello 3839
Hello 3840
Hello 3841
Hello 3842
Hello 3843
Hello 3844
Hello 3845
Hello 3846
Hello 3847
Hello 3848
Hello 3849
Hello 3850
Hello 3851
Hello 3852
Hello 3853
Hello 3854
Hello 3855
Hello 3856
Hello 3857
Hello 3858
Hello 3859
Hello 3860
Hello 3861
Hello 3862
Hello 3863
Hello 3864
Hello 3865
Hello 3866
Hello 3867
Hello 3868
Hello 3869
Hello 3870
Hello 3871
Hello 3872
Hello 3873
Hello 3874
Hello 3875
Hello 3876
Hello 3877
Hello 3878
Hello 3879
Hello 3880
Hello 3881
Hello 3882
Hello 3883
Hello 3884
Hello 3885
Hello 3886
Hello 3887
Hello 3888
Hello 3889
Hello 3890
Hello 3891
Hello 3892
Hello 3893
Hello 3894
Hello 3895
Hello 3896
Hello 3897
Hello 3898
Hello 3899
Hello 3900
Hello 3901
Hello 3902
Hello 3903
Hello 3904
Hello 3905
Hello 3906
Hello 3907
Hello 3908
Hello 3909
Hello 3910
Hello 3911
Hello 3912
Hello 3913
Hello 3914
Hello 3915
Hello 3916
Hello 3917
Hello 3918
Hello 3919
Hello 3920
Hello 3921
Hello 3922
Hello 3923
Hello 3924
Hello 3925
Hello 3926
Hello 3927
Hello 3928
Hello 3929
Hello 3930
Hello 3931
Hello 3932
Hello 3933
Hello 3934
Hello 3935
Hello 3936
Hello 3937
Hello 3938
Hello 3939
Hello 3940
Hello 3941
Hello 3942
Hello 3943
Hello 3944
Hello 3945
Hello 3946
Hello 3947
Hello 3948
Hello 3949
Hello 3950
Hello 3951
Hello 3952
Hello 3953
Hello 3954
Hello 3955
Hello 3956
Hello 3957
Hello 3958
Hello 3959
Hello 3960
Hello 3961
Hello 3962
Hello 3963
Hello 3964
Hello 3965
Hello 3966
Hello 3967
Hello 3968
Hello 3969
Hello 3970
Hello 3971
Hello 3972
Hello 3973
Hello 3974
Hello 3975
Hello 3976
Hello 3977
Hello 3978
Hello 3979
Hello 3980
Hello 3981
Hello 3982
Hello 3983
Hello 3984
Hello 3985
Hello 3986
Hello 3987
Hello 3988
Hello 3989
Hello 3990
Hello 3991
Hello 3992
Hello 3993
Hello 3994
Hello 3995
Hello 3996
Hello 3997
Hello 3998
Hello 3999
Hello 4000
Hello 4001
Hello 4002
Hello 4003
Hello 4004
Hello 4005
Hello 4006
Hello 4007
Hello 4008
Hello 4009
Hello 4010
Hello 4011
Hello 4012
Hello 4013
Hello 4014
Hello 4015
Hello 4016
Hello 4017
Hello 4018
Hello 4019
Hello 4020
Hello 4021
Hello 4022
Hello 4023
Hello 4024
Hello 4025
Hello 4026
Hello 4027
Hello 4028
Hello 4029
Hello 4030
Hello 4031
Hello 4032
Hello 4033
Hello 4034
Hello 4035
Hello 4036
Hello 4037
Hello 4038
Hello 4039
Hello 4040
Hello 4041
Hello 4042
Hello 4043
Hello 4044
Hello 4045
Hello 4046
Hello 4047
Hello 4048
Hello 4049
Hello 4050
Hello 4051
Hello 4052
Hello 4053
Hello 4054
Hello 4055
Hello 4056
Hello 4057
Hello 4058
Hello 4059
Hello 4060
Hello 4061
Hello 4062
Hello 4063
Hello 4064
Hello 4065
Hello 4066
Hello 4067
Hello 4068
Hello 4069
Hello 4070
Hello 4071
Hello 4072
Hello 4073
Hello 4074
Hello 4075
Hello 4076
Hello 4077
Hello 4078
Hello 4079
Hello 4080
Hello 4081
Hello 4082
Hello 4083
Hello 4084
Hello 4085
Hello 4086
Hello 4087
Hello 4088
Hello 4089
Hello 4090
Hello 4091
Hello 4092
Hello 4093
Hello 4094
Hello 4095
Hello 4096
Hello 4097
Hello 4098
Hello 4099
Hello 4100
Hello 4101
Hello 4102
Hello 4103
Hello 4104
Hello 4105
Hello 4106
Hello 4107
Hello 4108
Hello 4109
Hello 4110
Hello 4111
Hello 4112
Hello 4113
Hello 4114
Hello 4115
Hello 4116
Hello 4117
Hello 4118
Hello 4119
Hello 4120
Hello 4121
Hello 4122
Hello 4123
Hello 4124
Hello 4125
Hello 4126
Hello 4127
Hello 4128
Hello 4129
Hello 4130
Hello 4131
Hello 4132
Hello 4133
Hello 4134
Hello 4135
Hello 4136
Hello 4137
Hello 4138
Hello 4139
Hello 4140
Hello 4141
Hello 4142
Hello 4143
Hello 4144
Hello 4145
Hello 4146
Hello 4147
Hello 4148
Hello 4149
Hello 4150
Hello 4151
Hello 4152
Hello 4153
Hello 4154
Hello 4155
Hello 4156
Hello 4157
Hello 4158
Hello 4159
Hello 4160
Hello 4161
Hello 4162
Hello 4163
Hello 4164
Hello 4165
Hello 4166
Hello 4167
Hello 4168
Hello 4169
Hello 4170
Hello 4171
Hello 4172
Hello 4173
Hello 4174
Hello 4175
Hello 4176
Hello 4177
Hello 4178
Hello 4179
Hello 4180
Hello 4181
Hello 4182
Hello 4183
Hello 4184
Hello 4185
Hello 4186
Hello 4187
Hello 4188
Hello 4189
Hello 4190
Hello 4191
Hello 4192
Hello 4193
Hello 4194
Hello 4195
Hello 4196
Hello 4197
Hello 4198
Hello 4199
Hello 4200
Hello 4201
Hello 4202
Hello 4203
Hello 4204
Hello 4205
Hello 4206
Hello 4207
Hello 4208
Hello 4209
Hello 4210
Hello 4211
Hello 4212
Hello 4213
Hello 4214
Hello 4215
Hello 4216
Hello 4217
Hello 4218
Hello 4219
Hello 4220
Hello 4221
Hello 4222
Hello 4223
Hello 4224
Hello 4225
Hello 4226
Hello 4227
Hello 4228
Hello 4229
Hello 4230
Hello 4231
Hello 4232
Hello 4233
Hello 4234
Hello 4235
Hello 4236
Hello 4237
Hello 4238
Hello 4239
Hello 4240

 83%|███████████████████████████████████████████████████████████████▍            | 4646/5569 [00:01<00:00, 3311.06it/s]

Hello 4241
Hello 4242
Hello 4243
Hello 4244
Hello 4245
Hello 4246
Hello 4247
Hello 4248
Hello 4249
Hello 4250
Hello 4251
Hello 4252
Hello 4253
Hello 4254
Hello 4255
Hello 4256
Hello 4257
Hello 4258
Hello 4259
Hello 4260
Hello 4261
Hello 4262
Hello 4263
Hello 4264
Hello 4265
Hello 4266
Hello 4267
Hello 4268
Hello 4269
Hello 4270
Hello 4271
Hello 4272
Hello 4273
Hello 4274
Hello 4275
Hello 4276
Hello 4277
Hello 4278
Hello 4279
Hello 4280
Hello 4281
Hello 4282
Hello 4283
Hello 4284
Hello 4285
Hello 4286
Hello 4287
Hello 4288
Hello 4289
Hello 4290
Hello 4291
Hello 4292
Hello 4293
Hello 4294
Hello 4295
Hello 4296
Hello 4297
Hello 4298
Hello 4299
Hello 4300
Hello 4301
Hello 4302
Hello 4303
Hello 4304
Hello 4305
Hello 4306
Hello 4307
Hello 4308
Hello 4309
Hello 4310
Hello 4311
Hello 4312
Hello 4313
Hello 4314
Hello 4315
Hello 4316
Hello 4317
Hello 4318
Hello 4319
Hello 4320
Hello 4321
Hello 4322
Hello 4323
Hello 4324
Hello 4325
Hello 4326
Hello 4327
Hello 4328
Hello 4329
Hello 4330
Hello 4331
Hello 4332
Hello 4333
Hello 4334
Hello 4335
Hello 4336
Hello 4337
Hello 4338
Hello 4339
Hello 4340
Hello 4341
Hello 4342
Hello 4343
Hello 4344
Hello 4345
Hello 4346
Hello 4347
Hello 4348
Hello 4349
Hello 4350
Hello 4351
Hello 4352
Hello 4353
Hello 4354
Hello 4355
Hello 4356
Hello 4357
Hello 4358
Hello 4359
Hello 4360
Hello 4361
Hello 4362
Hello 4363
Hello 4364
Hello 4365
Hello 4366
Hello 4367
Hello 4368
Hello 4369
Hello 4370
Hello 4371
Hello 4372
Hello 4373
Hello 4374
Hello 4375
Hello 4376
Hello 4377
Hello 4378
Hello 4379
Hello 4380
Hello 4381
Hello 4382
Hello 4383
Hello 4384
Hello 4385
Hello 4386
Hello 4387
Hello 4388
Hello 4389
Hello 4390
Hello 4391
Hello 4392
Hello 4393
Hello 4394
Hello 4395
Hello 4396
Hello 4397
Hello 4398
Hello 4399
Hello 4400
Hello 4401
Hello 4402
Hello 4403
Hello 4404
Hello 4405
Hello 4406
Hello 4407
Hello 4408
Hello 4409
Hello 4410
Hello 4411
Hello 4412
Hello 4413
Hello 4414
Hello 4415
Hello 4416
Hello 4417
Hello 4418
Hello 4419
Hello 4420
Hello 4421
Hello 4422
Hello 4423
Hello 4424
Hello 4425
Hello 4426
Hello 4427
Hello 4428
Hello 4429
Hello 4430
Hello 4431
Hello 4432
Hello 4433
Hello 4434
Hello 4435
Hello 4436
Hello 4437
Hello 4438
Hello 4439
Hello 4440
Hello 4441
Hello 4442
Hello 4443
Hello 4444
Hello 4445
Hello 4446
Hello 4447
Hello 4448
Hello 4449
Hello 4450
Hello 4451
Hello 4452
Hello 4453
Hello 4454
Hello 4455
Hello 4456
Hello 4457
Hello 4458
Hello 4459
Hello 4460
Hello 4461
Hello 4462
Hello 4463
Hello 4464
Hello 4465
Hello 4466
Hello 4467
Hello 4468
Hello 4469
Hello 4470
Hello 4471
Hello 4472
Hello 4473
Hello 4474
Hello 4475
Hello 4476
Hello 4477
Hello 4478
Hello 4479
Hello 4480
Hello 4481
Hello 4482
Hello 4483
Hello 4484
Hello 4485
Hello 4486
Hello 4487
Hello 4488
Hello 4489
Hello 4490
Hello 4491
Hello 4492
Hello 4493
Hello 4494
Hello 4495
Hello 4496
Hello 4497
Hello 4498
Hello 4499
Hello 4500
Hello 4501
Hello 4502
Hello 4503
Hello 4504
Hello 4505
Hello 4506
Hello 4507
Hello 4508
Hello 4509
Hello 4510
Hello 4511
Hello 4512
Hello 4513
Hello 4514
Hello 4515
Hello 4516
Hello 4517
Hello 4518
Hello 4519
Hello 4520
Hello 4521
Hello 4522
Hello 4523
Hello 4524
Hello 4525
Hello 4526
Hello 4527
Hello 4528
Hello 4529
Hello 4530
Hello 4531
Hello 4532
Hello 4533
Hello 4534
Hello 4535
Hello 4536
Hello 4537
Hello 4538
Hello 4539
Hello 4540
Hello 4541
Hello 4542
Hello 4543
Hello 4544
Hello 4545
Hello 4546
Hello 4547
Hello 4548
Hello 4549
Hello 4550
Hello 4551
Hello 4552
Hello 4553
Hello 4554
Hello 4555
Hello 4556
Hello 4557
Hello 4558
Hello 4559
Hello 4560
Hello 4561
Hello 4562
Hello 4563
Hello 4564
Hello 4565
Hello 4566
Hello 4567
Hello 4568
Hello 4569
Hello 4570
Hello 4571
Hello 4572
Hello 4573
Hello 4574
Hello 4575
Hello 4576
Hello 4577
Hello 4578
Hello 4579
Hello 4580
Hello 4581
Hello 4582
Hello 4583
Hello 4584
Hello 4585
Hello 4586
Hello 4587
Hello 4588
Hello 4589
Hello 4590
Hello 4591
Hello 4592
Hello 4593
Hello 4594
Hello 4595
Hello 4596
Hello 4597
Hello 4598
Hello 4599
Hello 4600
Hello 4601
Hello 4602
Hello 4603
Hello 4604
Hello 4605
Hello 4606
Hello 4607
Hello 4608
Hello 4609
Hello 4610
Hello 4611
Hello 4612
Hello 4613
Hello 4614
Hello 4615
Hello 4616
Hello 4617
Hello 4618
Hello 4619
Hello 4620
Hello 4621
Hello 4622
Hello 4623
Hello 4624
Hello 4625
Hello 4626
Hello 4627
Hello 4628
Hello 4629
Hello 4630
Hello 4631
Hello 4632
Hello 4633
Hello 4634
Hello 4635
Hello 4636
Hello 4637
Hello 4638
Hello 4639
Hello 4640
Hello 4641
Hello 4642
Hello 4643
Hello 4644
Hello 4645
Hello 4646
Hello 4647
Hello 4648
Hello 4649
Hello 4650
Hello 4651
Hello 4652
Hello 4653
Hello 4654
Hello 4655
Hello 4656
Hello 4657
Hello 4658
Hello 4659
Hello 4660
Hello 4661
Hello 4662
Hello 4663
Hello 4664
Hello 4665
Hello 4666
Hello 4667
Hello 4668
Hello 4669
Hello 4670
Hello 4671
Hello 4672
Hello 4673
Hello 4674
Hello 4675
Hello 4676
Hello 4677
Hello 4678
Hello 4679
Hello 4680
Hello 4681
Hello 4682
Hello 4683
Hello 4684
Hello 4685
Hello 4686
Hello 4687
Hello 4688
Hello 4689
Hello 4690
Hello 4691
Hello 4692
Hello 4693
Hello 4694
Hello 4695
Hello 4696
Hello 4697
Hello 4698
Hello 4699
Hello 4700
Hello 4701
Hello 4702
Hello 4703
Hello 4704
Hello 4705
Hello 4706
Hello 4707
Hello 4708
Hello 4709
Hello 4710
Hello 4711
Hello 4712
Hello 4713
Hello 4714
Hello 4715
Hello 4716
Hello 4717
Hello 4718
Hello 4719
Hello 4720
Hello 4721
Hello 4722
Hello 4723
Hello 4724
Hello 4725
Hello 4726
Hello 4727
Hello 4728
Hello 4729
Hello 4730
Hello 4731
Hello 4732
Hello 4733
Hello 4734
Hello 4735
Hello 4736
Hello 4737
Hello 4738
Hello 4739
Hello 4740
Hello 4741
Hello 4742
Hello 4743
Hello 4744
Hello 4745
Hello 4746
Hello 4747
Hello 4748
Hello 4749
Hello 4750
Hello 4751
Hello 4752
Hello 4753
Hello 4754
Hello 4755
Hello 4756
Hello 4757
Hello 4758
Hello 4759
Hello 4760
Hello 4761
Hello 4762
Hello 4763
Hello 4764
Hello 4765
Hello 4766
Hello 4767
Hello 4768
Hello 4769
Hello 4770
Hello 4771
Hello 4772
Hello 4773
Hello 4774
Hello 4775
Hello 4776
Hello 4777
Hello 4778
Hello 4779
Hello 4780
Hello 4781
Hello 4782
Hello 4783
Hello 4784
Hello 4785
Hello 4786
Hello 4787
Hello 4788
Hello 4789
Hello 4790
Hello 4791
Hello 4792
Hello 4793
Hello 4794
Hello 4795
Hello 4796
Hello 4797
Hello 4798
Hello 4799
Hello 4800
Hello 4801
Hello 4802
Hello 4803
Hello 4804
Hello 4805
Hello 4806
Hello 4807
Hello 4808
Hello 4809
Hello 4810
Hello 4811
Hello 4812
Hello 4813
Hello 4814
Hello 4815
Hello 4816
Hello 4817
Hello 4818
Hello 4819
Hello 4820
Hello 4821
Hello 4822
Hello 4823
Hello 4824
Hello 4825
Hello 4826
Hello 4827
Hello 4828
Hello 4829
Hello 4830
Hello 4831
Hello 4832
Hello 4833
Hello 4834
Hello 4835
Hello 4836
Hello 4837
Hello 4838
Hello 4839
Hello 4840
Hello 4841
Hello 4842
Hello 4843
Hello 4844
Hello 4845
Hello 4846
Hello 4847
Hello 4848
Hello 4849
Hello 4850
Hello 4851
Hello 4852
Hello 4853
Hello 4854
Hello 4855
Hello 4856
Hello 4857
Hello 4858
Hello 4859
Hello 4860
Hello 4861
Hello 4862
Hello 4863
Hello 4864
Hello 4865
Hello 4866
Hello 4867
Hello 4868
Hello 4869
Hello 4870
Hello 4871
Hello 4872
Hello 4873
Hello 4874
Hello 4875
Hello 4876
Hello 4877
Hello 4878
Hello 4879
Hello 4880
Hello 4881
Hello 4882
Hello 4883
Hello 4884
Hello 4885
Hello 4886
Hello 4887
Hello 4888
Hello 4889
Hello 4890
Hello 4891
Hello 4892
Hello 4893
Hello 4894
Hello 4895
Hello 4896
Hello 4897
Hello 4898
Hello 4899
Hello 4900
Hello 4901
Hello 4902
Hello 4903
Hello 4904
Hello 4905
Hello 4906
Hello 4907
Hello 4908
Hello 4909
Hello 4910
Hello 4911
Hello 4912
Hello 4913
Hello 4914
Hello 4915
Hello 4916
Hello 4917
Hello 4918
Hello 4919
Hello 4920
Hello 4921
Hello 4922
Hello 4923
Hello 4924
Hello 4925
Hello 4926
Hello 4927
Hello 4928
Hello 4929
Hello 4930
Hello 4931
Hello 4932
Hello 4933
Hello 4934
Hello 4935
Hello 4936
Hello 4937
Hello 4938
Hello 4939
Hello 4940
Hello 4941
Hello 4942
Hello 4943
Hello 4944
Hello 4945
Hello 4946
Hello 4947
Hello 4948
Hello 4949
Hello 4950
Hello 4951
Hello 4952
Hello 4953
Hello 4954
Hello 4955
Hello 4956
Hello 4957
Hello 4958
Hello 4959
Hello 4960
Hello 4961
Hello 4962
Hello 4963
Hello 4964
Hello 4965
Hello 4966
Hello 4967
Hello 4968
Hello 4969

 95%|████████████████████████████████████████████████████████████████████████▌   | 5315/5569 [00:01<00:00, 3099.42it/s]

Hello 4970
Hello 4971
Hello 4972
Hello 4973
Hello 4974
Hello 4975
Hello 4976
Hello 4977
Hello 4978
Hello 4979
Hello 4980
Hello 4981
Hello 4982
Hello 4983
Hello 4984
Hello 4985
Hello 4986
Hello 4987
Hello 4988
Hello 4989
Hello 4990
Hello 4991
Hello 4992
Hello 4993
Hello 4994
Hello 4995
Hello 4996
Hello 4997
Hello 4998
Hello 4999
Hello 5000
Hello 5001
Hello 5002
Hello 5003
Hello 5004
Hello 5005
Hello 5006
Hello 5007
Hello 5008
Hello 5009
Hello 5010
Hello 5011
Hello 5012
Hello 5013
Hello 5014
Hello 5015
Hello 5016
Hello 5017
Hello 5018
Hello 5019
Hello 5020
Hello 5021
Hello 5022
Hello 5023
Hello 5024
Hello 5025
Hello 5026
Hello 5027
Hello 5028
Hello 5029
Hello 5030
Hello 5031
Hello 5032
Hello 5033
Hello 5034
Hello 5035
Hello 5036
Hello 5037
Hello 5038
Hello 5039
Hello 5040
Hello 5041
Hello 5042
Hello 5043
Hello 5044
Hello 5045
Hello 5046
Hello 5047
Hello 5048
Hello 5049
Hello 5050
Hello 5051
Hello 5052
Hello 5053
Hello 5054
Hello 5055
Hello 5056
Hello 5057
Hello 5058
Hello 5059
Hello 5060
Hello 5061
Hello 5062
Hello 5063
Hello 5064
Hello 5065
Hello 5066
Hello 5067
Hello 5068
Hello 5069
Hello 5070
Hello 5071
Hello 5072
Hello 5073
Hello 5074
Hello 5075
Hello 5076
Hello 5077
Hello 5078
Hello 5079
Hello 5080
Hello 5081
Hello 5082
Hello 5083
Hello 5084
Hello 5085
Hello 5086
Hello 5087
Hello 5088
Hello 5089
Hello 5090
Hello 5091
Hello 5092
Hello 5093
Hello 5094
Hello 5095
Hello 5096
Hello 5097
Hello 5098
Hello 5099
Hello 5100
Hello 5101
Hello 5102
Hello 5103
Hello 5104
Hello 5105
Hello 5106
Hello 5107
Hello 5108
Hello 5109
Hello 5110
Hello 5111
Hello 5112
Hello 5113
Hello 5114
Hello 5115
Hello 5116
Hello 5117
Hello 5118
Hello 5119
Hello 5120
Hello 5121
Hello 5122
Hello 5123
Hello 5124
Hello 5125
Hello 5126
Hello 5127
Hello 5128
Hello 5129
Hello 5130
Hello 5131
Hello 5132
Hello 5133
Hello 5134
Hello 5135
Hello 5136
Hello 5137
Hello 5138
Hello 5139
Hello 5140
Hello 5141
Hello 5142
Hello 5143
Hello 5144
Hello 5145
Hello 5146
Hello 5147
Hello 5148
Hello 5149
Hello 5150
Hello 5151
Hello 5152
Hello 5153
Hello 5154
Hello 5155
Hello 5156
Hello 5157
Hello 5158
Hello 5159
Hello 5160
Hello 5161
Hello 5162
Hello 5163
Hello 5164
Hello 5165
Hello 5166
Hello 5167
Hello 5168
Hello 5169
Hello 5170
Hello 5171
Hello 5172
Hello 5173
Hello 5174
Hello 5175
Hello 5176
Hello 5177
Hello 5178
Hello 5179
Hello 5180
Hello 5181
Hello 5182
Hello 5183
Hello 5184
Hello 5185
Hello 5186
Hello 5187
Hello 5188
Hello 5189
Hello 5190
Hello 5191
Hello 5192
Hello 5193
Hello 5194
Hello 5195
Hello 5196
Hello 5197
Hello 5198
Hello 5199
Hello 5200
Hello 5201
Hello 5202
Hello 5203
Hello 5204
Hello 5205
Hello 5206
Hello 5207
Hello 5208
Hello 5209
Hello 5210
Hello 5211
Hello 5212
Hello 5213
Hello 5214
Hello 5215
Hello 5216
Hello 5217
Hello 5218
Hello 5219
Hello 5220
Hello 5221
Hello 5222
Hello 5223
Hello 5224
Hello 5225
Hello 5226
Hello 5227
Hello 5228
Hello 5229
Hello 5230
Hello 5231
Hello 5232
Hello 5233
Hello 5234
Hello 5235
Hello 5236
Hello 5237
Hello 5238
Hello 5239
Hello 5240
Hello 5241
Hello 5242
Hello 5243
Hello 5244
Hello 5245
Hello 5246
Hello 5247
Hello 5248
Hello 5249
Hello 5250
Hello 5251
Hello 5252
Hello 5253
Hello 5254
Hello 5255
Hello 5256
Hello 5257
Hello 5258
Hello 5259
Hello 5260
Hello 5261
Hello 5262
Hello 5263
Hello 5264
Hello 5265
Hello 5266
Hello 5267
Hello 5268
Hello 5269
Hello 5270
Hello 5271
Hello 5272
Hello 5273
Hello 5274
Hello 5275
Hello 5276
Hello 5277
Hello 5278
Hello 5279
Hello 5280
Hello 5281
Hello 5282
Hello 5283
Hello 5284
Hello 5285
Hello 5286
Hello 5287
Hello 5288
Hello 5289
Hello 5290
Hello 5291
Hello 5292
Hello 5293
Hello 5294
Hello 5295
Hello 5296
Hello 5297
Hello 5298
Hello 5299
Hello 5300
Hello 5301
Hello 5302
Hello 5303
Hello 5304
Hello 5305
Hello 5306
Hello 5307
Hello 5308
Hello 5309
Hello 5310
Hello 5311
Hello 5312
Hello 5313
Hello 5314
Hello 5315
Hello 5316
Hello 5317
Hello 5318
Hello 5319
Hello 5320
Hello 5321
Hello 5322
Hello 5323
Hello 5324
Hello 5325
Hello 5326
Hello 5327
Hello 5328
Hello 5329
Hello 5330
Hello 5331
Hello 5332
Hello 5333
Hello 5334
Hello 5335
Hello 5336
Hello 5337
Hello 5338
Hello 5339
Hello 5340
Hello 5341
Hello 5342
Hello 5343
Hello 5344
Hello 5345
Hello 5346
Hello 5347
Hello 5348
Hello 5349
Hello 5350
Hello 5351
Hello 5352
Hello 5353
Hello 5354
Hello 5355
Hello 5356
Hello 5357
Hello 5358
Hello 5359
Hello 5360
Hello 5361
Hello 5362
Hello 5363
Hello 5364
Hello 5365
Hello 5366
Hello 5367
Hello 5368
Hello 5369
Hello 5370
Hello 5371
Hello 5372
Hello 5373
Hello 5374
Hello 5375
Hello 5376
Hello 5377
Hello 5378
Hello 5379
Hello 5380
Hello 5381
Hello 5382
Hello 5383
Hello 5384
Hello 5385
Hello 5386
Hello 5387
Hello 5388
Hello 5389
Hello 5390
Hello 5391
Hello 5392
Hello 5393
Hello 5394
Hello 5395
Hello 5396
Hello 5397
Hello 5398
Hello 5399
Hello 5400
Hello 5401
Hello 5402
Hello 5403
Hello 5404
Hello 5405
Hello 5406
Hello 5407
Hello 5408
Hello 5409
Hello 5410
Hello 5411
Hello 5412
Hello 5413
Hello 5414
Hello 5415
Hello 5416
Hello 5417
Hello 5418
Hello 5419
Hello 5420
Hello 5421
Hello 5422
Hello 5423
Hello 5424
Hello 5425
Hello 5426
Hello 5427
Hello 5428
Hello 5429
Hello 5430
Hello 5431
Hello 5432
Hello 5433
Hello 5434
Hello 5435
Hello 5436
Hello 5437
Hello 5438
Hello 5439
Hello 5440
Hello 5441
Hello 5442
Hello 5443
Hello 5444
Hello 5445
Hello 5446
Hello 5447
Hello 5448
Hello 5449
Hello 5450
Hello 5451
Hello 5452
Hello 5453
Hello 5454
Hello 5455
Hello 5456
Hello 5457
Hello 5458
Hello 5459
Hello 5460
Hello 5461
Hello 5462
Hello 5463
Hello 5464
Hello 5465
Hello 5466
Hello 5467
Hello 5468
Hello 5469
Hello 5470
Hello 5471
Hello 5472
Hello 5473
Hello 5474
Hello 5475
Hello 5476
Hello 5477
Hello 5478
Hello 5479
Hello 5480
Hello 5481
Hello 5482
Hello 5483
Hello 5484
Hello 5485
Hello 5486
Hello 5487
Hello 5488
Hello 5489
Hello 5490
Hello 5491
Hello 5492
Hello 5493
Hello 5494
Hello 5495
Hello 5496
Hello 5497
Hello 5498
Hello 5499
Hello 5500
Hello 5501
Hello 5502
Hello 5503
Hello 5504
Hello 5505
Hello 5506
Hello 5507
Hello 5508
Hello 5509
Hello 5510
Hello 5511
Hello 5512
Hello 5513
Hello 5514
Hello 5515
Hello 5516
Hello 5517
Hello 5518
Hello 5519
Hello 5520
Hello 5521
Hello 5522
Hello 5523
Hello 5524
Hello 5525
Hello 5526
Hello 5527
Hello 5528
Hello 5529
Hello 5530
Hello 5531
Hello 5532
Hello 5533
Hello 5534
Hello 5535
Hello 5536
Hello 5537
Hello 5538
Hello 5539
Hello 5540
Hello 5541
Hello 5542

100%|████████████████████████████████████████████████████████████████████████████| 5569/5569 [00:01<00:00, 2992.90it/s]

Hello 5543
Hello 5544
Hello 5545
Hello 5546
Hello 5547
Hello 5548
Hello 5549
Hello 5550
Hello 5551
Hello 5552
Hello 5553
Hello 5554
Hello 5555
Hello 5556
Hello 5557
Hello 5558
Hello 5559
Hello 5560
Hello 5561
Hello 5562
Hello 5563
Hello 5564
Hello 5565
Hello 5566
Hello 5567
Hello 5568

In [96]:
len(X)

5569

In [97]:
## Independent Features (convert X to array)
X_new=np.array(X)

In [101]:
## Lets view the first sentence vector
len(X_new[0])

100

In [102]:
X_new[0]

array([-0.185, 0.163, 0.0751, 0.0973, 0.0459, -0.463, 0.154, 0.505, -0.244, -0.127, -0.218, -0.37, -0.0737, 0.0851, 0.161, -0.183, 0.144, -0.335, -0.0157, -0.562, 0.217, 0.0875, 0.163, -0.166, 0.0416, -0.00407, -0.242, -0.2, -0.271, 0.0398, 0.26, -0.0326, 0.15, -0.208, -0.127, 0.342, -0.0111, -0.164, -0.177, -0.503, 0.00929, -0.181, -0.166, 0.0219, 0.194, -0.0389, -0.188, -0.0858, 0.233, 0.14, 0.142, -0.188, -0.0857, 0.0292, -0.0735, 0.0207, 0.185, 0.104, -0.382, 0.137, 0.00311, 0.0483, -0.101, -0.102, -0.293, 0.237, 0.0313, 0.214, -0.302, 0.318, -0.175, 0.216, 0.348, -0.0828, 0.312, -0.0019, 0.051, -0.143, -0.171, 0.0829, -0.216, -0.0511, -0.253, 0.461, -0.177, -0.0931, 0.125, 0.229, 0.36, 0.0597, 0.337, 0.136, 0.0579, 0.0451, 0.53, 0.19, 0.146, -0.221, 0.162, -0.0105])

In [107]:
## dependent feature
y=pd.get_dummies(messages['label'], dtype=int)
y

      ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5572 rows x 2 columns]

In [108]:
y=y.spam
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: spam, Length: 5572, dtype: int32

In [109]:
X_new.shape, y.shape

((5569, 100), (5572,))

Notice both independent and dependent feature shapes are different. This will be a big problem when training. This means some sentences were removed from the corpus probably when stemming and removal of unwanted characters occurred. We have to find a way to track which indices were affected.

In [111]:
## Output features
y=messages[list(map(lambda x: len(x)>0,corpus))] ## check chat for explanation of this code
y=pd.get_dummies(y['label'],dtype=int)
y=y.spam
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: spam, Length: 5569, dtype: int32

In [112]:
y.shape

(5569,)

It is finally balanced.

Now remember that Xdata has to be in form of a dataframe therefore we will add each sentence vector into a dataframe object

In [117]:
## This is the final independent feature
X_df=pd.DataFrame(X_new)
X_df

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.184982,0.163262,0.075147,0.097303,0.045886,-0.462591,0.154398,0.505150,-0.243620,-0.127087,...,0.336760,0.136076,0.057934,0.045132,0.530284,0.189758,0.145969,-0.220838,0.161787,-0.010482
1,-0.175133,0.144486,0.065442,0.086965,0.051005,-0.417292,0.129460,0.457911,-0.217574,-0.106290,...,0.308661,0.115721,0.047997,0.035786,0.467002,0.164867,0.131724,-0.207933,0.152142,-0.017329
2,-0.198795,0.182539,0.076223,0.112959,0.015754,-0.497793,0.155690,0.497210,-0.260744,-0.164090,...,0.339746,0.132687,0.040543,0.024993,0.550302,0.182513,0.105386,-0.260281,0.190212,0.011749
3,-0.252871,0.215704,0.096075,0.134147,0.068561,-0.625823,0.204914,0.686382,-0.328773,-0.159444,...,0.455637,0.181507,0.078689,0.068409,0.707689,0.258397,0.208596,-0.300263,0.219595,-0.024224
4,-0.224200,0.181211,0.090975,0.113476,0.064239,-0.539855,0.174461,0.594916,-0.286194,-0.145597,...,0.397500,0.153229,0.070571,0.057807,0.611103,0.221767,0.171847,-0.269895,0.185127,-0.017054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5564,-0.226930,0.213988,0.101187,0.129790,0.037253,-0.567138,0.189083,0.596242,-0.303766,-0.179113,...,0.404846,0.161053,0.063579,0.037892,0.646333,0.217637,0.139440,-0.285979,0.209026,0.007906
5565,-0.229007,0.194089,0.088067,0.126310,0.052720,-0.561647,0.187193,0.601273,-0.306657,-0.154256,...,0.408528,0.164346,0.050940,0.042974,0.630841,0.220372,0.154833,-0.287896,0.203002,-0.001137
5566,-0.254682,0.220025,0.097070,0.122927,0.056829,-0.614689,0.204488,0.682125,-0.326320,-0.173711,...,0.455744,0.191131,0.085308,0.071542,0.710390,0.261239,0.209338,-0.287596,0.208787,-0.019422
5567,-0.229988,0.197074,0.089614,0.118725,0.051113,-0.562893,0.180481,0.611688,-0.296551,-0.162373,...,0.406019,0.164185,0.074576,0.056761,0.642431,0.232574,0.170648,-0.271433,0.191970,-0.015411
5568,-0.256025,0.207637,0.099819,0.134083,0.064312,-0.622231,0.195596,0.673643,-0.323391,-0.179398,...,0.444378,0.178535,0.079378,0.058902,0.702213,0.256420,0.184681,-0.304488,0.211739,-0.016088

In [118]:
X_df.shape

(5569, 100)

This is a more straight forward way. Below is another way as well if you want to add them one by one

In [119]:
X_df_alt = pd.DataFrame()

for i in range(len(X_new)):
    X_df_alt = pd.concat(
        [X_df_alt, pd.DataFrame(X_new[i].reshape(1, -1))],
        ignore_index=True
    )

In [120]:
X_df_alt.shape

(5569, 100)

In [121]:
X_df_alt

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.184982,0.163262,0.075147,0.097303,0.045886,-0.462591,0.154398,0.505150,-0.243620,-0.127087,...,0.336760,0.136076,0.057934,0.045132,0.530284,0.189758,0.145969,-0.220838,0.161787,-0.010482
1,-0.175133,0.144486,0.065442,0.086965,0.051005,-0.417292,0.129460,0.457911,-0.217574,-0.106290,...,0.308661,0.115721,0.047997,0.035786,0.467002,0.164867,0.131724,-0.207933,0.152142,-0.017329
2,-0.198795,0.182539,0.076223,0.112959,0.015754,-0.497793,0.155690,0.497210,-0.260744,-0.164090,...,0.339746,0.132687,0.040543,0.024993,0.550302,0.182513,0.105386,-0.260281,0.190212,0.011749
3,-0.252871,0.215704,0.096075,0.134147,0.068561,-0.625823,0.204914,0.686382,-0.328773,-0.159444,...,0.455637,0.181507,0.078689,0.068409,0.707689,0.258397,0.208596,-0.300263,0.219595,-0.024224
4,-0.224200,0.181211,0.090975,0.113476,0.064239,-0.539855,0.174461,0.594916,-0.286194,-0.145597,...,0.397500,0.153229,0.070571,0.057807,0.611103,0.221767,0.171847,-0.269895,0.185127,-0.017054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5564,-0.226930,0.213988,0.101187,0.129790,0.037253,-0.567138,0.189083,0.596242,-0.303766,-0.179113,...,0.404846,0.161053,0.063579,0.037892,0.646333,0.217637,0.139440,-0.285979,0.209026,0.007906
5565,-0.229007,0.194089,0.088067,0.126310,0.052720,-0.561647,0.187193,0.601273,-0.306657,-0.154256,...,0.408528,0.164346,0.050940,0.042974,0.630841,0.220372,0.154833,-0.287896,0.203002,-0.001137
5566,-0.254682,0.220025,0.097070,0.122927,0.056829,-0.614689,0.204488,0.682125,-0.326320,-0.173711,...,0.455744,0.191131,0.085308,0.071542,0.710390,0.261239,0.209338,-0.287596,0.208787,-0.019422
5567,-0.229988,0.197074,0.089614,0.118725,0.051113,-0.562893,0.180481,0.611688,-0.296551,-0.162373,...,0.406019,0.164185,0.074576,0.056761,0.642431,0.232574,0.170648,-0.271433,0.191970,-0.015411
5568,-0.256025,0.207637,0.099819,0.134083,0.064312,-0.622231,0.195596,0.673643,-0.323391,-0.179398,...,0.444378,0.178535,0.079378,0.058902,0.702213,0.256420,0.184681,-0.304488,0.211739,-0.016088

Its the same outcome but the first is faster and saves time.

In [122]:
## Train test split
from sklearn.model_selection import train_test_split

In [123]:
X_train,X_test,y_train,y_test=train_test_split(X_df,y,test_size=0.2,random_state=42)

In [124]:
## Since these are dense vectors we can apply randomforest
from sklearn.ensemble import RandomForestClassifier

In [125]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [126]:
y_pred=rf.predict(X_test)

In [127]:
from sklearn.metrics import accuracy_score, classification_report

In [128]:
accuracy_score(y_test,y_pred)

0.973967684021544

In [129]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       955
           1       0.93      0.88      0.91       159

    accuracy                           0.97      1114
   macro avg       0.96      0.94      0.95      1114
weighted avg       0.97      0.97      0.97      1114

A very good model. Please do well to attempt hyperparameter tuning for improved model performance.